spring:
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/data_loader
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

## Swagger properties
open-api:
  tokenBaseUrl: http://localhost:8080/eca-oauth

minio:
  url: http://s3-minio-storage:9000

auth-server:
  baseUrl: http://eca-oauth:8080
