= Библиотека для работы с шаблонами фильтрами
:toc:
:toc-title: Оглавление

== Введение

В данном документе приведена инструкция для подключения библиотеки фильтрации к spring boot приложению.

== 1. Подключение библиотеки

Для начала, необходимо добавить зависимость в pom.xml

[source,xml]
----
<dependency>
    <groupId>eca.service</groupId>
    <artifactId>core-filter</artifactId>
    <version>${project.version}</version>
</dependency>
----

Добавить шаблоны фильтров в папку resources:

resources/

   filter-templates/

      templates/

         evaluationresultshistorytemplate.json

      dictionaries/

         classifier.json

         evaluationmethod.json

Привер json кофигурации с шаблоном фильтра:

[source,json]
----
{
  "templateName": "Фильтр для истории результатов классификации",
  "templateType": "EVALUATION_RESULTS_HISTORY_TEMPLATE",
  "fields": [
    {
      "fieldName": "classifierName",
      "description": "Классификатор",
      "filterFieldType": "REFERENCE",
      "matchMode": "EQUALS",
      "multiple": true,
      "dictionary": {
        "name": "classifier",
        "values": null
      }
    },
    {
      "fieldName": "instancesInfo.id",
      "description": "Обучающая выборка",
      "filterFieldType": "LAZY_REFERENCE",
      "matchMode": "EQUALS",
      "multiple": false,
      "dictionary": null
    },
    {
      "fieldName": "evaluationMethod",
      "description": "Метод оценки точности",
      "filterFieldType": "REFERENCE",
      "matchMode": "EQUALS",
      "multiple": false,
      "dictionary": {
        "name": "evaluationMethod",
        "values": null
      }
    },
    {
      "fieldName": "saveDate",
      "description": "Дата сохранения результатов",
      "filterFieldType": "DATE",
      "matchMode": "RANGE",
      "multiple": true,
      "dictionary": null
    }
  ],
  "globalFilterFields": [
    "relationName",
    "evaluationMethod",
    "classifierName"
  ],
  "sortFields": [
    "saveDate",
    "relationName",
    "classifierName",
    "statistics.pctCorrect",
    "statistics.meanAbsoluteError",
    "statistics.rootMeanSquaredError",
    "statistics.maxAucValue",
    "statistics.varianceError"
  ]
}
----

* fields - список полей для фильтрации
* globalFilterFields - список полей для полнотекстового поиска
* sortFields - список полей для сортировки

Привер json кофигурации с шаблоном справочника для полей фильтра:

[source,json]
----
{
  "name": "evaluationMethod",
  "values": [
    {
      "label": "Использование обучающего множества",
      "value": "TRAINING_DATA"
    },
    {
      "label": "V-блочная кросс-проверка",
      "value": "CROSS_VALIDATION"
    }
  ]
}
----

== 3. Примеры использования

Ниже приведен пример контроллера для получения шаблона фильтра:

[source,java]
----
@Slf4j
@RestController
@RequestMapping("/filters")
@RequiredArgsConstructor
public class FilterController {

    private final FilterTemplateService filterTemplateService;

    /**
     * Gets filter fields.
     *
     * @return filter fields list
     */
    @GetMapping(value = "/fields")
    public List<FilterFieldDto> getFilterFields() {
        return filterTemplateService.getFilterFields("filterName");
    }

    /**
     * Gets filter dictionary.
     *
     * @return filter dictionary
     */
    @GetMapping(value = "/dictionary")
    public FilterDictionaryDto getFilterDictionary() {
        return filterTemplateService.getFilterDictionary("dictionaryName");
    }
}
----

Ниже приведен пример использования класса AbstractFilter для фильтрации и сортировки данных:

[source,java]
----
@Slf4j
@Service
@RequiredArgsConstructor
public class AppService {

    private final FilterTemplateService filterTemplateService;
    private final MyEntityRepository myEntityRepository;

    public Page<MyEntity> getNextPage(PageRequestDto pageRequestDto) {
        List<String> globalFilterFields = filterService.getGlobalFilterFields("globalFilterName");
        AbstractFilter filter = new MyFilterImpl(pageRequestDto.getSearchQuery(), globalFilterFields,
                pageRequestDto.getFilters());
        return myEntityRepository.findAll(filter, PageRequest.of(pageRequestDto.getPage(), pageRequestDto.getSize()));
    }
}
----
