= Библиотека фильтрации
:toc:
:toc-title: Оглавление

== Введение

В данном документе приведена инструкция для подключения библиотеки фильтрации к spring boot приложению.

== 1. Подключение библиотеки

Для начала, необходимо добавить зависимость в pom.xml

[source,xml]
----
<dependency>
    <groupId>eca.service</groupId>
    <artifactId>core-filter</artifactId>
    <version>${project.version}</version>
</dependency>
----

С помощью аннотации @EnableFilters импортировать бины библиотеки

[source,java]
----
@EnableFilters
@EnableCaching
@Configuration
public class AppConfiguration {
}
----

Примечание: с помощью аннотации @EnableCaching включается использование spring кэша.

В конфигурационный файл liquibase, добавить путь к файлу filter-template-changelog.xml со скриптами для создания служебных таблиц фильтрации.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">
    <!-- your change sets -->
    <include file="../filter-template-changelog.xml" relativeToChangelogFile="true"/>
</databaseChangeLog>
----

Также можно настроить параметры кэша. Ниже приведен пример файла application.yml с настройками кэша от caffeine:

[source,yml]
----
spring:
  cache:
    cache-names: global-filters, filter-templates, filter-dictionaries
    caffeine:
      spec: maximumSize=100, expireAfterWrite=18000s
----

== 2. Описание таблиц библиотеки фильтрации

Таблица 2.1 - 'global_filter_template' - содержит конфигурацию полей для глобального поиска
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                      |bigint           |+|+|+                  |Идентификатор записи (первичный ключ)
|filter_name             |varchar(255)     |-|+|-                  |Название фильтра
|template_type           |varchar(255)     |-|+|-                  |Тип шаблона
|===

Таблица 2.2 - 'global_filter_field' - содержит данные полей для глобального поиска
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                         |bigint           |+|+|+                                 |Идентификатор записи (первичный ключ)
|field_name                 |varchar(255)     |-|+|-                                 |Название поля в сущности
|global_filter_template_id  |bigint           |-|+|fk_global_filter_template_id      |Внешний ключ, ID шаблона
|===

Таблица 2.3 - 'filter_template' - содержит данные шаблонов фильтров для web приложения
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                      |bigint           |+|+|+                  |Идентификатор записи (первичный ключ)
|template_name           |varchar(255)     |-|+|-                  |Название шаблона
|template_type           |varchar(255)     |-|+|-                  |Тип шаблона
|created                 |timestamp        |-|+|-                  |Дата создания шаблона
|===

Таблица 2.4 - 'filter_dictionary' - содержит данные словарей
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                         |bigint           |+|+|+                                 |Идентификатор записи (первичный ключ)
|name                       |varchar(255)     |-|+|-                                 |Название словаря
|===

Таблица 2.5 - 'filter_dictionary_value' - содержит данные значений словарей
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                         |bigint           |+|+|+                                 |Идентификатор записи (первичный ключ)
|label                      |varchar(255)     |-|+|-                                 |Описание значения
|value                      |varchar(255)     |-|+|-                                 |Значение
|filter_dictionary_id       |bigint           |-|+|fk_filter_dictionary_id           |Внешний ключ, ID словаря
|===

Таблица 2.6 - 'filter_field' - содержит данные полей для фильтров
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                         |bigint           |+|+|+                                 |Идентификатор записи (первичный ключ)
|field_name                 |varchar(255)     |-|+|-                                 |Название поля в сущности
|description                |varchar(255)     |-|+|-                                 |Описание поля
|field_order                |integer          |-|+|-                                 |Порядок отображения поля в фильтре
|filter_field_type          |varchar(255)     |-|+|-                                 |Тип поля для отображения, например TEXT, DATE, REFERENCE.
|match_mode                 |varchar(255)     |-|+|-                                 |Тип фильтрации по полю, например EQUALS, LIKE, RANGE.
|multiple                   |boolean          |-|-|-                                 |Допускается фильтрация по нескольким значениям поля
|filter_dictionary_id       |bigint           |-|-|fk_filter_field_dictionary_id     |Внешний ключ, ID словаря (заполняется для полей типа REFERENCE)
|filter_template_id         |bigint           |-|+|fk_filter_template_id             |Внешний ключ, ID шаблона
|===

== 3. Примеры использования

Ниже приведен пример контроллера для получения шаблона фильтра:

[source,java]
----
@Slf4j
@RestController
@RequestMapping("/filters")
@RequiredArgsConstructor
public class FilterController {

    private final FilterService filterService;

    /**
     * Gets filter fields.
     *
     * @return filter fields list
     */
    @GetMapping(value = "/fields")
    public List<FilterFieldDto> getFilterFields() {
        return filterService.getFilterFields("filterName");
    }

    /**
     * Gets filter dictionary.
     *
     * @return filter dictionary
     */
    @GetMapping(value = "/dictionary")
    public FilterDictionaryDto getFilterDictionary() {
        return filterService.getFilterDictionary("dictionaryName");
    }
}
----

Ниже приведен пример использования класса AbstractFilter для фильтрации и сортировки данных:

[source,java]
----
@Slf4j
@Service
@RequiredArgsConstructor
public class AppService {

    private final FilterService filterService;
    private final MyEntityRepository myEntityRepository;

    public Page<MyEntity> getNextPage(PageRequestDto pageRequestDto) {
        List<String> globalFilterFields = filterService.getGlobalFilterFields("globalFilterName");
        AbstractFilter filter = new MyFilterImpl(pageRequestDto.getSearchQuery(), globalFilterFields,
                pageRequestDto.getFilters());
        return myEntityRepository.findAll(filter, PageRequest.of(pageRequestDto.getPage(), pageRequestDto.getSize()));
    }
}
----
