= Microservice for classifiers learning
Автор: Roman Batygin
(roman.batygin@mail.ru)
:toc:
:toc-title: Table of contents

== Overview

API provides operations for individual and ensemble classification models learning

== Security schemas


=== EcaAuth

[width=100%]
|===
|*Type*|*Description*|*Flows*
|*oauth2*
|Oauth2 authentication

*Client credentials location:* __header__

*Bearer format:* __Authorization: Bearer <access token>__
a|

*Flow*

__Grant type:__ password

__Token url:__ http://localhost:8080/eca-oauth/oauth/token

__Refresh token url:__ http://localhost:8080/eca-oauth/oauth/token


__Scopes__:


* web

|===

== Updates classifiers configuration

__PUT__ */experiment/classifiers-configurations/update* - Updates classifiers configuration

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<UpdateClassifiersConfigurationDto>>















a|
[source,json]
----
{
  "id" : 1,
  "configurationName" : "Classifiers configuration"
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*-*
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "configurationName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
} ]
----
|===

== Downloads specified base report in xlsx format

__POST__ */reports/download* - Downloads specified base report in xlsx format

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25
}
----
|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*reportType**
|Report type
|query
a|
__string__















*Values*:

* EXPERIMENTS

* EVALUATION_LOGS

* CLASSIFIERS_OPTIONS_REQUESTS
|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*-*
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Finds experiments with specified options

__POST__ */experiment/list* - Finds experiments with specified options

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25,
  "sortField" : "creationDate",
  "ascending" : false,
  "searchQuery" : "",
  "filters" : [ {
    "name" : "evaluationMethod",
    "values" : [ "CROSS_VALIDATION" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "requestStatus",
    "values" : [ "FINISHED" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "experimentType",
    "values" : [ "ADA_BOOST", "NEURAL_NETWORKS", "HETEROGENEOUS_ENSEMBLE", "MODIFIED_HETEROGENEOUS_ENSEMBLE" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "creationDate",
    "values" : [ "2021-07-12" ],
    "matchMode" : "RANGE"
  } ]
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ExperimentsPageDto>>















a|
[source,json]
----
{
  "content" : [ {
    "id" : 1,
    "requestId" : "1d2de514-3a87-4620-9b97-c260e24340de",
    "creationDate" : "2021-07-01 14:00:00",
    "startDate" : "2021-07-01 14:00:30",
    "endDate" : "2021-07-01 14:02:13",
    "requestStatus" : {
      "value" : "FINISHED",
      "description" : "Завершена"
    },
    "evaluationMethod" : {
      "value" : "CROSS_VALIDATION",
      "description" : "V-блочная кросс-проверка"
    },
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1,
    "evaluationTotalTime" : "00:00:1:43",
    "firstName" : "Roman",
    "email" : "test@mail.ru",
    "experimentAbsolutePath" : "experiment_1d2de514-3a87-4620-9b97-c260e24340de.model",
    "trainingDataAbsolutePath" : "data_1d2de514-3a87-4620-9b97-c260e24340de.xls",
    "deletedDate" : "2021-07-14 14:00:00",
    "experimentType" : {
      "value" : "RANDOM_FORESTS",
      "description" : "Случайные леса"
    }
  } ],
  "page" : 0,
  "totalCount" : 1
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Creates experiment request with specified options

__POST__ */experiment/create* - Creates experiment request with specified options

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*multipart/form-data*
|false
|
__object__















a|
-
|===

*Multipart form data fields*

[width=100%]
|===
|*Name*|*Description*|*Schema*
|*trainingData**
|Training data file
a|
__string__
__(binary)__















|===

*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*experimentType**
|Experiment type
|query
a|
__string__















*Values*:

* NEURAL_NETWORKS

* HETEROGENEOUS_ENSEMBLE

* MODIFIED_HETEROGENEOUS_ENSEMBLE

* ADA_BOOST

* STACKING

* KNN

* RANDOM_FORESTS

* STACKING_CV

* DECISION_TREE
|*evaluationMethod**
|Evaluation method
|query
a|
__string__















*Values*:

* TRAINING_DATA

* CROSS_VALIDATION
|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<CreateExperimentResultDto>>















a|
[source,json]
----
{
  "id" : 1,
  "requestId" : "1d2de514-3a87-4620-9b97-c260e24340de"
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Uploads new classifier options file for specified configuration

__POST__ */experiment/classifiers-options/upload* - Uploads new classifier options file for specified configuration

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*multipart/form-data*
|false
|
__object__















a|
-
|===

*Multipart form data fields*

[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classifiersOptionsFile**
|Classifiers options file
a|
__string__
__(binary)__















|===

*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*configurationId**
|Configuration id
|query
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<CreateClassifierOptionsResultDto>>















a|
[source,json]
----
{
  "id" : 1,
  "sourceFileName" : "cart.json",
  "success" : true,
  "errorMessage" : ""
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Finds classifiers options configs page

__POST__ */experiment/classifiers-options/page* - Finds classifiers options configs page

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25
}
----
|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*configurationId**
|Configuration id
|query
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ClassifiersOptionsPageDto>>















a|
[source,json]
----
{
  "content" : [ {
    "id" : 1,
    "optionsName" : "DecisionTreeOptions",
    "optionsDescription" : "Decision tree",
    "creationDate" : "2021-07-01 14:00:00",
    "createdBy" : "admin",
    "config" : "Json config"
  } ],
  "page" : 0,
  "totalCount" : 1
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Adds new classifier options for specified configuration

__POST__ */experiment/classifiers-options/add* - Adds new classifier options for specified configuration

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|


*One of types:*

* <<AdaBoostOptions>>

* <<DecisionTreeOptions>>

* <<ExtraTreesOptions>>

* <<HeterogeneousClassifierOptions>>

* <<J48Options>>

* <<KNearestNeighboursOptions>>

* <<LogisticOptions>>

* <<NeuralNetworkOptions>>

* <<RandomForestsOptions>>

* <<RandomNetworkOptions>>

* <<StackingOptions>>














a|
[source,json]
----
{
  "type" : "decision_tree",
  "decisionTreeType" : "CART",
  "minObj" : 2,
  "maxDepth" : 0,
  "randomTree" : false,
  "useBinarySplits" : true,
  "useRandomSplits" : false
}
----
|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*configurationId**
|Configuration id
|query
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ClassifierOptionsDto>>















a|
[source,json]
----
{
  "id" : 1,
  "optionsName" : "DecisionTreeOptions",
  "optionsDescription" : "Decision tree",
  "creationDate" : "2021-07-01 14:00:00",
  "createdBy" : "admin",
  "config" : "Json config"
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Sets classifiers configuration as active

__POST__ */experiment/classifiers-configurations/set-active* - Sets classifiers configuration as active

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Configuration id
|query
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*-*
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Saves new classifiers configuration

__POST__ */experiment/classifiers-configurations/save* - Saves new classifiers configuration

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<CreateClassifiersConfigurationDto>>















a|
[source,json]
----
{
  "configurationName" : "Classifiers configuration"
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ClassifiersConfigurationDto>>















a|
[source,json]
----
{
  "id" : 1,
  "configurationName" : "Default configuration",
  "creationDate" : "2021-07-01 14:00:00",
  "createdBy" : "admin",
  "updated" : "2021-07-01 14:00:00",
  "active" : true,
  "buildIn" : true,
  "classifiersOptionsCount" : 25
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "configurationName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
} ]
----
|===

== Finds classifiers configurations with specified options

__POST__ */experiment/classifiers-configurations/list* - Finds classifiers configurations with specified options

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ClassifierConfigurationsPageDto>>















a|
[source,json]
----
{
  "content" : [ {
    "id" : 1,
    "configurationName" : "Default configuration",
    "creationDate" : "2021-07-01 14:00:00",
    "createdBy" : "admin",
    "updated" : "2021-07-01 14:00:00",
    "active" : true,
    "buildIn" : true,
    "classifiersOptionsCount" : 25
  } ],
  "page" : 0,
  "totalCount" : 1
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Finds classifiers configuration history with specified options

__POST__ */experiment/classifiers-configurations/history* - Finds classifiers configuration history with specified options

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25
}
----
|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*configurationId**
|Configuration id
|query
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ClassifiersConfigurationHistoryPageDto>>















a|
[source,json]
----
{
  "content" : [ {
    "id" : 44,
    "actionType" : {
      "value" : "SET_ACTIVE",
      "description" : "Конфигурация сделана активной"
    },
    "messageText" : "Конфигурация сделана активной",
    "createdAt" : "2022-07-08 12:26:18",
    "createdBy" : "admin"
  }, {
    "id" : 43,
    "actionType" : {
      "value" : "REMOVE_CLASSIFIER_OPTIONS",
      "description" : "Удалены настройки классификатора"
    },
    "messageText" : "Удалены настройки классификатора [Алгоритм k - взвешенных ближайших соседей]. Идентификатор настроек [39]",
    "createdAt" : "2022-07-08 12:26:16",
    "createdBy" : "admin"
  }, {
    "id" : 42,
    "actionType" : {
      "value" : "ADD_CLASSIFIER_OPTIONS",
      "description" : "Добавлены новые настройки классификатора"
    },
    "messageText" : "Добавлены настройки классификатора [Логистическая регрессия]. Идентификатор настроек [41]",
    "createdAt" : "2022-07-08 12:26:07",
    "createdBy" : "admin"
  }, {
    "id" : 40,
    "actionType" : {
      "value" : "ADD_CLASSIFIER_OPTIONS",
      "description" : "Добавлены новые настройки классификатора"
    },
    "messageText" : "Добавлены настройки классификатора [Алгоритм k - взвешенных ближайших соседей]. Идентификатор настроек [39]",
    "createdAt" : "2022-07-08 12:26:04",
    "createdBy" : "admin"
  }, {
    "id" : 38,
    "actionType" : {
      "value" : "UPDATE_CONFIGURATION",
      "description" : "Данные конфигурации изменены"
    },
    "messageText" : "Изменено название конфигурации. Новое название - Test configuration (renamed)",
    "createdAt" : "2022-07-08 12:25:58",
    "createdBy" : "admin"
  }, {
    "id" : 37,
    "actionType" : {
      "value" : "CREATE_CONFIGURATION",
      "description" : "Создана новая конфигурация"
    },
    "messageText" : "Создана конфигурация с именем Test configuration",
    "createdAt" : "2022-07-08 12:25:48",
    "createdBy" : "admin"
  } ],
  "page" : 0,
  "totalCount" : 6
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Creates classifiers configuration copy

__POST__ */experiment/classifiers-configurations/copy* - Creates classifiers configuration copy

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<UpdateClassifiersConfigurationDto>>















a|
[source,json]
----
{
  "id" : 1,
  "configurationName" : "Classifiers configuration"
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<UpdateClassifiersConfigurationDto>>















a|
[source,json]
----
{
  "id" : 1,
  "configurationName" : "Default configuration",
  "creationDate" : "2021-07-01 14:00:00",
  "createdBy" : "admin",
  "updated" : "2021-07-01 14:00:00",
  "active" : true,
  "buildIn" : true,
  "classifiersOptionsCount" : 25
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "configurationName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
} ]
----
|===

== Finds evaluation logs with specified options

__POST__ */evaluation/list* - Finds evaluation logs with specified options

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25,
  "sortField" : "creationDate",
  "ascending" : false,
  "searchQuery" : "",
  "filters" : [ {
    "name" : "evaluationMethod",
    "values" : [ "CROSS_VALIDATION" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "requestStatus",
    "values" : [ "FINISHED" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "creationDate",
    "values" : [ "2021-07-12" ],
    "matchMode" : "RANGE"
  } ]
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<EvaluationLogsPageDto>>















a|
[source,json]
----
{
  "content" : [ {
    "id" : 1,
    "requestId" : "1d2de514-3a87-4620-9b97-c260e24340de",
    "creationDate" : "2021-07-01 14:00:00",
    "startDate" : "2021-07-01 14:00:01",
    "endDate" : "2021-07-01 14:00:12",
    "requestStatus" : {
      "value" : "FINISHED",
      "description" : "Завершена"
    },
    "evaluationMethod" : {
      "value" : "CROSS_VALIDATION",
      "description" : "V-блочная кросс-проверка"
    },
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1,
    "evaluationTotalTime" : "00:00:00:11",
    "classifierInfo" : {
      "classifierName" : "CART",
      "classifierDescription" : "Алгоритм CART",
      "metaClassifier" : false,
      "inputOptions" : [ {
        "optionName" : "Iterations number",
        "optionValue" : "100"
      } ]
    },
    "instancesInfo" : {
      "relationName" : "iris",
      "numInstances" : 150,
      "numAttributes" : 5,
      "numClasses" : 4,
      "className" : "class"
    }
  } ],
  "page" : 0,
  "totalCount" : 1
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Finds classifiers options requests models with specified options

__POST__ */classifiers-options-requests* - Finds classifiers options requests models with specified options

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25,
  "sortField" : "requestDate",
  "ascending" : false,
  "searchQuery" : "",
  "filters" : [ {
    "name" : "evaluationMethod",
    "values" : [ "CROSS_VALIDATION" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "responseStatus",
    "values" : [ "SUCCESS" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "requestDate",
    "values" : [ "2021-07-16" ],
    "matchMode" : "RANGE"
  } ]
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ClassifierOptionsRequestsPageDto>>















a|
[source,json]
----
{
  "content" : [ {
    "requestDate" : "2021-07-01 14:00:00",
    "requestId" : "1d2de514-3a87-4620-9b97-c260e24340de",
    "relationName" : "glass",
    "evaluationMethod" : {
      "value" : "CROSS_VALIDATION",
      "description" : "V-блочная кросс-проверка"
    },
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1,
    "responseStatus" : {
      "value" : "SUCCESS",
      "description" : "Успешно"
    },
    "classifierOptionsResponseModels" : [ {
      "classifierName" : "CART",
      "options" : "json config"
    } ]
  } ],
  "page" : 0,
  "totalCount" : 1
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Gets experiment filter fields

__GET__ */filter-templates/experiment* - Gets experiment filter fields

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
__array__
<<<FilterFieldDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "requestId",
  "description" : "UUID заявки",
  "fieldOrder" : 0,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false
}, {
  "fieldName" : "email",
  "description" : "Email заявки",
  "fieldOrder" : 1,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false
}, {
  "fieldName" : "evaluationMethod",
  "description" : "Метод оценки точности",
  "fieldOrder" : 2,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : {
    "name" : "evaluationMethod",
    "values" : [ {
      "label" : "Использование обучающего множества",
      "value" : "TRAINING_DATA"
    }, {
      "label" : "V-блочная кросс-проверка",
      "value" : "CROSS_VALIDATION"
    } ]
  }
}, {
  "fieldName" : "requestStatus",
  "description" : "Статус заявки",
  "fieldOrder" : 3,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : {
    "name" : "requestStatus",
    "values" : [ {
      "label" : "Новая",
      "value" : "NEW"
    }, {
      "label" : "Завершена",
      "value" : "FINISHED"
    }, {
      "label" : "Ошибка",
      "value" : "ERROR"
    }, {
      "label" : "Таймаут",
      "value" : "TIMEOUT"
    }, {
      "label" : "В работе",
      "value" : "IN_PROGRESS"
    } ]
  }
}, {
  "fieldName" : "experimentType",
  "description" : "Тип эксперимента",
  "fieldOrder" : 4,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : true,
  "dictionary" : {
    "name" : "experimentType",
    "values" : [ {
      "label" : "Нейронные сети",
      "value" : "NEURAL_NETWORKS"
    }, {
      "label" : "Алгоритм AdaBoost",
      "value" : "ADA_BOOST"
    }, {
      "label" : "Алгоритм Stacking",
      "value" : "STACKING"
    }, {
      "label" : "Случайные леса",
      "value" : "RANDOM_FORESTS"
    }, {
      "label" : "Алгоритм Stacking CV",
      "value" : "STACKING_CV"
    }, {
      "label" : "Деревья решений",
      "value" : "DECISION_TREE"
    }, {
      "label" : "Неоднородный ансамбль",
      "value" : "HETEROGENEOUS_ENSEMBLE"
    }, {
      "label" : "Мод. неоднородный ансамбль",
      "value" : "MODIFIED_HETEROGENEOUS_ENSEMBLE"
    }, {
      "label" : "Алгоритм KNN",
      "value" : "KNN"
    } ]
  }
}, {
  "fieldName" : "creationDate",
  "description" : "Дата создания заявки",
  "fieldOrder" : 5,
  "filterFieldType" : "DATE",
  "matchMode" : "RANGE",
  "multiple" : true
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Gets experiment types filter dictionary

__GET__ */filter-templates/experiment-types* - Gets experiment types filter dictionary

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<FilterDictionaryDto>>















a|
[source,json]
----
{
  "name" : "experimentType",
  "values" : [ {
    "label" : "Нейронные сети",
    "value" : "NEURAL_NETWORKS"
  }, {
    "label" : "Алгоритм AdaBoost",
    "value" : "ADA_BOOST"
  }, {
    "label" : "Алгоритм Stacking",
    "value" : "STACKING"
  }, {
    "label" : "Случайные леса",
    "value" : "RANDOM_FORESTS"
  }, {
    "label" : "Алгоритм Stacking CV",
    "value" : "STACKING_CV"
  }, {
    "label" : "Деревья решений",
    "value" : "DECISION_TREE"
  }, {
    "label" : "Неоднородный ансамбль",
    "value" : "HETEROGENEOUS_ENSEMBLE"
  }, {
    "label" : "Мод. неоднородный ансамбль",
    "value" : "MODIFIED_HETEROGENEOUS_ENSEMBLE"
  }, {
    "label" : "Алгоритм KNN",
    "value" : "KNN"
  } ]
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Gets evaluation log filter fields

__GET__ */filter-templates/evaluation* - Gets evaluation log filter fields

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
__array__
<<<FilterFieldDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "requestId",
  "description" : "UUID заявки",
  "fieldOrder" : 0,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false
}, {
  "fieldName" : "classifierInfo.classifierName",
  "description" : "Классификатор",
  "fieldOrder" : 1,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false
}, {
  "fieldName" : "instancesInfo.relationName",
  "description" : "Обучающая выборка",
  "fieldOrder" : 2,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false
}, {
  "fieldName" : "evaluationMethod",
  "description" : "Метод оценки точности",
  "fieldOrder" : 3,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : {
    "name" : "evaluationMethod",
    "values" : [ {
      "label" : "Использование обучающего множества",
      "value" : "TRAINING_DATA"
    }, {
      "label" : "V-блочная кросс-проверка",
      "value" : "CROSS_VALIDATION"
    } ]
  }
}, {
  "fieldName" : "requestStatus",
  "description" : "Статус заявки",
  "fieldOrder" : 4,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : {
    "name" : "requestStatus",
    "values" : [ {
      "label" : "Новая",
      "value" : "NEW"
    }, {
      "label" : "Завершена",
      "value" : "FINISHED"
    }, {
      "label" : "Ошибка",
      "value" : "ERROR"
    }, {
      "label" : "Таймаут",
      "value" : "TIMEOUT"
    }, {
      "label" : "В работе",
      "value" : "IN_PROGRESS"
    } ]
  }
}, {
  "fieldName" : "creationDate",
  "description" : "Дата создания заявки",
  "fieldOrder" : 5,
  "filterFieldType" : "DATE",
  "matchMode" : "RANGE",
  "multiple" : true
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Gets evaluation method filter dictionary

__GET__ */filter-templates/evaluation-methods* - Gets evaluation method filter dictionary

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<FilterDictionaryDto>>















a|
[source,json]
----
{
  "name" : "evaluationMethod",
  "values" : [ {
    "label" : "Использование обучающего множества",
    "value" : "TRAINING_DATA"
  }, {
    "label" : "V-блочная кросс-проверка",
    "value" : "CROSS_VALIDATION"
  } ]
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Gets classifiers configuration history filter fields

__GET__ */filter-templates/classifiers-configuration-history* - Gets classifiers configuration history filter fields

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
__array__
<<<FilterFieldDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "createdBy",
  "description" : "Пользователь",
  "fieldOrder" : 0,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false
}, {
  "fieldName" : "actionType",
  "description" : "Тип события",
  "fieldOrder" : 1,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : true,
  "dictionary" : {
    "name" : "classifiersConfigurationActionType",
    "values" : [ {
      "label" : "Создана новая конфигурация",
      "value" : "CREATE_CONFIGURATION"
    }, {
      "label" : "Данные конфигурации изменены",
      "value" : "UPDATE_CONFIGURATION"
    }, {
      "label" : "Конфигурация сделана активной",
      "value" : "SET_ACTIVE"
    }, {
      "label" : "Добавлены новые настройки классификатора",
      "value" : "ADD_CLASSIFIER_OPTIONS"
    }, {
      "label" : "Удалены настройки классификатора",
      "value" : "REMOVE_CLASSIFIER_OPTIONS"
    } ]
  }
}, {
  "fieldName" : "createdAt",
  "description" : "Дата события",
  "fieldOrder" : 2,
  "filterFieldType" : "DATE",
  "matchMode" : "RANGE",
  "multiple" : true
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Gets classifier options request filter fields

__GET__ */filter-templates/classifier-options-request* - Gets classifier options request filter fields

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
__array__
<<<FilterFieldDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "requestId",
  "description" : "UUID заявки",
  "fieldOrder" : 0,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false
}, {
  "fieldName" : "relationName",
  "description" : "Обучающая выборка",
  "fieldOrder" : 1,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false
}, {
  "fieldName" : "evaluationMethod",
  "description" : "Метод оценки точности",
  "fieldOrder" : 2,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : {
    "name" : "evaluationMethod",
    "values" : [ {
      "label" : "Использование обучающего множества",
      "value" : "TRAINING_DATA"
    }, {
      "label" : "V-блочная кросс-проверка",
      "value" : "CROSS_VALIDATION"
    } ]
  }
}, {
  "fieldName" : "responseStatus",
  "description" : "Статус ответа от ERS",
  "fieldOrder" : 3,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : {
    "name" : "ersResponseStatus",
    "values" : [ {
      "label" : "Успешно",
      "value" : "SUCCESS"
    }, {
      "label" : "Заявка с таким UUID уже существует",
      "value" : "DUPLICATE_REQUEST_ID"
    }, {
      "label" : "Ошибка",
      "value" : "ERROR"
    }, {
      "label" : "Не найдена обучающая выборка",
      "value" : "DATA_NOT_FOUND"
    }, {
      "label" : "Не найдены оптимальные конфигурации моделей",
      "value" : "RESULTS_NOT_FOUND"
    } ]
  }
}, {
  "fieldName" : "requestDate",
  "description" : "Дата отправки запроса в ERS",
  "fieldOrder" : 4,
  "filterFieldType" : "DATE",
  "matchMode" : "RANGE",
  "multiple" : true
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Downloads experiment training data by specified id

__GET__ */experiment/training-data/{id}* - Downloads experiment training data by specified id

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Experiment id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|**/**
|
__string__
__(binary)__















a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Gets experiment types statistics

__GET__ */experiment/statistics* - Gets experiment types statistics

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*createdDateFrom*
|Experiment created date from
|query
a|
__string__
__(date)__















|*createdDateTo*
|Experiment created date to
|query
a|
__string__
__(date)__















|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
__array__
<<<ChartDataDto>>
>















a|
[source,json]
----
[ {
  "name" : "NEURAL_NETWORKS",
  "label" : "Нейронные сети",
  "count" : 0
}, {
  "name" : "HETEROGENEOUS_ENSEMBLE",
  "label" : "Неоднородный ансамбль",
  "count" : 0
}, {
  "name" : "MODIFIED_HETEROGENEOUS_ENSEMBLE",
  "label" : "Мод. неоднородный ансамбль",
  "count" : 0
}, {
  "name" : "ADA_BOOST",
  "label" : "Алгоритм AdaBoost",
  "count" : 0
}, {
  "name" : "STACKING",
  "label" : "Алгоритм Stacking",
  "count" : 0
}, {
  "name" : "KNN",
  "label" : "Алгоритм KNN",
  "count" : 0
}, {
  "name" : "RANDOM_FORESTS",
  "label" : "Случайные леса",
  "count" : 0
}, {
  "name" : "STACKING_CV",
  "label" : "Алгоритм Stacking CV",
  "count" : 0
}, {
  "name" : "DECISION_TREE",
  "label" : "Деревья решений",
  "count" : 0
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Downloads experiment results by specified id

__GET__ */experiment/results/{id}* - Downloads experiment results by specified id

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Experiment id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|**/**
|
__string__
__(binary)__















a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Finds experiment results details with specified id

__GET__ */experiment/results/details/{id}* - Finds experiment results details with specified id

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Experiment results id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ExperimentResultsDetailsDto>>















a|
[source,json]
----
{
  "id" : 1,
  "classifierInfo" : {
    "classifierName" : "CART",
    "classifierDescription" : "Алгоритм CART",
    "metaClassifier" : false,
    "inputOptions" : [ {
      "optionName" : "Iterations number",
      "optionValue" : "100"
    } ]
  },
  "resultsIndex" : 0,
  "pctCorrect" : 99,
  "sent" : true,
  "experimentDto" : {
    "id" : 1,
    "requestId" : "1d2de514-3a87-4620-9b97-c260e24340de",
    "creationDate" : "2021-07-01 14:00:00",
    "startDate" : "2021-07-01 14:00:30",
    "endDate" : "2021-07-01 14:02:13",
    "requestStatus" : {
      "value" : "FINISHED",
      "description" : "Завершена"
    },
    "evaluationMethod" : {
      "value" : "CROSS_VALIDATION",
      "description" : "V-блочная кросс-проверка"
    },
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1,
    "evaluationTotalTime" : "00:00:1:43",
    "firstName" : "Roman",
    "email" : "test@mail.ru",
    "experimentAbsolutePath" : "experiment_1d2de514-3a87-4620-9b97-c260e24340de.model",
    "trainingDataAbsolutePath" : "data_1d2de514-3a87-4620-9b97-c260e24340de.xls",
    "deletedDate" : "2021-07-14 14:00:00",
    "experimentType" : {
      "value" : "RANDOM_FORESTS",
      "description" : "Случайные леса"
    }
  },
  "evaluationResultsDto" : {
    "evaluationResultsStatus" : {
      "value" : "SUCCESS",
      "description" : "Успешно"
    },
    "evaluationStatisticsDto" : {
      "numTestInstances" : 150,
      "numCorrect" : 146,
      "numIncorrect" : 4,
      "pctCorrect" : 96,
      "pctIncorrect" : 4,
      "meanAbsoluteError" : 0.29,
      "rootMeanSquaredError" : 0.01,
      "maxAucValue" : 0.89,
      "varianceError" : 0.0012,
      "confidenceIntervalLowerBound" : 0.01,
      "confidenceIntervalUpperBound" : 0.035
    },
    "classificationCosts" : [ {
      "classValue" : "Iris-setosa",
      "truePositiveRate" : 0.75,
      "falsePositiveRate" : 0.25,
      "trueNegativeRate" : 0.5,
      "falseNegativeRate" : 0.5,
      "aucValue" : 0.9
    } ]
  }
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Gets experiments request statuses statistics

__GET__ */experiment/request-statuses-statistics* - Gets experiments request statuses statistics

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<RequestStatusStatisticsDto>>















a|
[source,json]
----
{
  "totalCount" : 100,
  "newRequestsCount" : 0,
  "inProgressRequestsCount" : 1,
  "finishedRequestsCount" : 99,
  "timeoutRequestsCount" : 0,
  "errorRequestsCount" : 0
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Finds experiment progress with specified id

__GET__ */experiment/progress/{id}* - Finds experiment progress with specified id

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Experiment id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ExperimentProgressDto>>















a|
[source,json]
----
{
  "finished" : false,
  "progress" : 85,
  "estimatedTimeLeft" : "00:01:24"
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Gets experiment ERS report

__GET__ */experiment/ers-report/{id}* - Gets experiment ERS report

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Experiment id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ExperimentErsReportDto>>















a|
[source,json]
----
{
  "experimentRequestId" : "1d2de514-3a87-4620-9b97-c260e24340de",
  "classifiersCount" : 1,
  "sentClassifiersCount" : 1,
  "experimentResults" : [ {
    "id" : 1,
    "classifierInfo" : {
      "classifierName" : "CART",
      "classifierDescription" : "Алгоритм CART",
      "metaClassifier" : false,
      "inputOptions" : [ {
        "optionName" : "Iterations number",
        "optionValue" : "100"
      } ]
    },
    "resultsIndex" : 0,
    "pctCorrect" : 99,
    "sent" : true
  } ],
  "ersReportStatus" : {
    "value" : "SUCCESS_SENT",
    "description" : "Результаты эксперимента были успешно отправлены в ERS сервис"
  }
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Finds experiment with specified id

__GET__ */experiment/details/{id}* - Finds experiment with specified id

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Experiment id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ExperimentDto>>















a|
[source,json]
----
{
  "id" : 1,
  "requestId" : "1d2de514-3a87-4620-9b97-c260e24340de",
  "creationDate" : "2021-07-01 14:00:00",
  "startDate" : "2021-07-01 14:00:30",
  "endDate" : "2021-07-01 14:02:13",
  "requestStatus" : {
    "value" : "FINISHED",
    "description" : "Завершена"
  },
  "evaluationMethod" : {
    "value" : "CROSS_VALIDATION",
    "description" : "V-блочная кросс-проверка"
  },
  "numFolds" : 10,
  "numTests" : 1,
  "seed" : 1,
  "evaluationTotalTime" : "00:00:1:43",
  "firstName" : "Roman",
  "email" : "test@mail.ru",
  "experimentAbsolutePath" : "experiment_1d2de514-3a87-4620-9b97-c260e24340de.model",
  "trainingDataAbsolutePath" : "data_1d2de514-3a87-4620-9b97-c260e24340de.xls",
  "deletedDate" : "2021-07-14 14:00:00",
  "experimentType" : {
    "value" : "RANDOM_FORESTS",
    "description" : "Случайные леса"
  }
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Downloads classifiers configuration report in xlsx format

__GET__ */experiment/classifiers-configurations/report/{id}* - Downloads classifiers configuration report in xlsx format

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Configuration id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*-*
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Gets classifiers configuration details

__GET__ */experiment/classifiers-configurations/details/{id}* - Gets classifiers configuration details

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Configuration id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ClassifiersConfigurationDto>>















a|
[source,json]
----
{
  "id" : 1,
  "configurationName" : "Default configuration",
  "creationDate" : "2021-07-01 14:00:00",
  "createdBy" : "admin",
  "updated" : "2021-07-01 14:00:00",
  "active" : true,
  "buildIn" : true,
  "classifiersOptionsCount" : 25
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Gets evaluations request statuses statistics

__GET__ */evaluation/request-statuses-statistics* - Gets evaluations request statuses statistics

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<RequestStatusStatisticsDto>>















a|
[source,json]
----
{
  "totalCount" : 100,
  "newRequestsCount" : 0,
  "inProgressRequestsCount" : 1,
  "finishedRequestsCount" : 99,
  "timeoutRequestsCount" : 0,
  "errorRequestsCount" : 0
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Gets evaluation log details

__GET__ */evaluation/details/{id}* - Gets evaluation log details

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Evaluation log id
|path
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<EvaluationLogDetailsDto>>















a|
[source,json]
----
{
  "id" : 1,
  "requestId" : "1d2de514-3a87-4620-9b97-c260e24340de",
  "creationDate" : "2021-07-01 14:00:00",
  "startDate" : "2021-07-01 14:00:01",
  "endDate" : "2021-07-01 14:00:12",
  "requestStatus" : {
    "value" : "FINISHED",
    "description" : "Завершена"
  },
  "evaluationMethod" : {
    "value" : "CROSS_VALIDATION",
    "description" : "V-блочная кросс-проверка"
  },
  "numFolds" : 10,
  "numTests" : 1,
  "seed" : 1,
  "evaluationTotalTime" : "00:00:00:11",
  "classifierInfo" : {
    "classifierName" : "CART",
    "classifierDescription" : "Алгоритм CART",
    "metaClassifier" : false,
    "inputOptions" : [ {
      "optionName" : "Iterations number",
      "optionValue" : "100"
    } ]
  },
  "instancesInfo" : {
    "relationName" : "iris",
    "numInstances" : 150,
    "numAttributes" : 5,
    "numClasses" : 4,
    "className" : "class"
  },
  "evaluationResultsDto" : {
    "evaluationResultsStatus" : {
      "value" : "RESULTS_RECEIVED",
      "description" : "Получены результаты классификации"
    },
    "evaluationStatisticsDto" : {
      "numTestInstances" : 150,
      "numCorrect" : 146,
      "numIncorrect" : 4,
      "pctCorrect" : 96,
      "pctIncorrect" : 4,
      "meanAbsoluteError" : 0.29,
      "rootMeanSquaredError" : 0.01,
      "maxAucValue" : 0.89,
      "varianceError" : 0.0012,
      "confidenceIntervalLowerBound" : 0.01,
      "confidenceIntervalUpperBound" : 0.035
    },
    "classificationCosts" : [ {
      "classValue" : "Iris-setosa",
      "truePositiveRate" : 0.75,
      "falsePositiveRate" : 0.25,
      "trueNegativeRate" : 0.5,
      "falseNegativeRate" : 0.5,
      "aucValue" : 0.9
    } ]
  }
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Downloads experiment results by token

__GET__ */eca-api/experiment/download/{token}* - Downloads experiment results by token



*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*token**
|Experiment token
|path
a|
__string__


*Min. length*: 1

*Max. length*: 255










|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|**/**
|
__string__
__(binary)__















a|
-
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Gets classifiers form templates

__GET__ */classifiers/templates/list* - Gets classifiers form templates

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
__array__
<<<FormTemplateDto>>
>















a|
[source,json]
----
[ {
  "templateName" : "KNN",
  "templateTitle" : "Алгоритм k - взвешенных ближайших соседей",
  "objectClass" : "KNearestNeighboursOptions",
  "objectType" : "knn",
  "fields" : [ {
    "fieldName" : "numNeighbours",
    "description" : "Число ближайших соседей",
    "fieldOrder" : 0,
    "fieldType" : "INTEGER",
    "minValue" : 1.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "10",
    "readOnly" : false
  }, {
    "fieldName" : "weight",
    "description" : "Вес ближайшего соседа",
    "fieldOrder" : 1,
    "fieldType" : "DECIMAL",
    "minValue" : 0.5,
    "minInclusive" : true,
    "maxValue" : 1.0,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "1",
    "readOnly" : false
  }, {
    "fieldName" : "distanceType",
    "description" : "Функция расстояния",
    "fieldOrder" : 2,
    "fieldType" : "REFERENCE",
    "minInclusive" : true,
    "maxInclusive" : true,
    "dictionary" : {
      "name" : "distanceType",
      "values" : [ {
        "label" : "Евкилидово расстояние",
        "value" : "EUCLID"
      }, {
        "label" : "Квадрат Евклидова расстояни",
        "value" : "SQUARE_EUCLID"
      }, {
        "label" : "Манхеттенское расстояние",
        "value" : "MANHATTAN"
      }, {
        "label" : "Расстояние Чебышева",
        "value" : "CHEBYSHEV"
      } ]
    },
    "defaultValue" : "EUCLID",
    "readOnly" : false
  } ]
}, {
  "templateName" : "LOGISTIC",
  "templateTitle" : "Логистическая регрессия",
  "objectClass" : "LogisticOptions",
  "objectType" : "logistic",
  "fields" : [ {
    "fieldName" : "maxIts",
    "description" : "Максимальное число итераций",
    "fieldOrder" : 0,
    "fieldType" : "INTEGER",
    "minValue" : 1.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "200",
    "readOnly" : false
  }, {
    "fieldName" : "useConjugateGradientDescent",
    "description" : "Использовать метод сопряженных градиентов",
    "fieldOrder" : 1,
    "fieldType" : "BOOLEAN",
    "minInclusive" : true,
    "maxInclusive" : true,
    "defaultValue" : "false",
    "readOnly" : false
  } ]
}, {
  "templateName" : "J48",
  "templateTitle" : "Алгоритм J48",
  "objectClass" : "J48Options",
  "objectType" : "j48",
  "fields" : [ {
    "fieldName" : "minNumObj",
    "description" : "Минимальное число объектов в листе",
    "fieldOrder" : 0,
    "fieldType" : "INTEGER",
    "minValue" : 0.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "2",
    "readOnly" : false
  }, {
    "fieldName" : "binarySplits",
    "description" : "Бинарное дерево",
    "fieldOrder" : 1,
    "fieldType" : "BOOLEAN",
    "minInclusive" : true,
    "maxInclusive" : true,
    "defaultValue" : "false",
    "readOnly" : false
  }, {
    "fieldName" : "unpruned",
    "description" : "Неусеченное дерево",
    "fieldOrder" : 2,
    "fieldType" : "BOOLEAN",
    "minInclusive" : true,
    "maxInclusive" : true,
    "defaultValue" : "false",
    "readOnly" : false
  }, {
    "fieldName" : "numFolds",
    "description" : "Количество блоков",
    "fieldOrder" : 3,
    "fieldType" : "INTEGER",
    "minValue" : 2.0,
    "minInclusive" : true,
    "maxValue" : 100.0,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "3",
    "readOnly" : false
  } ]
}, {
  "templateName" : "DECISION_TREE",
  "templateTitle" : "Дерево решений",
  "objectClass" : "DecisionTreeOptions",
  "objectType" : "decision_tree",
  "fields" : [ {
    "fieldName" : "decisionTreeType",
    "description" : "Алгоритм построения дерева",
    "fieldOrder" : 0,
    "fieldType" : "REFERENCE",
    "minInclusive" : true,
    "maxInclusive" : true,
    "dictionary" : {
      "name" : "decisionTreeType",
      "values" : [ {
        "label" : "Алгоритм CART",
        "value" : "CART"
      }, {
        "label" : "Алгоритм ID3",
        "value" : "ID3"
      }, {
        "label" : "Алгоритм C4.5",
        "value" : "C45"
      }, {
        "label" : "Алгоритм CHAID",
        "value" : "CHAID"
      } ]
    },
    "defaultValue" : "CART",
    "readOnly" : false
  }, {
    "fieldName" : "minObj",
    "description" : "Минимальное число объектов в листе",
    "fieldOrder" : 1,
    "fieldType" : "INTEGER",
    "minValue" : 0.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "2",
    "readOnly" : false
  }, {
    "fieldName" : "maxDepth",
    "description" : "Максимальная глубина дерева",
    "fieldOrder" : 2,
    "fieldType" : "INTEGER",
    "minValue" : 0.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "0",
    "readOnly" : false
  }, {
    "fieldName" : "useBinarySplits",
    "description" : "Бинарное дерево",
    "fieldOrder" : 3,
    "fieldType" : "BOOLEAN",
    "minInclusive" : true,
    "maxInclusive" : true,
    "defaultValue" : "false",
    "readOnly" : false
  }, {
    "fieldName" : "randomTree",
    "description" : "Случайное дерево",
    "fieldOrder" : 4,
    "fieldType" : "BOOLEAN",
    "minInclusive" : true,
    "maxInclusive" : true,
    "defaultValue" : "false",
    "readOnly" : false
  }, {
    "fieldName" : "numRandomAttr",
    "description" : "Число случайных атрибутов",
    "fieldOrder" : 5,
    "fieldType" : "INTEGER",
    "minValue" : 0.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "0",
    "readOnly" : false
  }, {
    "fieldName" : "useRandomSplits",
    "description" : "Случайные расщепления атрибута",
    "fieldOrder" : 6,
    "fieldType" : "BOOLEAN",
    "minInclusive" : true,
    "maxInclusive" : true,
    "defaultValue" : "false",
    "readOnly" : false
  }, {
    "fieldName" : "numRandomSplits",
    "description" : "Число случайных расщеплений атрибута",
    "fieldOrder" : 7,
    "fieldType" : "INTEGER",
    "minValue" : 1.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "1",
    "readOnly" : false
  }, {
    "fieldName" : "seed",
    "description" : "Начальное значение (seed)",
    "fieldOrder" : 8,
    "fieldType" : "INTEGER",
    "minValue" : 0.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "1",
    "readOnly" : false
  } ]
}, {
  "templateName" : "NEURAL_NETWORK",
  "templateTitle" : "Нейронная сеть (Многослойный персептрон)",
  "objectClass" : "NeuralNetworkOptions",
  "objectType" : "neural_network",
  "fields" : [ {
    "fieldName" : "numInNeurons",
    "description" : "Количество нейронов во входном слое",
    "fieldOrder" : 0,
    "fieldType" : "INTEGER",
    "minValue" : 1.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "readOnly" : true
  }, {
    "fieldName" : "numOutNeurons",
    "description" : "Количество нейронов в выходном слое",
    "fieldOrder" : 1,
    "fieldType" : "INTEGER",
    "minValue" : 2.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "readOnly" : true
  }, {
    "fieldName" : "hiddenLayer",
    "description" : "Структура скрытого слоя",
    "fieldOrder" : 2,
    "fieldType" : "TEXT",
    "minInclusive" : true,
    "maxInclusive" : true,
    "maxLength" : 255,
    "pattern" : "^([1-9],?)+$",
    "invalidPatternMessage" : "Неправильный формат скрытого слоя. Пример 8,15,10",
    "placeHolder" : "Введите числа, разделенные запятой",
    "readOnly" : false
  }, {
    "fieldName" : "numIterations",
    "description" : "Число итераций",
    "fieldOrder" : 3,
    "fieldType" : "INTEGER",
    "minValue" : 1.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "1000000",
    "readOnly" : false
  }, {
    "fieldName" : "minError",
    "description" : "Допустимая ошибка",
    "fieldOrder" : 4,
    "fieldType" : "DECIMAL",
    "minValue" : 0.0,
    "minInclusive" : true,
    "maxValue" : 1.0,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "0.00001",
    "readOnly" : false
  }, {
    "fieldName" : "activationFunctionOptions.activationFunctionType",
    "description" : "Активационная функция нейронов скрытого слоя",
    "fieldOrder" : 5,
    "fieldType" : "REFERENCE",
    "minInclusive" : true,
    "maxInclusive" : true,
    "dictionary" : {
      "name" : "activationFunctionType",
      "values" : [ {
        "label" : "Логистическая",
        "value" : "LOGISTIC"
      }, {
        "label" : "Гиперболический тангенс",
        "value" : "HYPERBOLIC_TANGENT"
      }, {
        "label" : "Тригонометрический синус",
        "value" : "SINUSOID"
      }, {
        "label" : "Экспоненциальная",
        "value" : "EXPONENTIAL"
      }, {
        "label" : "Функция SoftSign",
        "value" : "SOFT_SIGN"
      }, {
        "label" : "Функция ISRU",
        "value" : "INVERSE_SQUARE_ROOT_UNIT"
      } ]
    },
    "defaultValue" : "LOGISTIC",
    "readOnly" : false
  }, {
    "fieldName" : "activationFunctionOptions.coefficient",
    "description" : "Значение коэффициента",
    "fieldOrder" : 6,
    "fieldType" : "DECIMAL",
    "minValue" : 0.0,
    "minInclusive" : false,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "1",
    "readOnly" : false
  }, {
    "fieldName" : "backPropagationOptions.learningRate",
    "description" : "Коэффициент скорости обучения",
    "fieldOrder" : 7,
    "fieldType" : "DECIMAL",
    "minValue" : 0.0,
    "minInclusive" : false,
    "maxValue" : 1.0,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "0.1",
    "readOnly" : false
  }, {
    "fieldName" : "backPropagationOptions.momentum",
    "description" : "Коэффициент момента",
    "fieldOrder" : 8,
    "fieldType" : "DECIMAL",
    "minValue" : 0.0,
    "minInclusive" : true,
    "maxValue" : 1.0,
    "maxInclusive" : false,
    "maxLength" : 255,
    "defaultValue" : "0.2",
    "readOnly" : false
  }, {
    "fieldName" : "seed",
    "description" : "Начальное значение (seed)",
    "fieldOrder" : 9,
    "fieldType" : "INTEGER",
    "minValue" : 0.0,
    "minInclusive" : true,
    "maxValue" : 2.147483647E9,
    "maxInclusive" : true,
    "maxLength" : 255,
    "defaultValue" : "1",
    "readOnly" : false
  } ]
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Classifier options id

__DELETE__ */experiment/classifiers-options/delete* - Classifier options id

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Classifier options id
|query
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*-*
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Deletes classifiers configuration

__DELETE__ */experiment/classifiers-configurations/delete* - Deletes classifiers configuration

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===


*Request parameters*
[width=100%]
|===
|*Name*|*Description*|*Location*|*Schema*
|*id**
|Configuration id
|query
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|===

*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*-*
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===


== Components
=== ValidationErrorDto
:table-caption: Table
.Validation error model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*fieldName*
|Field name
a|
__string__




*Max. length*: 255










|*code*
|Error code
a|
__string__




*Max. length*: 255










|*errorMessage*
|Error message
a|
__string__




*Max. length*: 1,000










|===
=== UpdateClassifiersConfigurationDto
:table-caption: Table
.Update classifiers configuration model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id**
|Configuration id
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*configurationName**
|Configuration name
a|
__string__


*Min. length*: 1

*Max. length*: 64










|===
=== FilterRequestDto
:table-caption: Table
.Filter request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*name**
|Filter column name
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*values*
|-
a|
__array__
<string
>








*Min. items*: 0

*Max. items*: 50




|*matchMode**
|Match mode type
a|
__string__


*Min. length*: 1

*Max. length*: 255










*Values*:

* EQUALS

* LIKE

* RANGE
|===
=== PageRequestDto
:table-caption: Table
.Page request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*page**
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*size**
|Page size
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 100*








|*sortField*
|Sort field
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*ascending*
|Is ascending sort?
a|
__boolean__















|*searchQuery*
|Search query string
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*filters*
|Filters list
a|
__array__
<<<FilterRequestDto>>
>








*Min. items*: 0

*Max. items*: 50




|===
=== EnumDto
:table-caption: Table
.Enum dto model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*value**
|Enum value
a|
__string__




*Max. length*: 255










|*description**
|Enum value description
a|
__string__




*Max. length*: 255










|===
=== ExperimentDto
:table-caption: Table
.Experiment model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|ID
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*requestId*
|Request unique identifier
a|
__string__




*Max. length*: 36










|*creationDate*
|Request creation date
a|
__string__




*Max. length*: 19










|*startDate*
|Evaluation start date
a|
__string__




*Max. length*: 19










|*endDate*
|Evaluation end date
a|
__string__




*Max. length*: 19










|*requestStatus*
|-
a|
<<EnumDto>>















|*evaluationMethod*
|-
a|
<<EnumDto>>















|*numFolds*
|Folds number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 10*








|*numTests*
|Tests number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*evaluationTotalTime*
|Model evaluation total time in format HH:mm:ss:SS
a|
__string__




*Max. length*: 11










|*firstName*
|Request creator first name
a|
__string__




*Max. length*: 255










|*email*
|Request creator email
a|
__string__




*Max. length*: 255










|*experimentAbsolutePath*
|Experiment results file
a|
__string__




*Max. length*: 255










|*trainingDataAbsolutePath*
|Training data file
a|
__string__




*Max. length*: 255










|*deletedDate*
|Experiment files delete date
a|
__string__




*Max. length*: 19










|*experimentType*
|-
a|
<<EnumDto>>















|===
=== ExperimentsPageDto
:table-caption: Table
.Experiments page dto
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*content*
|-
a|
__array__
<<<ExperimentDto>>
>










*Max. items*: 100




|*page*
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*totalCount*
|Total elements count in all pages
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== CreateExperimentResultDto
:table-caption: Table
.Create experiment result model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id**
|Experiment id
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*requestId**
|Request id
a|
__string__




*Max. length*: 36










|===
=== CreateClassifierOptionsResultDto
:table-caption: Table
.Create classifier options model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id**
|Classifier options id
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*sourceFileName**
|Source file name
a|
__string__




*Max. length*: 255










|*success**
|Classifier options saved boolean flag
a|
__boolean__















|*errorMessage*
|Error message
a|
__string__




*Max. length*: 255










|===
=== ClassifierOptionsDto
:table-caption: Table
.Classifier json input options model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|Options id
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*optionsName**
|Options name
a|
__string__




*Max. length*: 255










|*optionsDescription**
|Options description
a|
__string__




*Max. length*: 255










|*creationDate**
|Creation date
a|
__string__




*Max. length*: 19










|*createdBy*
|User name
a|
__string__




*Max. length*: 255










|*config**
|Json config
a|
__string__















|*inputOptions*
|-
a|
__array__
<<<InputOptionDto>>
>















|===
=== ClassifiersOptionsPageDto
:table-caption: Table
.Classifiers options page dto
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*content*
|-
a|
__array__
<<<ClassifierOptionsDto>>
>










*Max. items*: 100




|*page*
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*totalCount*
|Total elements count in all pages
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== InputOptionDto
:table-caption: Table
.Classifier input option model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*optionName*
|Input option name
a|
__string__




*Max. length*: 255










|*optionValue*
|Input option value
a|
__string__




*Max. length*: 255










|===
=== ActivationFunctionOptions
:table-caption: Table
.Activation function options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*activationFunctionType*
|Activation function type
a|
__string__




*Max. length*: 255










*Values*:

* LOGISTIC

* HYPERBOLIC_TANGENT

* SINUSOID

* EXPONENTIAL

* SOFT_SIGN

* INVERSE_SQUARE_ROOT_UNIT
|*coefficient*
|Activation function coefficient value
a|
__number__
__(double)__






*Minimum*: 0

*Maximum*: 2,147,483,647*








|===
=== AdaBoostOptions
:table-caption: Table
.AdaBoost classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*numIterations*
|Iterations number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*numThreads*
|Threads number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for random generator
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*minError*
|Classifier min. error threshold
a|
__number__
__(double)__






*Minimum*: 0*

*Maximum*: 0.5*








|*maxError*
|Classifier max. error threshold
a|
__number__
__(double)__






*Minimum*: 0*

*Maximum*: 0.5*








|*classifierOptions**
|-
a|
__array__
<<<ClassifierOptions>>
>








*Min. items*: 1

*Max. items*: 25




|===
=== BackPropagationOptions
:table-caption: Table
.Back propagation learning algorithm options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*learningRate*
|Learning rate value
a|
__number__
__(double)__






*Minimum*: 0

*Maximum*: 1*








|*momentum*
|Momentum coefficient value
a|
__number__
__(double)__






*Minimum*: 0*

*Maximum*: 1








|===
=== ClassifierOptions
:table-caption: Table
.Component ClassifierOptions
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|===
=== DecisionTreeOptions
:table-caption: Table
.Decision tree classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*decisionTreeType*
|Decision tree algorithm
a|
__string__




*Max. length*: 255










*Values*:

* CART

* ID3

* C45

* CHAID
|*minObj*
|Minimum objects number per leaf
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*maxDepth*
|Maximum tree depth
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*randomTree*
|Random tree flag
a|
__boolean__















|*numRandomAttr*
|Random attributes number at each split for random tree
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*useBinarySplits*
|Binary tree flag
a|
__boolean__















|*useRandomSplits*
|Use random splits flag
a|
__boolean__















|*numRandomSplits*
|Random splits number at each node split
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*seed*
|Seed value for random generator
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*alpha*
|Alpha value for chi square test
a|
__number__
__(double)__






*Minimum*: 0

*Maximum*: 1








|*additionalOptions*
|Additional options map
a|
__object__















|===
=== ExtraTreesOptions
:table-caption: Table
.Extra trees classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*numIterations*
|Iterations number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*numThreads*
|Threads number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for random generator
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*numRandomAttr*
|Random attributes number at each node split
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*minObj*
|Min. objects per leaf
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*maxDepth*
|Maximum tree depth
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*decisionTreeType*
|Decision tree algorithm
a|
__string__




*Max. length*: 255










*Values*:

* CART

* ID3

* C45

* CHAID
|*numRandomSplits*
|Number of random splits
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*useBootstrapSamples*
|Use bootstrap samples flag
a|
__boolean__















|===
=== HeterogeneousClassifierOptions
:table-caption: Table
.Heterogeneous classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*numIterations*
|Iterations number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*numThreads*
|Threads number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for random generator
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*minError*
|Classifier min. error threshold
a|
__number__
__(double)__






*Minimum*: 0*

*Maximum*: 0.5*








|*maxError*
|Classifier max. error threshold
a|
__number__
__(double)__






*Minimum*: 0*

*Maximum*: 0.5*








|*classifierOptions**
|-
a|
__array__
<<<ClassifierOptions>>
>








*Min. items*: 1

*Max. items*: 25




|*useWeightedVotes*
|Use weighted votes method
a|
__boolean__















|*useRandomClassifier*
|Use random classifier at each iteration
a|
__boolean__















|*samplingMethod*
|Sampling method at each iteration
a|
__string__




*Max. length*: 255










*Values*:

* INITIAL

* BAGGING

* RANDOM

* RANDOM_BAGGING
|*useRandomSubspaces*
|Use random subspaces
a|
__boolean__















|===
=== J48Options
:table-caption: Table
.J48 algorithm classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*minNumObj*
|Minimum objects number per leaf
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*binarySplits*
|Binary tree flag
a|
__boolean__















|*unpruned*
|Unpruned tree flag
a|
__boolean__















|*numFolds*
|Folds number for tree pruning procedure
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 100*








|===
=== KNearestNeighboursOptions
:table-caption: Table
.K - nearest neighbours classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*numNeighbours*
|Neighbours number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*weight*
|Neighbour's weight value
a|
__number__
__(double)__






*Minimum*: 0.5*

*Maximum*: 1*








|*distanceType*
|Distance function type
a|
__string__




*Max. length*: 255










*Values*:

* EUCLID

* SQUARE_EUCLID

* MANHATTAN

* CHEBYSHEV
|===
=== LogisticOptions
:table-caption: Table
.Logistic regression classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*maxIts*
|Maximum iterations number for optimization method
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*useConjugateGradientDescent*
|Use conjugate gradient descent method
a|
__boolean__















|===
=== NeuralNetworkOptions
:table-caption: Table
.Neural network classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*numInNeurons*
|Neurons number in input layer
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*numOutNeurons*
|Neurons number in output layer
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 2,147,483,647*








|*hiddenLayer*
|Hidden layer structure
a|
__string__


*Min. length*: 0

*Max. length*: 255







*Pattern*: `^([0-9],?)+$`


|*seed*
|Seed value for random generator
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*numIterations*
|Max. its for learning
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*minError*
|Min. error for optimization algorithm
a|
__number__
__(double)__






*Minimum*: 0*

*Maximum*: 1*








|*activationFunctionOptions*
|-
a|
<<ActivationFunctionOptions>>















|*backPropagationOptions*
|-
a|
<<BackPropagationOptions>>















|===
=== RandomForestsOptions
:table-caption: Table
.Random forests classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*numIterations*
|Iterations number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*numThreads*
|Threads number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for random generator
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*numRandomAttr*
|Random attributes number at each node split
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*minObj*
|Min. objects per leaf
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*maxDepth*
|Maximum tree depth
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*decisionTreeType*
|Decision tree algorithm
a|
__string__




*Max. length*: 255










*Values*:

* CART

* ID3

* C45

* CHAID
|===
=== RandomNetworkOptions
:table-caption: Table
.Random networks classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*numIterations*
|Iterations number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 2,147,483,647*








|*numThreads*
|Threads number
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for random generator
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*minError*
|Classifier min. error threshold
a|
__number__
__(double)__






*Minimum*: 0*

*Maximum*: 0.5*








|*maxError*
|Classifier max. error threshold
a|
__number__
__(double)__






*Minimum*: 0*

*Maximum*: 0.5*








|*useBootstrapSamples*
|Use bootstrap samples
a|
__boolean__















|===
=== StackingOptions
:table-caption: Table
.Stacking classifier options
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*type**
|-
a|
__string__















|*useCrossValidation*
|Use cross - validation method for meta data building
a|
__boolean__















|*numFolds*
|Folds number for V - cross validation method
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 100*








|*seed*
|Seed value for random generator
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*classifierOptions**
|-
a|
__array__
<<<ClassifierOptions>>
>








*Min. items*: 1

*Max. items*: 25




|*metaClassifierOptions**
|-
a|
<<ClassifierOptions>>















|===
=== ClassifiersConfigurationDto
:table-caption: Table
.Classifiers configuration dto model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|Configuration id
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*configurationName*
|Configuration name
a|
__string__




*Max. length*: 255










|*creationDate*
|Configuration creation date
a|
__string__




*Max. length*: 19










|*createdBy*
|User name
a|
__string__




*Max. length*: 255










|*updated*
|Configuration updated date
a|
__string__




*Max. length*: 19










|*active*
|Is active?
a|
__boolean__















|*buildIn*
|Is build in?
a|
__boolean__















|*classifiersOptionsCount*
|Classifiers options count associated with configuration
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== CreateClassifiersConfigurationDto
:table-caption: Table
.Create classifiers configuration model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*configurationName**
|Configuration name
a|
__string__


*Min. length*: 1

*Max. length*: 64










|===
=== ClassifierConfigurationsPageDto
:table-caption: Table
.Classifier configurations page dto
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*content*
|-
a|
__array__
<<<ClassifiersConfigurationDto>>
>










*Max. items*: 100




|*page*
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*totalCount*
|Total elements count in all pages
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== ClassifiersConfigurationHistoryDto
:table-caption: Table
.Classifiers configuration history model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id**
|ID
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*actionType**
|-
a|
<<EnumDto>>















|*messageText**
|Message text
a|
__string__















|*createdAt**
|Creation date
a|
__string__




*Max. length*: 19










|*createdBy**
|User name
a|
__string__




*Max. length*: 255










|===
=== ClassifiersConfigurationHistoryPageDto
:table-caption: Table
.Classifiers configuration history page dto
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*content*
|-
a|
__array__
<<<ClassifiersConfigurationHistoryDto>>
>










*Max. items*: 100




|*page*
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*totalCount*
|Total elements count in all pages
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== ClassifierInfoDto
:table-caption: Table
.Classifier info model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classifierName*
|Classifier name
a|
__string__




*Max. length*: 255










|*classifierDescription*
|Classifier description
a|
__string__




*Max. length*: 255










|*classifierOptionsJson**
|Classifier options json config
a|
__string__















|*metaClassifier*
|Is meta classifier (used for stacking algorithms)
a|
__boolean__















|*inputOptions*
|-
a|
__array__
<<<InputOptionDto>>
>















|*individualClassifiers*
|-
a|
__array__
<<<ClassifierInfoDto>>
>















|===
=== EvaluationLogDto
:table-caption: Table
.Classifier evaluation log model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|ID
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*requestId*
|Request unique identifier
a|
__string__




*Max. length*: 36










|*creationDate*
|Request creation date
a|
__string__




*Max. length*: 19










|*startDate*
|Evaluation start date
a|
__string__




*Max. length*: 19










|*endDate*
|Evaluation end date
a|
__string__




*Max. length*: 19










|*requestStatus*
|-
a|
<<EnumDto>>















|*evaluationMethod*
|-
a|
<<EnumDto>>















|*numFolds*
|Folds number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 10*








|*numTests*
|Tests number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*evaluationTotalTime*
|Model evaluation total time in format HH:mm:ss:SS
a|
__string__




*Max. length*: 11










|*classifierInfo*
|-
a|
<<ClassifierInfoDto>>















|*instancesInfo*
|-
a|
<<InstancesInfoDto>>















|===
=== EvaluationLogsPageDto
:table-caption: Table
.Evaluation logs page dto
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*content*
|-
a|
__array__
<<<EvaluationLogDto>>
>










*Max. items*: 100




|*page*
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*totalCount*
|Total elements count in all pages
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== InstancesInfoDto
:table-caption: Table
.Classifier training data model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*relationName*
|Instances name
a|
__string__




*Max. length*: 255










|*numInstances*
|Instances number
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 2,147,483,647*








|*numAttributes*
|Attributes number
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 2,147,483,647*








|*numClasses*
|Classes number
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 2,147,483,647*








|*className*
|Class name
a|
__string__




*Max. length*: 255










|===
=== ClassifierOptionsRequestDto
:table-caption: Table
.ERS classifier options request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestDate*
|ERS request date
a|
__string__




*Max. length*: 19










|*requestId*
|Request id
a|
__string__




*Max. length*: 36










|*relationName*
|Training data name
a|
__string__




*Max. length*: 255










|*evaluationMethod*
|-
a|
<<EnumDto>>















|*numFolds*
|Folds number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 10*








|*numTests*
|Tests number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*responseStatus*
|-
a|
<<EnumDto>>















|*classifierOptionsResponseModels*
|-
a|
__array__
<<<ClassifierOptionsResponseDto>>
>










*Max. items*: 5




|===
=== ClassifierOptionsRequestsPageDto
:table-caption: Table
.Classifier options requests page dto
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*content*
|-
a|
__array__
<<<ClassifierOptionsRequestDto>>
>










*Max. items*: 100




|*page*
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*totalCount*
|Total elements count in all pages
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== ClassifierOptionsResponseDto
:table-caption: Table
.ERS classifier options response model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classifierName*
|Classifier name
a|
__string__




*Max. length*: 255










|*options*
|Classifier input options json config
a|
__string__















|===
=== FilterDictionaryDto
:table-caption: Table
.Filter dictionary model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*name*
|Filter dictionary name
a|
__string__




*Max. length*: 255










|*values*
|Filter dictionary values
a|
__array__
<<<FilterDictionaryValueDto>>
>















|===
=== FilterDictionaryValueDto
:table-caption: Table
.Filter dictionary value model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*label*
|Filter dictionary field label
a|
__string__




*Max. length*: 255










|*value*
|Filter dictionary field value
a|
__string__




*Max. length*: 255










|===
=== FilterFieldDto
:table-caption: Table
.Filter field model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*fieldName*
|Field name
a|
__string__




*Max. length*: 255










|*description*
|Field description
a|
__string__




*Max. length*: 255










|*fieldOrder*
|Field order
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*filterFieldType*
|Filter field type
a|
__string__




*Max. length*: 255










*Values*:

* TEXT

* REFERENCE

* DATE
|*matchMode*
|Filter match mode
a|
__string__




*Max. length*: 255










*Values*:

* EQUALS

* LIKE

* RANGE
|*multiple*
|Allow multiple values
a|
__boolean__















|*dictionary*
|-
a|
<<FilterDictionaryDto>>















|===
=== ChartDataDto
:table-caption: Table
.Model for chart
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*name**
|Chart item name
a|
__string__




*Max. length*: 255










|*label**
|Chart item label
a|
__string__




*Max. length*: 255










|*count**
|Chart item value
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== ClassificationCostsDto
:table-caption: Table
.Classification costs model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classValue*
|Class value
a|
__string__




*Max. length*: 255










|*truePositiveRate*
|TP rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*falsePositiveRate*
|FP rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*trueNegativeRate*
|TN rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*falseNegativeRate*
|FN rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*aucValue*
|AUC value
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|===
=== EvaluationResultsDto
:table-caption: Table
.Classifier evaluation results model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*evaluationResultsStatus*
|-
a|
<<EnumDto>>















|*evaluationStatisticsDto*
|-
a|
<<EvaluationStatisticsDto>>















|*classificationCosts*
|Classification costs results
a|
__array__
<<<ClassificationCostsDto>>
>















|===
=== EvaluationStatisticsDto
:table-caption: Table
.Classifier evaluation statistics model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*numTestInstances*
|Test instances number
a|
__integer__






*Minimum*: 2*

*Maximum*: 2,147,483,647*








|*numCorrect*
|Correctly classified instances number
a|
__integer__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*numIncorrect*
|Incorrectly classified instances number
a|
__integer__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*pctCorrect*
|Correctly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*pctIncorrect*
|Incorrectly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*meanAbsoluteError*
|Mean absolute error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*rootMeanSquaredError*
|Root mean squared error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*maxAucValue*
|Max AUC value
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*varianceError*
|Variance error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*confidenceIntervalLowerBound*
|95% confidence interval lower bound value
a|
__number__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*confidenceIntervalUpperBound*
|95% confidence interval upper bound value
a|
__number__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|===
=== ExperimentResultsDetailsDto
:table-caption: Table
.Experiment results details model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|Experiment results id
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*classifierInfo*
|-
a|
<<ClassifierInfoDto>>















|*resultsIndex*
|Results index
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*pctCorrect*
|Correctly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*sent*
|Is experiment results sent to ERS?
a|
__boolean__















|*experimentDto*
|-
a|
<<ExperimentDto>>















|*evaluationResultsDto*
|-
a|
<<EvaluationResultsDto>>















|===
=== RequestStatusStatisticsDto
:table-caption: Table
.Requests statuses statistics model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*totalCount*
|Total requests count
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|*newRequestsCount*
|Total requests count with status NEW
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|*inProgressRequestsCount*
|Total requests count with status IN_PROGRESS
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|*finishedRequestsCount*
|Total requests count with status FINISHED
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|*timeoutRequestsCount*
|Total requests count with status TIMEOUT
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|*errorRequestsCount*
|Total requests count with status ERROR
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|===
=== ExperimentProgressDto
:table-caption: Table
.Experiment progress model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*finished*
|Is experiment processing finished?
a|
__boolean__















|*progress*
|Experiment progress bar value
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 100*








|*estimatedTimeLeft*
|Estimated time left
a|
__string__




*Max. length*: 8










|===
=== ExperimentErsReportDto
:table-caption: Table
.Experiment ERS report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*experimentRequestId*
|Experiment request id
a|
__string__




*Max. length*: 36










|*classifiersCount*
|Total classifiers count
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|*sentClassifiersCount*
|Successfully sent classifiers count
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9,223,372,036,854,775,807*








|*experimentResults*
|-
a|
__array__
<<<ExperimentResultsDto>>
>










*Max. items*: 5




|*ersReportStatus*
|-
a|
<<EnumDto>>















|===
=== ExperimentResultsDto
:table-caption: Table
.Experiment results model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|Experiment results id
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*classifierInfo*
|-
a|
<<ClassifierInfoDto>>















|*resultsIndex*
|Results index
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*pctCorrect*
|Correctly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*sent*
|Is experiment results sent to ERS?
a|
__boolean__















|===
=== EvaluationLogDetailsDto
:table-caption: Table
.Classifier evaluation log details model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|ID
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9,223,372,036,854,775,807*








|*requestId*
|Request unique identifier
a|
__string__




*Max. length*: 36










|*creationDate*
|Request creation date
a|
__string__




*Max. length*: 19










|*startDate*
|Evaluation start date
a|
__string__




*Max. length*: 19










|*endDate*
|Evaluation end date
a|
__string__




*Max. length*: 19










|*requestStatus*
|-
a|
<<EnumDto>>















|*evaluationMethod*
|-
a|
<<EnumDto>>















|*numFolds*
|Folds number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 10*








|*numTests*
|Tests number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: -2,147,483,648*

*Maximum*: 2,147,483,647*








|*evaluationTotalTime*
|Model evaluation total time in format HH:mm:ss:SS
a|
__string__




*Max. length*: 11










|*classifierInfo*
|-
a|
<<ClassifierInfoDto>>















|*instancesInfo*
|-
a|
<<InstancesInfoDto>>















|*evaluationResultsDto*
|-
a|
<<EvaluationResultsDto>>















|===
=== FieldDictionaryDto
:table-caption: Table
.Field dictionary model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*name*
|Field dictionary name
a|
__string__




*Max. length*: 255










|*values*
|-
a|
__array__
<<<FieldDictionaryValueDto>>
>















|===
=== FieldDictionaryValueDto
:table-caption: Table
.Field dictionary value model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*label*
|Field dictionary field label
a|
__string__




*Max. length*: 255










|*value*
|Field dictionary field value
a|
__string__




*Max. length*: 255










|===
=== FormFieldDto
:table-caption: Table
.Form field model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*fieldName*
|Field name
a|
__string__




*Max. length*: 255










|*description*
|Field description
a|
__string__




*Max. length*: 255










|*fieldOrder*
|Field order
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*fieldType*
|Form field type
a|
__string__




*Max. length*: 255










*Values*:

* TEXT

* REFERENCE

* INTEGER

* DECIMAL

* BOOLEAN
|*minValue*
|Minimum value
a|
__number__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*minInclusive*
|Min. value inclusive?
a|
__boolean__















|*maxValue*
|Maximum value
a|
__number__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*maxInclusive*
|Max. value inclusive?
a|
__boolean__















|*maxLength*
|Maximum value length
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2,147,483,647*








|*pattern*
|Pattern value
a|
__string__




*Max. length*: 255










|*invalidPatternMessage*
|Invalid pattern message
a|
__string__




*Max. length*: 255










|*dictionary*
|-
a|
<<FieldDictionaryDto>>















|*placeHolder*
|Place holder message
a|
__string__




*Max. length*: 255










|*defaultValue*
|Default value
a|
__string__




*Max. length*: 255










|*readOnly*
|Read only?
a|
__boolean__















|===
=== FormTemplateDto
:table-caption: Table
.Form template model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*templateName*
|Template name
a|
__string__




*Max. length*: 255










|*templateTitle*
|Template title
a|
__string__




*Max. length*: 255










|*objectClass*
|Object class
a|
__string__




*Max. length*: 255










|*objectType*
|Object type
a|
__string__




*Max. length*: 255










|*fields*
|-
a|
__array__
<<<FormFieldDto>>
>















|===
