= Microservice for storaging and analysis evaluation results
Автор: Roman Batygin
(roman.batygin@mail.ru)
:toc:
:toc-title: Table of contents

== Overview

API provides operations with evaluation results

== Security schemas


=== EcaAuth

[width=100%]
|===
|*Type*|*Description*|*Flows*
|*oauth2*
|Oauth2 authentication


a|

*Flow*

__Grant type:__ password

__Token url:__ http://localhost:8080/eca-oauth/oauth/token

__Refresh token url:__ http://localhost:8080/eca-oauth/oauth/token


__Scopes__:


* web

|===

== Finds instances info page with specified options such as filter, sorting and paging

__POST__ */evaluation-results/instances/list* - Finds instances info page with specified options such as filter, sorting and paging

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25,
  "sortField" : "createdDate",
  "ascending" : false,
  "searchQuery" : "glass",
  "filters" : [ ]
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<InstancesInfoPageDto>>















a|
[source,json]
----
{
  "content" : [ {
    "id" : 1,
    "relation" : "glass",
    "numInstances" : 214,
    "numAttributes" : 10,
    "numClasses" : 6,
    "className" : "class",
    "createdDate" : "2021-07-01 14:00:00"
  } ],
  "page" : 0,
  "totalCount" : 1
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Finds evaluation results history page with specified options such as filter, sorting and paging

__POST__ */evaluation-results/history* - Finds evaluation results history page with specified options such as filter, sorting and paging

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===

*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<PageRequestDto>>















a|
[source,json]
----
{
  "page" : 0,
  "size" : 25
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<EvaluationResultsHistoryPageDto>>















a|
[source,json]
----
{
  "content" : [ {
    "id" : 2643,
    "classifierInfo" : {
      "classifierName" : "DecisionTreeOptions",
      "classifierDescription" : "Алгоритм CART",
      "classifierOptionsJson" : "{\"type\":\"decision_tree\",\"decisionTreeType\":\"CART\",\"minObj\":2,\"maxDepth\":0,\"randomTree\":false,\"numRandomAttr\":0,\"useBinarySplits\":true,\"useRandomSplits\":false,\"numRandomSplits\":1,\"seed\":1,\"alpha\":null}",
      "metaClassifier" : false,
      "inputOptions" : [ {
        "optionName" : "Алгоритм построения дерева",
        "optionValue" : "Алгоритм CART"
      }, {
        "optionName" : "Минимальное число объектов в листе",
        "optionValue" : "2"
      }, {
        "optionName" : "Максимальная глубина дерева",
        "optionValue" : "0"
      }, {
        "optionName" : "Бинарное дерево",
        "optionValue" : "true"
      }, {
        "optionName" : "Случайное дерево",
        "optionValue" : "false"
      }, {
        "optionName" : "Число случайных атрибутов",
        "optionValue" : "0"
      }, {
        "optionName" : "Случайные расщепления атрибута",
        "optionValue" : "false"
      }, {
        "optionName" : "Число случайных расщеплений атрибута",
        "optionValue" : "1"
      }, {
        "optionName" : "Начальное значение (seed)",
        "optionValue" : "1"
      } ],
      "individualClassifiers" : null
    },
    "instancesInfo" : {
      "id" : 1,
      "relationName" : "glass",
      "numInstances" : 214,
      "numAttributes" : 10,
      "numClasses" : 6,
      "className" : "type",
      "createdDate" : "2023-11-16 18:57:14"
    },
    "evaluationMethod" : {
      "value" : "CROSS_VALIDATION",
      "description" : "V-блочная кросс-проверка"
    },
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1,
    "saveDate" : "2023-12-07 14:49:26",
    "numTestInstances" : 214,
    "numCorrect" : 154,
    "numIncorrect" : 60,
    "pctCorrect" : 71.9626,
    "pctIncorrect" : 28.0374,
    "meanAbsoluteError" : 0.109,
    "rootMeanSquaredError" : 0.2884,
    "maxAucValue" : 0.8824,
    "varianceError" : 0.0066,
    "confidenceIntervalLowerBound" : 0.2224,
    "confidenceIntervalUpperBound" : 0.3384
  } ],
  "page" : 0,
  "totalCount" : 79
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Saves evaluation results report

__POST__ */api/save* - Saves evaluation results report


*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<EvaluationResultsRequest>>















a|
[source,json]
----
{
  "requestId" : "04b1373f-7838-4535-b65a-88c088830879",
  "instances" : {
    "dataMd5Hash" : "3032e188204cb537f69fc7364f638641",
    "relationName" : "Glass",
    "numInstances" : 214,
    "numAttributes" : 10,
    "numClasses" : 6,
    "className" : "Type"
  },
  "classifierReport" : {
    "classifierName" : "ExtraTreesClassifier",
    "classifierDescription" : null,
    "options" : "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
  },
  "evaluationMethodReport" : {
    "evaluationMethod" : "CROSS_VALIDATION",
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1
  },
  "statistics" : {
    "numTestInstances" : 214,
    "numCorrect" : 172,
    "numIncorrect" : 42,
    "pctCorrect" : 80.37383177570094,
    "pctIncorrect" : 19.626168224299064,
    "meanAbsoluteError" : 0.11885129227585131,
    "rootMeanSquaredError" : 0.231476151125149,
    "maxAucValue" : 0.9983739837398374,
    "varianceError" : 0.00436052266530287,
    "confidenceIntervalLowerBound" : 0.14902362368597982,
    "confidenceIntervalUpperBound" : 0.24349974080000147
  },
  "classificationCosts" : [ {
    "classValue" : "build wind float",
    "truePositiveRate" : 0.9142857142857143,
    "falsePositiveRate" : 0.125,
    "trueNegativeRate" : 0.875,
    "falseNegativeRate" : 0.08571428571428572,
    "rocCurve" : {
      "aucValue" : 0.9313988095238095,
      "specificity" : 0.8611111111111112,
      "sensitivity" : 0.9428571428571428,
      "thresholdValue" : 0.4138291855203621
    }
  }, {
    "classValue" : "vehic wind float",
    "truePositiveRate" : 0.23529411764705882,
    "falsePositiveRate" : 0.01015228426395939,
    "trueNegativeRate" : 0.9898477157360406,
    "falseNegativeRate" : 0.7647058823529411,
    "rocCurve" : {
      "aucValue" : 0.9252015527022992,
      "specificity" : 0.751269035532995,
      "sensitivity" : 1,
      "thresholdValue" : 0.08396763793615986
    }
  }, {
    "classValue" : "tableware",
    "truePositiveRate" : 0.7777777777777778,
    "falsePositiveRate" : 0.004878048780487805,
    "trueNegativeRate" : 0.9951219512195122,
    "falseNegativeRate" : 0.2222222222222222,
    "rocCurve" : {
      "aucValue" : 0.9983739837398374,
      "specificity" : 0.9951219512195122,
      "sensitivity" : 1,
      "thresholdValue" : 0.33422619047619045
    }
  }, {
    "classValue" : "build wind non-float",
    "truePositiveRate" : 0.8289473684210527,
    "falsePositiveRate" : 0.10869565217391304,
    "trueNegativeRate" : 0.8913043478260869,
    "falseNegativeRate" : 0.17105263157894737,
    "rocCurve" : {
      "aucValue" : 0.9111365369946606,
      "specificity" : 0.9492753623188406,
      "sensitivity" : 0.75,
      "thresholdValue" : 0.49067460317460315
    }
  }, {
    "classValue" : "headlamps",
    "truePositiveRate" : 0.8275862068965517,
    "falsePositiveRate" : 0.016216216216216217,
    "trueNegativeRate" : 0.9837837837837838,
    "falseNegativeRate" : 0.1724137931034483,
    "rocCurve" : {
      "aucValue" : 0.9606710158434296,
      "specificity" : 0.9459459459459459,
      "sensitivity" : 0.9655172413793104,
      "thresholdValue" : 0.1461273690078038
    }
  }, {
    "classValue" : "containers",
    "truePositiveRate" : 0.7692307692307693,
    "falsePositiveRate" : 0.014925373134328358,
    "trueNegativeRate" : 0.9850746268656716,
    "falseNegativeRate" : 0.23076923076923078,
    "rocCurve" : {
      "aucValue" : 0.9862227324913893,
      "specificity" : 0.9701492537313433,
      "sensitivity" : 0.9230769230769231,
      "thresholdValue" : 0.2746176338281601
    }
  } ],
  "confusionMatrix" : [ {
    "actualClass" : "build wind float",
    "predictedClass" : "build wind float",
    "numInstances" : 64
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 5
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "headlamps",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "build wind float",
    "numInstances" : 9
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 4
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 4
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "headlamps",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "build wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "tableware",
    "numInstances" : 7
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "build wind non-float",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "build wind float",
    "numInstances" : 8
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "tableware",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 63
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "containers",
    "numInstances" : 2
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "build wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "build wind non-float",
    "numInstances" : 3
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "headlamps",
    "numInstances" : 24
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "containers",
    "numInstances" : 1
  }, {
    "actualClass" : "containers",
    "predictedClass" : "build wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "containers",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "containers",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "containers",
    "predictedClass" : "build wind non-float",
    "numInstances" : 2
  }, {
    "actualClass" : "containers",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "containers",
    "predictedClass" : "containers",
    "numInstances" : 10
  } ]
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<EvaluationResultsResponse>>















a|
[source,json]
----
{
  "requestId" : "04b1373f-7838-4535-b65a-88c088830879"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "requestId",
  "code" : "Pattern",
  "errorMessage" : "must match \"^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$\""
}, {
  "fieldName" : "instances.structure",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
}, {
  "fieldName" : "requestId",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
}, {
  "fieldName" : "instances.relationName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
}, {
  "fieldName" : "classifierReport.classifierName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
} ]
----
|===

== Gets evaluation results simple report

__POST__ */api/results* - Gets evaluation results simple report


*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<GetEvaluationResultsRequest>>















a|
[source,json]
----
{
  "requestId" : "04b1373f-7838-4535-b65a-88c088830879"
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<GetEvaluationResultsResponse>>















a|
[source,json]
----
{
  "requestId" : "04b1373f-7838-4535-b65a-88c088830879",
  "instances" : {
    "dataMd5Hash" : "3032e188204cb537f69fc7364f638641",
    "relationName" : "Glass",
    "numInstances" : 214,
    "numAttributes" : 10,
    "numClasses" : 6,
    "className" : "Type"
  },
  "classifierReport" : {
    "classifierName" : "ExtraTreesClassifier",
    "classifierDescription" : null,
    "options" : "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
  },
  "evaluationMethodReport" : {
    "evaluationMethod" : "CROSS_VALIDATION",
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1
  },
  "statistics" : {
    "numTestInstances" : 214,
    "numCorrect" : 172,
    "numIncorrect" : 42,
    "pctCorrect" : 80.3738,
    "pctIncorrect" : 19.6262,
    "meanAbsoluteError" : 0.1189,
    "rootMeanSquaredError" : 0.2315,
    "maxAucValue" : 0.9984,
    "varianceError" : 0.0044,
    "confidenceIntervalLowerBound" : 0.149,
    "confidenceIntervalUpperBound" : 0.2435
  },
  "classificationCosts" : [ {
    "classValue" : "build wind float",
    "truePositiveRate" : 0.9143,
    "falsePositiveRate" : 0.125,
    "trueNegativeRate" : 0.875,
    "falseNegativeRate" : 0.0857,
    "rocCurve" : {
      "aucValue" : 0.9314,
      "specificity" : 0.8611,
      "sensitivity" : 0.9429,
      "thresholdValue" : 0.4138
    }
  }, {
    "classValue" : "build wind non-float",
    "truePositiveRate" : 0.8289,
    "falsePositiveRate" : 0.1087,
    "trueNegativeRate" : 0.8913,
    "falseNegativeRate" : 0.1711,
    "rocCurve" : {
      "aucValue" : 0.9111,
      "specificity" : 0.9493,
      "sensitivity" : 0.75,
      "thresholdValue" : 0.4907
    }
  }, {
    "classValue" : "containers",
    "truePositiveRate" : 0.7692,
    "falsePositiveRate" : 0.0149,
    "trueNegativeRate" : 0.9851,
    "falseNegativeRate" : 0.2308,
    "rocCurve" : {
      "aucValue" : 0.9862,
      "specificity" : 0.9701,
      "sensitivity" : 0.9231,
      "thresholdValue" : 0.2746
    }
  }, {
    "classValue" : "headlamps",
    "truePositiveRate" : 0.8276,
    "falsePositiveRate" : 0.0162,
    "trueNegativeRate" : 0.9838,
    "falseNegativeRate" : 0.1724,
    "rocCurve" : {
      "aucValue" : 0.9607,
      "specificity" : 0.9459,
      "sensitivity" : 0.9655,
      "thresholdValue" : 0.1461
    }
  }, {
    "classValue" : "tableware",
    "truePositiveRate" : 0.7778,
    "falsePositiveRate" : 0.0049,
    "trueNegativeRate" : 0.9951,
    "falseNegativeRate" : 0.2222,
    "rocCurve" : {
      "aucValue" : 0.9984,
      "specificity" : 0.9951,
      "sensitivity" : 1,
      "thresholdValue" : 0.3342
    }
  }, {
    "classValue" : "vehic wind float",
    "truePositiveRate" : 0.2353,
    "falsePositiveRate" : 0.0102,
    "trueNegativeRate" : 0.9898,
    "falseNegativeRate" : 0.7647,
    "rocCurve" : {
      "aucValue" : 0.9252,
      "specificity" : 0.7513,
      "sensitivity" : 1,
      "thresholdValue" : 0.084
    }
  } ],
  "confusionMatrix" : [ {
    "actualClass" : "tableware",
    "predictedClass" : "build wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "build wind float",
    "numInstances" : 8
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 4
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 5
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 63
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "containers",
    "numInstances" : 2
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "headlamps",
    "numInstances" : 0
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "build wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "containers",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "build wind non-float",
    "numInstances" : 3
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "containers",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "build wind non-float",
    "numInstances" : 1
  }, {
    "actualClass" : "containers",
    "predictedClass" : "build wind non-float",
    "numInstances" : 2
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "headlamps",
    "numInstances" : 24
  }, {
    "actualClass" : "containers",
    "predictedClass" : "build wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "headlamps",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "build wind float",
    "numInstances" : 64
  }, {
    "actualClass" : "containers",
    "predictedClass" : "containers",
    "numInstances" : 10
  }, {
    "actualClass" : "containers",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "tableware",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 4
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "build wind float",
    "numInstances" : 9
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "containers",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "tableware",
    "numInstances" : 7
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  } ]
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "requestId",
  "code" : "Pattern",
  "errorMessage" : "must match \"^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$\""
} ]
----
|===

== Endpoint for searching optimal classifiers options for specified request

__POST__ */api/optimal-classifier-options* - Endpoint for searching optimal classifiers options for specified request


*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|
<<ClassifierOptionsRequest>>















a|
[source,json]
----
{
  "requestId" : "f8cecbf7-405b-403b-9a94-f51e8fb73ed8",
  "dataHash" : "2aeb5c41423c895995e8cb304fe30b2d",
  "evaluationMethodReport" : {
    "evaluationMethod" : "CROSS_VALIDATION",
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1
  },
  "sortFields" : null
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|
<<ClassifierOptionsResponse>>















a|
[source,json]
----
{
  "requestId" : "f8cecbf7-405b-403b-9a94-f51e8fb73ed8",
  "classifierReports" : [ {
    "classifierName" : "ExtraTreesClassifier",
    "classifierDescription" : null,
    "options" : "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
  }, {
    "classifierName" : "ExtraTreesClassifier",
    "classifierDescription" : null,
    "options" : "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
  } ]
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : "evaluationMethodReport.evaluationMethod",
  "code" : "NotNull",
  "errorMessage" : "must not be null"
}, {
  "fieldName" : "dataHash",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
}, {
  "fieldName" : "relationName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
} ]
----
|===

== Gets evaluation results history filter fields

__GET__ */evaluation-results/filter-templates/fields* - Gets evaluation results history filter fields

*Security requirement*

[cols="^50%,^50%",options="header"]
|===
|*Name*|*Scopes*
|
<<EcaAuth>>
a|

* web

|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : "classifierInfo.classifierName",
  "description" : "Классификатор",
  "fieldOrder" : 0,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : true,
  "dictionary" : {
    "name" : "classifier",
    "values" : [ {
      "label" : "Алгоритм CART",
      "value" : "CART"
    }, {
      "label" : "Алгоритм C4.5",
      "value" : "C45"
    }, {
      "label" : "Алгоритм ID3",
      "value" : "ID3"
    }, {
      "label" : "Алгоритм CHAID",
      "value" : "CHAID"
    }, {
      "label" : "Алгоритм J48",
      "value" : "J48"
    }, {
      "label" : "Нейронная сеть (Многослойный персептрон)",
      "value" : "NeuralNetwork"
    }, {
      "label" : "Алгоритм k - взвешенных ближайших соседей",
      "value" : "KNearestNeighbours"
    }, {
      "label" : "Логистическая регрессия",
      "value" : "Logistic"
    }, {
      "label" : "Алгоритм AdaBoost",
      "value" : "AdaBoostClassifier"
    }, {
      "label" : "Неоднородный ансамблевый алгоритм",
      "value" : "HeterogeneousClassifier"
    }, {
      "label" : "Модифицированный неоднородный ансамблевый алгоритм",
      "value" : "ModifiedHeterogeneousClassifier"
    }, {
      "label" : "Алгоритм Stacking",
      "value" : "StackingClassifier"
    }, {
      "label" : "Алгоритм Случайные леса",
      "value" : "RandomForests"
    }, {
      "label" : "Алгоритм Extra trees",
      "value" : "ExtraTreesClassifier"
    }, {
      "label" : "Алгоритм Случайные сети",
      "value" : "RandomNetworks"
    } ]
  }
}, {
  "fieldName" : "instancesInfo.id",
  "description" : "Обучающая выборка",
  "fieldOrder" : 1,
  "filterFieldType" : "LAZY_REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : null
}, {
  "fieldName" : "evaluationMethod",
  "description" : "Метод оценки точности",
  "fieldOrder" : 2,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : {
    "name" : "evaluationMethod",
    "values" : [ {
      "label" : "Использование обучающего множества",
      "value" : "TRAINING_DATA"
    }, {
      "label" : "V-блочная кросс-проверка",
      "value" : "CROSS_VALIDATION"
    } ]
  }
}, {
  "fieldName" : "saveDate",
  "description" : "Дата сохранения результатов",
  "fieldOrder" : 3,
  "filterFieldType" : "DATE",
  "matchMode" : "RANGE",
  "multiple" : true,
  "dictionary" : null
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|
__array__
<<<ValidationErrorDto>>
>















a|
[source,json]
----
[ {
  "fieldName" : null,
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===


== Components
=== InstancesInfoDto
:table-caption: Table
.Classifier training data model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|ID
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9 223 372 036 854 775 807*








|*relationName*
|Instances name
a|
__string__




*Max. length*: 255










|*numInstances*
|Instances number
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*numAttributes*
|Attributes number
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*numClasses*
|Classes number
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*className*
|Class name
a|
__string__




*Max. length*: 255










|*createdDate*
|Created date
a|
__string__




*Max. length*: 19










|===
=== InstancesInfoPageDto
:table-caption: Table
.Instances info page dto
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*content*
|-
a|
__array__
<<<InstancesInfoDto>>
>










*Max. items*: 100




|*page*
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2 147 483 647*








|*totalCount*
|Total elements count in all pages
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9 223 372 036 854 775 807*








|===
=== ValidationErrorDto
:table-caption: Table
.Validation error model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*fieldName*
|Field name
a|
__string__




*Max. length*: 255










|*code*
|Error code
a|
__string__




*Max. length*: 255










|*errorMessage*
|Error message
a|
__string__




*Max. length*: 1 000










|===
=== FilterRequestDto
:table-caption: Table
.Filter request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*name**
|Filter column name
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*values*
|-
a|
__array__
<string
>








*Min. items*: 0

*Max. items*: 50




|*matchMode**
|Match mode type
a|
__string__


*Min. length*: 1

*Max. length*: 255










*Values*:

* EQUALS

* LIKE

* RANGE
|===
=== PageRequestDto
:table-caption: Table
.Page request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*page**
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2 147 483 647*








|*size**
|Page size
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 100*








|*sortField*
|Sort field
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*ascending*
|Is ascending sort?
a|
__boolean__















|*searchQuery*
|Search query string
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*filters*
|Filters list
a|
__array__
<<<FilterRequestDto>>
>








*Min. items*: 0

*Max. items*: 50




|===
=== ClassifierInfoDto
:table-caption: Table
.Classifier info model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classifierName*
|Classifier name
a|
__string__




*Max. length*: 255










|*classifierDescription*
|Classifier description
a|
__string__




*Max. length*: 255










|*classifierOptionsJson**
|Classifier options json config
a|
__string__















|*metaClassifier*
|Is meta classifier (used for stacking algorithms)
a|
__boolean__















|*inputOptions*
|-
a|
__array__
<<<InputOptionDto>>
>















|*individualClassifiers*
|-
a|
__array__
<<<ClassifierInfoDto>>
>















|===
=== EnumDto
:table-caption: Table
.Enum dto model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*value**
|Enum value
a|
__string__




*Max. length*: 255










|*description**
|Enum value description
a|
__string__




*Max. length*: 255










|===
=== EvaluationResultsHistoryDto
:table-caption: Table
.Classifier evaluation results history model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*id*
|ID
a|
__integer__
__(int64)__






*Minimum*: 1*

*Maximum*: 9 223 372 036 854 775 807*








|*classifierInfo*
|-
a|
<<ClassifierInfoDto>>















|*instancesInfo*
|-
a|
<<InstancesInfoDto>>















|*evaluationMethod*
|-
a|
<<EnumDto>>















|*numFolds*
|Folds number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 2*

*Maximum*: 10*








|*numTests*
|Tests number for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: 1*

*Maximum*: 10*








|*seed*
|Seed value for k * V cross - validation method
a|
__integer__
__(int32)__






*Minimum*: -2 147 483 648*

*Maximum*: 2 147 483 647*








|*saveDate*
|Save date
a|
__string__




*Max. length*: 19










|*numTestInstances*
|Test instances number
a|
__integer__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*numCorrect*
|Correctly classified instances number
a|
__integer__






*Minimum*: 0*

*Maximum*: 2 147 483 647*








|*numIncorrect*
|Incorrectly classified instances number
a|
__integer__






*Minimum*: 0*

*Maximum*: 2 147 483 647*








|*pctCorrect*
|Correctly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*pctIncorrect*
|Incorrectly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*meanAbsoluteError*
|Mean absolute error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*rootMeanSquaredError*
|Root mean squared error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*maxAucValue*
|Max AUC value
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*varianceError*
|Variance error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*confidenceIntervalLowerBound*
|95% confidence interval lower bound value
a|
__number__






*Minimum*: -2 147 483 648*

*Maximum*: 2 147 483 647*








|*confidenceIntervalUpperBound*
|95% confidence interval upper bound value
a|
__number__






*Minimum*: -2 147 483 648*

*Maximum*: 2 147 483 647*








|===
=== EvaluationResultsHistoryPageDto
:table-caption: Table
.Classifier evaluation results history page dto
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*content*
|-
a|
__array__
<<<EvaluationResultsHistoryDto>>
>










*Max. items*: 100




|*page*
|Page number
a|
__integer__
__(int32)__






*Minimum*: 0*

*Maximum*: 2 147 483 647*








|*totalCount*
|Total elements count in all pages
a|
__integer__
__(int64)__






*Minimum*: 0*

*Maximum*: 9 223 372 036 854 775 807*








|===
=== InputOptionDto
:table-caption: Table
.Classifier input option model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*optionName*
|Input option name
a|
__string__




*Max. length*: 255










|*optionValue*
|Input option value
a|
__string__




*Max. length*: 255










|===
=== EvaluationResultsResponse
:table-caption: Table
.Evaluation results response model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId*
|Request id
a|
__string__




*Max. length*: 36










|===
=== ClassificationCostsReport
:table-caption: Table
.Classification costs report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classValue**
|Class value
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*truePositiveRate**
|True positive rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*falsePositiveRate**
|False positive rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*trueNegativeRate**
|True negative rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*falseNegativeRate**
|False negative rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*rocCurve*
|-
a|
<<RocCurveReport>>















|===
=== ClassifierReport
:table-caption: Table
.Classifier report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classifierName**
|Classifier name
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*classifierDescription*
|Classifier description
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*options**
|Classifier options string
a|
__string__


*Min. length*: 1

*Max. length*: 2 147 483 647










|===
=== ConfusionMatrixReport
:table-caption: Table
.Confusion matrix report
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*actualClass**
|Actual class
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*predictedClass**
|Predicted class
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*numInstances**
|Instances number
a|
__integer__






*Minimum*: 0*

*Maximum*: 2 147 483 647*








|===
=== EvaluationMethodReport
:table-caption: Table
.Evaluation method report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*evaluationMethod**
|Evaluation method
a|
__string__




*Max. length*: 255










*Values*:

* TRAINING_DATA

* CROSS_VALIDATION
|*numFolds*
|Folds number for k * V cross - validation method
a|
__integer__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*numTests*
|Tests number for k * V cross - validation method
a|
__integer__






*Minimum*: 1*

*Maximum*: 2 147 483 647*








|*seed*
|Seed value for k * V cross - validation method
a|
__integer__






*Minimum*: -9 223 372 036 854 775 808*

*Maximum*: 9 223 372 036 854 775 807*








|===
=== EvaluationResultsRequest
:table-caption: Table
.Evaluation results request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId**
|Request id
a|
__string__


*Min. length*: 1

*Max. length*: 36







*Pattern*: `^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`


|*instances**
|-
a|
<<InstancesReport>>















|*classifierReport**
|-
a|
<<ClassifierReport>>















|*evaluationMethodReport**
|-
a|
<<EvaluationMethodReport>>















|*statistics**
|-
a|
<<StatisticsReport>>















|*classificationCosts*
|Classification costs report
a|
__array__
<<<ClassificationCostsReport>>
>















|*confusionMatrix*
|Confusion matrix report
a|
__array__
<<<ConfusionMatrixReport>>
>















|===
=== InstancesReport
:table-caption: Table
.Training data report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*dataMd5Hash**
|Instances MD5 hash sum
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*relationName**
|Relation name
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*numInstances**
|Instances number
a|
__integer__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*numAttributes**
|Attributes number
a|
__integer__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*numClasses**
|Classes number
a|
__integer__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*className**
|Class name
a|
__string__


*Min. length*: 1

*Max. length*: 255










|===
=== RocCurveReport
:table-caption: Table
.Roc curve report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*aucValue*
|Auc value
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*specificity*
|Specificity value at optimal ROC - curve point
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*sensitivity*
|Sensitivity value at optimal ROC - curve point
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*thresholdValue*
|Threshold value at optimal ROC - curve point
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|===
=== StatisticsReport
:table-caption: Table
.Evaluation statistics report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*numTestInstances**
|Test instances number
a|
__integer__






*Minimum*: 2*

*Maximum*: 2 147 483 647*








|*numCorrect**
|Correctly classified instances number
a|
__integer__






*Minimum*: 0*

*Maximum*: 2 147 483 647*








|*numIncorrect**
|Incorrectly classified instances number
a|
__integer__






*Minimum*: 0*

*Maximum*: 2 147 483 647*








|*pctCorrect**
|Correctly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*pctIncorrect**
|Incorrectly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*meanAbsoluteError*
|Mean absolute error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*rootMeanSquaredError*
|Root mean squared error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*maxAucValue*
|Max AUC value
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*varianceError*
|Variance error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*confidenceIntervalLowerBound*
|95% confidence interval lower bound value
a|
__number__






*Minimum*: -2 147 483 648*

*Maximum*: 2 147 483 647*








|*confidenceIntervalUpperBound*
|95% confidence interval upper bound value
a|
__number__






*Minimum*: -2 147 483 648*

*Maximum*: 2 147 483 647*








|===
=== GetEvaluationResultsResponse
:table-caption: Table
.Get evaluation results response model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId*
|Request id
a|
__string__




*Max. length*: 36










|*instances*
|-
a|
<<InstancesReport>>















|*classifierReport*
|-
a|
<<ClassifierReport>>















|*evaluationMethodReport*
|-
a|
<<EvaluationMethodReport>>















|*statistics*
|-
a|
<<StatisticsReport>>















|*classificationCosts*
|Classification costs report
a|
__array__
<<<ClassificationCostsReport>>
>















|*confusionMatrix*
|Confusion matrix report
a|
__array__
<<<ConfusionMatrixReport>>
>















|===
=== GetEvaluationResultsRequest
:table-caption: Table
.Get evaluation results request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId**
|Request id
a|
__string__


*Min. length*: 1

*Max. length*: 36







*Pattern*: `^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`


|===
=== ClassifierOptionsResponse
:table-caption: Table
.Classifier options response model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId*
|Request id
a|
__string__




*Max. length*: 36










|*classifierReports*
|-
a|
__array__
<<<ClassifierReport>>
>










*Max. items*: 5




|===
=== ClassifierOptionsRequest
:table-caption: Table
.Classifier options request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId**
|Request id
a|
__string__


*Min. length*: 1

*Max. length*: 36







*Pattern*: `^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`


|*dataHash**
|Instances MD5 hash sum
a|
__string__


*Min. length*: 1

*Max. length*: 255










|*evaluationMethodReport**
|-
a|
<<EvaluationMethodReport>>















|*evaluationResultsStatisticsSortFields*
|-
a|
__array__
<<<EvaluationResultsStatisticsSortField>>
>








*Min. items*: 0

*Max. items*: 3




|===
=== EvaluationResultsStatisticsSortField
:table-caption: Table
.Evaluation results statistics sort field model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*field**
|Sort field name
a|
__string__















*Values*:

* PCT_CORRECT

* MAX_AUC_VALUE

* VARIANCE_ERROR
|*direction**
|Sort direction
a|
__string__




*Max. length*: 255










*Values*:

* ASC

* DESC
|===
