= Microservice for storaging and analysis evaluation results
Автор: Roman Batygin
(roman.batygin@mail.ru)
:toc:
:toc-title: Table of contents

== Overview

API provides operations with evaluation results


== Saves evaluation results report

__POST__ */api/save* - Saves evaluation results report


*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|<<EvaluationResultsRequest>>
a|
[source,json]
----
{
  "requestId" : "04b1373f-7838-4535-b65a-88c088830879",
  "instances" : {
    "structure" : "<data structure>",
    "relationName" : "Glass",
    "numInstances" : 214,
    "numAttributes" : 10,
    "numClasses" : 6,
    "className" : "Type"
  },
  "classifierReport" : {
    "type" : "ClassifierReport",
    "classifierName" : "ExtraTreesClassifier",
    "classifierDescription" : null,
    "options" : "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}",
    "classifierInputOptions" : [ {
      "key" : "Число деревьев:",
      "value" : "20"
    }, {
      "key" : "Минимальное число объектов в листе:",
      "value" : "2"
    }, {
      "key" : "Максиальная глубина дерева:",
      "value" : "0"
    }, {
      "key" : "Число случайных атрибутов:",
      "value" : "5"
    }, {
      "key" : "Алгоритм построения дерева решений:",
      "value" : "ID3"
    }, {
      "key" : "Число потоков",
      "value" : "6"
    }, {
      "key" : "Начальное значение (Seed)",
      "value" : "1"
    }, {
      "key" : "Число случайных расщеплений атрибута:",
      "value" : "6"
    }, {
      "key" : "Формирование обучающих выборок:",
      "value" : "Исходное обучающее множество"
    } ],
    "metaClassifier" : false
  },
  "evaluationMethodReport" : {
    "evaluationMethod" : "CROSS_VALIDATION",
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1
  },
  "statistics" : {
    "numTestInstances" : 214,
    "numCorrect" : 172,
    "numIncorrect" : 42,
    "pctCorrect" : 80.37383177570094,
    "pctIncorrect" : 19.626168224299064,
    "meanAbsoluteError" : 0.11885129227585131,
    "rootMeanSquaredError" : 0.231476151125149,
    "maxAucValue" : 0.9983739837398374,
    "varianceError" : 0.00436052266530287,
    "confidenceIntervalLowerBound" : 0.14902362368597982,
    "confidenceIntervalUpperBound" : 0.24349974080000147
  },
  "classificationCosts" : [ {
    "classValue" : "build wind float",
    "truePositiveRate" : 0.9142857142857143,
    "falsePositiveRate" : 0.125,
    "trueNegativeRate" : 0.875,
    "falseNegativeRate" : 0.08571428571428572,
    "rocCurve" : {
      "aucValue" : 0.9313988095238095,
      "specificity" : 0.8611111111111112,
      "sensitivity" : 0.9428571428571428,
      "thresholdValue" : 0.4138291855203621
    }
  }, {
    "classValue" : "vehic wind float",
    "truePositiveRate" : 0.23529411764705882,
    "falsePositiveRate" : 0.01015228426395939,
    "trueNegativeRate" : 0.9898477157360406,
    "falseNegativeRate" : 0.7647058823529411,
    "rocCurve" : {
      "aucValue" : 0.9252015527022992,
      "specificity" : 0.751269035532995,
      "sensitivity" : 1.0,
      "thresholdValue" : 0.08396763793615986
    }
  }, {
    "classValue" : "tableware",
    "truePositiveRate" : 0.7777777777777778,
    "falsePositiveRate" : 0.004878048780487805,
    "trueNegativeRate" : 0.9951219512195122,
    "falseNegativeRate" : 0.2222222222222222,
    "rocCurve" : {
      "aucValue" : 0.9983739837398374,
      "specificity" : 0.9951219512195122,
      "sensitivity" : 1.0,
      "thresholdValue" : 0.33422619047619045
    }
  }, {
    "classValue" : "build wind non-float",
    "truePositiveRate" : 0.8289473684210527,
    "falsePositiveRate" : 0.10869565217391304,
    "trueNegativeRate" : 0.8913043478260869,
    "falseNegativeRate" : 0.17105263157894737,
    "rocCurve" : {
      "aucValue" : 0.9111365369946606,
      "specificity" : 0.9492753623188406,
      "sensitivity" : 0.75,
      "thresholdValue" : 0.49067460317460315
    }
  }, {
    "classValue" : "headlamps",
    "truePositiveRate" : 0.8275862068965517,
    "falsePositiveRate" : 0.016216216216216217,
    "trueNegativeRate" : 0.9837837837837838,
    "falseNegativeRate" : 0.1724137931034483,
    "rocCurve" : {
      "aucValue" : 0.9606710158434296,
      "specificity" : 0.9459459459459459,
      "sensitivity" : 0.9655172413793104,
      "thresholdValue" : 0.1461273690078038
    }
  }, {
    "classValue" : "containers",
    "truePositiveRate" : 0.7692307692307693,
    "falsePositiveRate" : 0.014925373134328358,
    "trueNegativeRate" : 0.9850746268656716,
    "falseNegativeRate" : 0.23076923076923078,
    "rocCurve" : {
      "aucValue" : 0.9862227324913893,
      "specificity" : 0.9701492537313433,
      "sensitivity" : 0.9230769230769231,
      "thresholdValue" : 0.2746176338281601
    }
  } ],
  "confusionMatrix" : [ {
    "actualClass" : "build wind float",
    "predictedClass" : "build wind float",
    "numInstances" : 64
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 5
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "headlamps",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "build wind float",
    "numInstances" : 9
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 4
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 4
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "headlamps",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "build wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "tableware",
    "numInstances" : 7
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "build wind non-float",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "build wind float",
    "numInstances" : 8
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "tableware",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 63
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "containers",
    "numInstances" : 2
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "build wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "build wind non-float",
    "numInstances" : 3
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "headlamps",
    "numInstances" : 24
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "containers",
    "numInstances" : 1
  }, {
    "actualClass" : "containers",
    "predictedClass" : "build wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "containers",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "containers",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "containers",
    "predictedClass" : "build wind non-float",
    "numInstances" : 2
  }, {
    "actualClass" : "containers",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "containers",
    "predictedClass" : "containers",
    "numInstances" : 10
  } ]
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|<<EvaluationResultsResponse>>
a|
[source,json]
----
{
  "requestId" : "04b1373f-7838-4535-b65a-88c088830879"
}
----
|400
|Bad request
|*application/json*
|__array__<<<ValidationErrorDto>>>
a|
[source,json]
----
[ {
  "fieldName" : "requestId",
  "code" : "Pattern",
  "errorMessage" : "must match \"^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$\""
}, {
  "fieldName" : "instances.structure",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
}, {
  "fieldName" : "requestId",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
}, {
  "fieldName" : "instances.relationName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
}, {
  "fieldName" : "classifierReport.classifierName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
} ]
----
|===

== Gets evaluation results simple report

__POST__ */api/results* - Gets evaluation results simple report


*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|<<GetEvaluationResultsRequest>>
a|
[source,json]
----
{
  "requestId" : "04b1373f-7838-4535-b65a-88c088830879"
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|<<GetEvaluationResultsResponse>>
a|
[source,json]
----
{
  "requestId" : "04b1373f-7838-4535-b65a-88c088830879",
  "instances" : {
    "structure" : "<data structure>",
    "relationName" : "Glass",
    "numInstances" : 214,
    "numAttributes" : 10,
    "numClasses" : 6,
    "className" : "Type"
  },
  "classifierReport" : {
    "type" : "ClassifierReport",
    "classifierName" : "ExtraTreesClassifier",
    "classifierDescription" : null,
    "options" : "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}",
    "classifierInputOptions" : [ {
      "key" : "Число потоков",
      "value" : "6"
    }, {
      "key" : "Формирование обучающих выборок:",
      "value" : "Исходное обучающее множество"
    }, {
      "key" : "Алгоритм построения дерева решений:",
      "value" : "ID3"
    }, {
      "key" : "Число деревьев:",
      "value" : "20"
    }, {
      "key" : "Максиальная глубина дерева:",
      "value" : "0"
    }, {
      "key" : "Число случайных атрибутов:",
      "value" : "5"
    }, {
      "key" : "Число случайных расщеплений атрибута:",
      "value" : "6"
    }, {
      "key" : "Минимальное число объектов в листе:",
      "value" : "2"
    }, {
      "key" : "Начальное значение (Seed)",
      "value" : "1"
    } ],
    "metaClassifier" : false
  },
  "evaluationMethodReport" : {
    "evaluationMethod" : "CROSS_VALIDATION",
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1
  },
  "statistics" : {
    "numTestInstances" : 214,
    "numCorrect" : 172,
    "numIncorrect" : 42,
    "pctCorrect" : 80.3738,
    "pctIncorrect" : 19.6262,
    "meanAbsoluteError" : 0.1189,
    "rootMeanSquaredError" : 0.2315,
    "maxAucValue" : 0.9984,
    "varianceError" : 0.0044,
    "confidenceIntervalLowerBound" : 0.149,
    "confidenceIntervalUpperBound" : 0.2435
  },
  "classificationCosts" : [ {
    "classValue" : "build wind float",
    "truePositiveRate" : 0.9143,
    "falsePositiveRate" : 0.125,
    "trueNegativeRate" : 0.875,
    "falseNegativeRate" : 0.0857,
    "rocCurve" : {
      "aucValue" : 0.9314,
      "specificity" : 0.8611,
      "sensitivity" : 0.9429,
      "thresholdValue" : 0.4138
    }
  }, {
    "classValue" : "build wind non-float",
    "truePositiveRate" : 0.8289,
    "falsePositiveRate" : 0.1087,
    "trueNegativeRate" : 0.8913,
    "falseNegativeRate" : 0.1711,
    "rocCurve" : {
      "aucValue" : 0.9111,
      "specificity" : 0.9493,
      "sensitivity" : 0.75,
      "thresholdValue" : 0.4907
    }
  }, {
    "classValue" : "containers",
    "truePositiveRate" : 0.7692,
    "falsePositiveRate" : 0.0149,
    "trueNegativeRate" : 0.9851,
    "falseNegativeRate" : 0.2308,
    "rocCurve" : {
      "aucValue" : 0.9862,
      "specificity" : 0.9701,
      "sensitivity" : 0.9231,
      "thresholdValue" : 0.2746
    }
  }, {
    "classValue" : "headlamps",
    "truePositiveRate" : 0.8276,
    "falsePositiveRate" : 0.0162,
    "trueNegativeRate" : 0.9838,
    "falseNegativeRate" : 0.1724,
    "rocCurve" : {
      "aucValue" : 0.9607,
      "specificity" : 0.9459,
      "sensitivity" : 0.9655,
      "thresholdValue" : 0.1461
    }
  }, {
    "classValue" : "tableware",
    "truePositiveRate" : 0.7778,
    "falsePositiveRate" : 0.0049,
    "trueNegativeRate" : 0.9951,
    "falseNegativeRate" : 0.2222,
    "rocCurve" : {
      "aucValue" : 0.9984,
      "specificity" : 0.9951,
      "sensitivity" : 1.0,
      "thresholdValue" : 0.3342
    }
  }, {
    "classValue" : "vehic wind float",
    "truePositiveRate" : 0.2353,
    "falsePositiveRate" : 0.0102,
    "trueNegativeRate" : 0.9898,
    "falseNegativeRate" : 0.7647,
    "rocCurve" : {
      "aucValue" : 0.9252,
      "specificity" : 0.7513,
      "sensitivity" : 1.0,
      "thresholdValue" : 0.084
    }
  } ],
  "confusionMatrix" : [ {
    "actualClass" : "tableware",
    "predictedClass" : "build wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "build wind float",
    "numInstances" : 8
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 4
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 5
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "build wind non-float",
    "numInstances" : 63
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "containers",
    "numInstances" : 2
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "headlamps",
    "numInstances" : 0
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "build wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "containers",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "build wind non-float",
    "numInstances" : 3
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "containers",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "build wind non-float",
    "numInstances" : 1
  }, {
    "actualClass" : "containers",
    "predictedClass" : "build wind non-float",
    "numInstances" : 2
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "headlamps",
    "numInstances" : 24
  }, {
    "actualClass" : "containers",
    "predictedClass" : "build wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "headlamps",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "build wind float",
    "numInstances" : 64
  }, {
    "actualClass" : "containers",
    "predictedClass" : "containers",
    "numInstances" : 10
  }, {
    "actualClass" : "containers",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "tableware",
    "numInstances" : 1
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "containers",
    "numInstances" : 0
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 4
  }, {
    "actualClass" : "build wind float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "vehic wind float",
    "predictedClass" : "build wind float",
    "numInstances" : 9
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "containers",
    "predictedClass" : "tableware",
    "numInstances" : 0
  }, {
    "actualClass" : "build wind non-float",
    "predictedClass" : "vehic wind float",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "headlamps",
    "numInstances" : 1
  }, {
    "actualClass" : "tableware",
    "predictedClass" : "tableware",
    "numInstances" : 7
  }, {
    "actualClass" : "headlamps",
    "predictedClass" : "vehic wind float",
    "numInstances" : 0
  } ]
}
----
|400
|Bad request
|*application/json*
|__array__<<<ValidationErrorDto>>>
a|
[source,json]
----
[ {
  "fieldName" : "requestId",
  "code" : "Pattern",
  "errorMessage" : "must match \"^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$\""
} ]
----
|===

== Endpoint for searching optimal classifiers options for specified request

__POST__ */api/optimal-classifier-options* - Endpoint for searching optimal classifiers options for specified request


*Request body*

[width=100%]
|===
|*Content type*|*Required*|*Schema*|*Example*
|*application/json*
|true
|<<ClassifierOptionsRequest>>
a|
[source,json]
----
{
  "relationName" : "Glass",
  "dataHash" : "2aeb5c41423c895995e8cb304fe30b2d",
  "evaluationMethodReport" : {
    "evaluationMethod" : "CROSS_VALIDATION",
    "numFolds" : 10,
    "numTests" : 1,
    "seed" : 1
  },
  "sortFields" : null
}
----
|===



*Api responses*
[width=100%]
|===
|*Code*|*Description*|*Content type*|*Schema*|*Example*
|200
|OK
|*application/json*
|<<ClassifierOptionsResponse>>
a|
[source,json]
----
{
  "requestId" : "f8cecbf7-405b-403b-9a94-f51e8fb73ed8",
  "classifierReports" : [ {
    "type" : "ClassifierReport",
    "classifierName" : "ExtraTreesClassifier",
    "classifierDescription" : null,
    "options" : "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}",
    "classifierInputOptions" : [ {
      "key" : "Число потоков",
      "value" : "6"
    }, {
      "key" : "Формирование обучающих выборок:",
      "value" : "Исходное обучающее множество"
    }, {
      "key" : "Алгоритм построения дерева решений:",
      "value" : "ID3"
    }, {
      "key" : "Число деревьев:",
      "value" : "20"
    }, {
      "key" : "Максиальная глубина дерева:",
      "value" : "0"
    }, {
      "key" : "Число случайных атрибутов:",
      "value" : "5"
    }, {
      "key" : "Число случайных расщеплений атрибута:",
      "value" : "6"
    }, {
      "key" : "Минимальное число объектов в листе:",
      "value" : "2"
    }, {
      "key" : "Начальное значение (Seed)",
      "value" : "1"
    } ],
    "metaClassifier" : false
  }, {
    "type" : "ClassifierReport",
    "classifierName" : "ExtraTreesClassifier",
    "classifierDescription" : null,
    "options" : "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}",
    "classifierInputOptions" : [ {
      "key" : "Число потоков",
      "value" : "6"
    }, {
      "key" : "Формирование обучающих выборок:",
      "value" : "Исходное обучающее множество"
    }, {
      "key" : "Алгоритм построения дерева решений:",
      "value" : "ID3"
    }, {
      "key" : "Число деревьев:",
      "value" : "20"
    }, {
      "key" : "Максиальная глубина дерева:",
      "value" : "0"
    }, {
      "key" : "Число случайных атрибутов:",
      "value" : "5"
    }, {
      "key" : "Число случайных расщеплений атрибута:",
      "value" : "6"
    }, {
      "key" : "Минимальное число объектов в листе:",
      "value" : "2"
    }, {
      "key" : "Начальное значение (Seed)",
      "value" : "1"
    } ],
    "metaClassifier" : false
  } ]
}
----
|400
|Bad request
|*application/json*
|__array__<<<ValidationErrorDto>>>
a|
[source,json]
----
[ {
  "fieldName" : "evaluationMethodReport.evaluationMethod",
  "code" : "NotNull",
  "errorMessage" : "must not be null"
}, {
  "fieldName" : "dataHash",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
}, {
  "fieldName" : "relationName",
  "code" : "NotBlank",
  "errorMessage" : "must not be blank"
} ]
----
|===


== Components
=== EvaluationResultsResponse
:table-caption: Table
.Evaluation results response model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId*
|Request id
a|
__string__















|===
=== ValidationErrorDto
:table-caption: Table
.Validation error model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*fieldName*
|Field name
a|
__string__















|*code*
|Error code
a|
__string__















|*errorMessage*
|Error message
a|
__string__















|===
=== ClassificationCostsReport
:table-caption: Table
.Classification costs report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classValue**
|Class value
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*truePositiveRate**
|True positive rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*falsePositiveRate**
|False positive rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*trueNegativeRate**
|True negative rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*falseNegativeRate**
|False negative rate
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*rocCurve*
|-
a|
<<RocCurveReport>>















|===
=== ClassifierInputOption
:table-caption: Table
.Classifier input option model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*key**
|Option key
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*value**
|Option value
a|
__string__


*Min. length*: 0

*Max. length*: 255










|===
=== ClassifierReport
:table-caption: Table
.Classifier report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classifierName**
|Classifier name
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*classifierDescription*
|Classifier description
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*options**
|Classifier options string
a|
__string__















|*classifierInputOptions*
|Classifier input options
a|
__array__
<<<ClassifierInputOption>>
>















|*metaClassifier*
|Is meta classifier?
a|
__boolean__















|*type**
|-
a|
__string__















|===
=== ConfusionMatrixReport
:table-caption: Table
.Confusion matrix report
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*actualClass**
|Actual class
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*predictedClass**
|Predicted class
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*numInstances**
|Instances number
a|
__integer__






*Minimum*: 0*









|===
=== EnsembleClassifierReport
:table-caption: Table
.Ensemble classifier report
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*classifierName**
|Classifier name
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*classifierDescription*
|Classifier description
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*options**
|Classifier options string
a|
__string__















|*classifierInputOptions*
|Classifier input options
a|
__array__
<<<ClassifierInputOption>>
>















|*metaClassifier*
|Is meta classifier?
a|
__boolean__















|*type**
|-
a|
__string__















|*individualClassifiers*
|Individual classifiers reports
a|
__array__
<<<ClassifierReport>>
>















|===
=== EvaluationMethodReport
:table-caption: Table
.Evaluation method report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*evaluationMethod**
|Evaluation method
a|
__string__















*Values*:

* TRAINING_DATA

* CROSS_VALIDATION
|*numFolds*
|Folds number for k * V cross - validation method
a|
__integer__






*Minimum*: 2*









|*numTests*
|Tests number for k * V cross - validation method
a|
__integer__






*Minimum*: 1*









|*seed*
|Seed value for k * V cross - validation method
a|
__integer__















|===
=== EvaluationResultsRequest
:table-caption: Table
.Evaluation results request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId**
|Request id
a|
__string__


*Min. length*: 0

*Max. length*: 36







*Pattern*: `^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`


|*instances**
|-
a|
<<InstancesReport>>















|*classifierReport**
|-
a|


*One of types:*

* <<ClassifierReport>>

* <<EnsembleClassifierReport>>














|*evaluationMethodReport**
|-
a|
<<EvaluationMethodReport>>















|*statistics**
|-
a|
<<StatisticsReport>>















|*classificationCosts*
|Classification costs report
a|
__array__
<<<ClassificationCostsReport>>
>















|*confusionMatrix*
|Confusion matrix report
a|
__array__
<<<ConfusionMatrixReport>>
>















|===
=== InstancesReport
:table-caption: Table
.Training data report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*structure**
|Training data structure
a|
__string__















|*relationName**
|Relation name
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*numInstances**
|Instances number
a|
__integer__






*Minimum*: 2*









|*numAttributes**
|Attributes number
a|
__integer__






*Minimum*: 2*









|*numClasses**
|Classes number
a|
__integer__






*Minimum*: 2*









|*className**
|Class name
a|
__string__


*Min. length*: 0

*Max. length*: 255










|===
=== RocCurveReport
:table-caption: Table
.Roc curve report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*aucValue*
|Auc value
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*specificity*
|Specificity value at optimal ROC - curve point
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*sensitivity*
|Sensitivity value at optimal ROC - curve point
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*thresholdValue*
|Threshold value at optimal ROC - curve point
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|===
=== StatisticsReport
:table-caption: Table
.Evaluation statistics report model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*numTestInstances**
|Test instances number
a|
__integer__






*Minimum*: 2*









|*numCorrect**
|Correctly classified instances number
a|
__integer__






*Minimum*: 0*









|*numIncorrect**
|Incorrectly classified instances number
a|
__integer__






*Minimum*: 0*









|*pctCorrect**
|Correctly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*pctIncorrect**
|Incorrectly classified percentage
a|
__number__






*Minimum*: 0*

*Maximum*: 100*








|*meanAbsoluteError*
|Mean absolute error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*rootMeanSquaredError*
|Root mean squared error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*maxAucValue*
|Max AUC value
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*varianceError*
|Variance error
a|
__number__






*Minimum*: 0*

*Maximum*: 1*








|*confidenceIntervalLowerBound*
|95% confidence interval lower bound value
a|
__number__















|*confidenceIntervalUpperBound*
|95% confidence interval upper bound value
a|
__number__















|===
=== GetEvaluationResultsResponse
:table-caption: Table
.Get evaluation results response model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId*
|Request id
a|
__string__















|*instances*
|-
a|
<<InstancesReport>>















|*classifierReport*
|-
a|
<<ClassifierReport>>















|*evaluationMethodReport*
|-
a|
<<EvaluationMethodReport>>















|*statistics*
|-
a|
<<StatisticsReport>>















|*classificationCosts*
|Classification costs report
a|
__array__
<<<ClassificationCostsReport>>
>















|*confusionMatrix*
|Confusion matrix report
a|
__array__
<<<ConfusionMatrixReport>>
>















|===
=== GetEvaluationResultsRequest
:table-caption: Table
.Get evaluation results request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId**
|Request id
a|
__string__


*Min. length*: 0

*Max. length*: 36







*Pattern*: `^[0-9a-f]{8}-[0-9a-f]{4}-[34][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`


|===
=== ClassifierOptionsResponse
:table-caption: Table
.Classifier options response model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*requestId*
|Request id
a|
__string__















|*classifierReports*
|Optimal classifiers reports list
a|
__array__
<<<ClassifierReport>>
>















|===
=== ClassifierOptionsRequest
:table-caption: Table
.Classifier options request model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*relationName**
|Instances name
a|
__string__















|*dataHash**
|Instances MD5 hash sum
a|
__string__















|*evaluationMethodReport**
|-
a|
<<EvaluationMethodReport>>















|*sortFields*
|Sort fields list
a|
__array__
<<<SortField>>
>















|===
=== SortField
:table-caption: Table
.Sort field model
[width=100%]
|===
|*Name*|*Description*|*Schema*
|*fieldName**
|Sort field name
a|
__string__


*Min. length*: 0

*Max. length*: 255










|*direction*
|Sort direction
a|
__string__















*Values*:

* ASC

* DESC
|===
