spring:
  application:
    name: eca-external-api
  jmx:
    default-domain: eca-external-api
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  ## Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca_external_api
    username: postgres
    password: postgres
  ## Token datasource properties
  tokendatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca_oauth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        order_by:
          default_null_ordering: last
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        maxConcurrency: 10

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

ribbon:
  ReadTimeout: 60000

external-api:
  maxPageSize: 50
  dateFormat: yyyy-MM-dd HH:mm:ss
  batchSize: 100
  requestTimeoutMinutes: 60
  requestCacheDurationMinutes: 60
  classifiersPath: D:/classifiers/

classifiers-options:
  maximumFractionDigits: 4

queue:
  evaluationRequestQueue: evaluation-request-queue
  evaluationRequestReplyToQueue: external-api-evaluation-response-queue

## Swagger properties
swagger2:
  projectVersion: @project.version@
  groups:
    eca-external-api:
      title: External API
      description: Operations for external systems
      author: Roman Batygin
      email: roman.batygin@mail.ru
  tokenBaseUrl: http://localhost:8085/eca-oauth
  clientId: swagger
  secret: swagger_secret

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always