spring:
  ## Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://eca-db:5432/eca_external_api
    username: postgres
    password: postgres
  ## Token datasource properties
  tokendatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://eca-db:5432/eca_oauth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

## Swagger properties
swagger2:
  tokenBaseUrl: http://localhost:8080/eca-oauth

external-api:
  classifiersPath: /home/classifiers/
  trainDataPath: /home/classifiers/data/
  downloadBaseUrl: http://localhost:8080/eca-external-api
