spring:
  application:
    name: zuul-gate
  jmx:
    default-domain: zuul-gate
zuul:
  routes:
      server:
        path: /eca-server/**
        url: http://eca-server:8080/eca-server
      oauth:
        path: /auth-server/**
        url: http://eca-oauth:8080/eca-oauth
      frontend:
        path: /**
        url: http://eca-web:8080
  host:
    connect-timeout-millis: -1
    socket-timeout-millis: -1
  sensitiveHeaders: Cookie, Set-Cookie