spring:
  application:
    name: zuul-gate
  jmx:
    default-domain: zuul-gate
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  servlet:
    multipart:
      max-file-size: 10MB

zuul:
  routes:
      server:
        path: /eca-server/**
        serviceId: eca-server
      oauth:
        path: /eca-oauth/**
        serviceId: eca-oauth
      ds:
        path: /eca-ds/**
        serviceId: eca-data-storage
      external-api:
        path: /external-api/**
        serviceId: eca-external-api
      eca-mail:
        path: /eca-mail/**
        serviceId: eca-mail
      eca-ers:
        path: /eca-ers/**
        serviceId: eca-ers
      eca-web-push:
        path: /eca-web-push/**
        serviceId: eca-web-push
      eca-audit-log:
        path: /eca-audit-log/**
        serviceId: eca-audit-log
      frontend:
        path: /**
        serviceId: eca-web
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  sensitiveHeaders: Cookie, Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

ribbon:
  ReadTimeout: 60000

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    port: 8030
