zuul:
  routes:
      server:
        path: /eca-server/**
        url: http://eca-server:8080/eca-server
      oauth:
        path: /auth-server/**
        url: http://eca-oauth:8080/eca-oauth
      monitoring:
        path: /monitoring/**
        url: http://monitoring:8080
      frontend:
        path: /**
        url: http://eca-web:8080
  host:
    connect-timeout-millis: -1
    socket-timeout-millis: -1