language: java
jdk: openjdk8
install: git clone https://github.com/Stonnos/eca.git Stonnos/eca
script:
  - cd Stonnos
  - cd eca/eca-core
  - mvn clean install
  - cd ..
  - cd ..
  - cd eca-service
  - mvn clean install