language: java
jdk: openjdk11
services:
  - docker

install: true
addons:
  sonarcloud:
    organization: $ORGANIZATION_KEY
    token: $SONAR_TOKEN

stages:
  - name: test
  - name: sonar_analysis
  - name: build_image
    if: branch = master

jobs:
  include:
    - stage: test
      script: mvn clean test
    - stage: sonar_analysis
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=$PROJECT_KEY
    - stage: build_image
      before_script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      script:
        - mvn clean install dockerfile:build -Pprod -Dmaven.test.skip=true
        - docker tag eca-oauth $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-oauth;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-oauth;
        - docker tag eca-server $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-server;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-server;
        - docker tag eca-mail $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-mail;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-mail;
        - docker tag eca-data-storage $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-data-storage;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-data-storage;
        - docker tag eca-web $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-web;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:eca-web;
        - docker tag zuul-gate $DOCKER_USERNAME/$DOCKER_REPOSITORY:zuul-gate;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:zuul-gate;
        - docker tag discovery-server $DOCKER_USERNAME/$DOCKER_REPOSITORY:discovery-server;
        - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:discovery-server;
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache