docker build -t eca-oauth eca-oauth
docker build -t eca-server eca-server
docker build -t eca-mail eca-mail
docker build -t eca-data-storage eca-data-storage
docker build -t eca-ers eca-ers
docker build -t eca-web eca-web
docker build -t api-gateway api-gateway
docker build -t discovery-server discovery-server
docker build -t eca-web-push eca-web-push
docker build -t eca-audit-log eca-audit-log
docker build -t eca-data-loader eca-data-loader