docker build eca-oauth eca-oauth
docker build eca-server eca-server
docker build eca-mail eca-mail
docker build eca-data-storage eca-data-storage
docker build eca-ers eca-ers
docker build eca-web eca-web
docker build api-gateway api-gateway
docker build discovery-server discovery-server
docker build eca-web-push eca-web-push
docker build eca-audit-log eca-audit-log
docker build eca-data-loader eca-data-loader