version: '3'
services:

  eca-db:
    image: postgres:9.6.9
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
    ports:
       - "5433:5432"
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres

  eca-service:
    image: eca-service
    ports:
      - "8080:8080"
    depends_on:
      - eca-db