version: '3.5'
services:

  eca-db:
    image: postgres:9.6.9
    container_name: eca-db
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
      - /home/eca-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Novosibirsk"
      PGTZ: "Asia/Novosibirsk"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
      - /home/rabbit-data:/var/lib/rabbitmq

  eca-server:
    image: eca-server
    container_name: eca-server
    command: ["/wait-for-it.sh", "eca-db:5432", "--timeout=45", "--", "catalina.sh", "run"]
    volumes:
      - /home/experiment:/home/experiment
      - /home/experiment/data:/home/experiment/data
    environment:
      TZ: "Asia/Novosibirsk"
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - default
    depends_on:
      - eca-db
      - monitoring

  eca-oauth:
    image: eca-oauth
    container_name: eca-oauth
    command: ["/wait-for-it.sh", "eca-db:5432", "--timeout=45", "--", "catalina.sh", "run"]
    environment:
      TZ: "Asia/Novosibirsk"
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - default
    depends_on:
      - eca-db
      - monitoring

  eca-web:
    image: eca-web
    container_name: eca-web
    environment:
      TZ: "Asia/Novosibirsk"
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - default
    depends_on:
      - eca-server

  zuul-gate:
    image: zuul-gate
    container_name: zuul-gate
    environment:
      TZ: "Asia/Novosibirsk"
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8080:8080"
    networks:
      - default

  monitoring:
    image: monitoring
    container_name: monitoring
    environment:
      TZ: "Asia/Novosibirsk"
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8085:8080"
    networks:
      - default

networks:
  default:
    name: app-network
    driver: bridge
