version: "3.5"
services:

  eca-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: eca-db
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
      - eca-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
      - rabbit-data:/var/lib/rabbitmq
    environment:
      TZ: ${TIME_ZONE}
    networks:
      - default

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - default

  eca-server:
    image: eca-server
    container_name: eca-server
    volumes:
      - experiment-data:/home/experiment
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      JAVA_OPTS: "-Xmx1g"
      DB_CONTAINER_WAIT: ${DB_CONTAINER_WAIT}
      DB_CONTAINER_WAIT_TIMEOUT: ${DB_CONTAINER_WAIT_TIMEOUT}
      QUEUE_EVALUATIONREQUESTQUEUE: ${QUEUE_EVALUATION_REQUEST_QUEUE}
      QUEUE_EVALUATIONOPTIMIZERREQUESTQUEUE: ${QUEUE_EVALUATION_OPTIMIZER_REQUEST_QUEUE}
      QUEUE_EXPERIMENTREQUESTQUEUE: ${QUEUE_EXPERIMENT_REQUEST_QUEUE}
    networks:
      - default
    depends_on:
      - eca-db
      - rabbitmq
      - discovery-server

  eca-oauth:
    image: eca-oauth
    container_name: eca-oauth
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      DB_CONTAINER_WAIT: ${DB_CONTAINER_WAIT}
      DB_CONTAINER_WAIT_TIMEOUT: ${DB_CONTAINER_WAIT_TIMEOUT}
      JAVA_OPTS: "-Xmx756m"
    networks:
      - default
    depends_on:
      - eca-db
      - discovery-server

  eca-mail:
    image: eca-mail
    container_name: eca-mail
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      DB_CONTAINER_WAIT: ${DB_CONTAINER_WAIT}
      DB_CONTAINER_WAIT_TIMEOUT: ${DB_CONTAINER_WAIT_TIMEOUT}
      JAVA_OPTS: "-Xmx756m"
    networks:
      - default
    depends_on:
      - eca-db
      - discovery-server

  eca-data-storage:
    image: eca-data-storage
    container_name: eca-data-storage
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      DB_CONTAINER_WAIT: ${DB_CONTAINER_WAIT}
      DB_CONTAINER_WAIT_TIMEOUT: ${DB_CONTAINER_WAIT_TIMEOUT}
      JAVA_OPTS: "-Xmx756m"
    networks:
      - default
    depends_on:
      - eca-db
      - discovery-server

  eca-ers:
    image: eca-ers
    container_name: eca-ers
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      JAVA_OPTS: "-Xmx1g"
      DB_CONTAINER_WAIT: ${DB_CONTAINER_WAIT}
      DB_CONTAINER_WAIT_TIMEOUT: ${DB_CONTAINER_WAIT_TIMEOUT}
    networks:
      - default
    depends_on:
      - eca-db
      - discovery-server

  eca-external-api:
    image: eca-external-api
    container_name: eca-external-api
    volumes:
      - classifiers-data:/home/classifiers
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      JAVA_OPTS: "-Xmx1g"
      DB_CONTAINER_WAIT: ${DB_CONTAINER_WAIT}
      DB_CONTAINER_WAIT_TIMEOUT: ${DB_CONTAINER_WAIT_TIMEOUT}
    networks:
      - default
    depends_on:
      - eca-db
      - rabbitmq
      - discovery-server

  eca-web:
    image: eca-web
    container_name: eca-web
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      JAVA_OPTS: "-Xmx512m"
    networks:
      - default
    depends_on:
      - eca-server
      - discovery-server

  zuul-gate:
    image: zuul-gate
    container_name: zuul-gate
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      JAVA_OPTS: "-Xmx756m"
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - discovery-server

networks:
  default:
    name: app-network
    driver: bridge

volumes:
  eca-pgdata:
    name: eca-pgdata
  rabbit-data:
    name: rabbit-data
  experiment-data:
    name: experiment-data
  classifiers-data:
    name: classifiers-data
