version: '3.5'
services:

  eca-db:
    image: postgres:9.6.9
    container_name: eca-db
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
    ports:
      - "5433:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Asia/Novosibirsk"
      PGTZ: "Asia/Novosibirsk"

  eca-server:
    image: eca-server
    container_name: eca-server
    environment:
      TZ: "Asia/Novosibirsk"
    ports:
      - "8085:8080"
    networks:
      - default
    depends_on:
      - eca-db

   eca-web:
    image: eca-web
    container_name: eca-web
    environment:
      TZ: "Asia/Novosibirsk"
    ports:
      - "8083:8080"
    networks:
      - default
    depends_on:
      - eca-server

networks:
  default:
    name: app-network
    driver: bridge