version: "3.5"
services:

  eca-external-api:
    image: eca-external-api
    container_name: eca-external-api
    restart: always
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
      JAVA_OPTS: "-Xmx512m"
      OPENAPI_BASEPATH: "/external-api"
    networks:
      - default
    depends_on:
      - eca-db
      - rabbitmq
      - discovery-server

networks:
  default:
    name: app-network
    driver: bridge
