version: "3.5"
services:

  eca-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: eca-db
    volumes:
      - ./scripts/postgresinit.sql:/docker-entrypoint-initdb.d/postgresinit.sql
      - eca-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIME_ZONE}
      PGTZ: ${TIME_ZONE}

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
      - rabbit-data:/var/lib/rabbitmq
    environment:
      TZ: ${TIME_ZONE}
    networks:
      - default

  eca-server:
    image: eca-server
    container_name: eca-server
    command: ["/wait-for-it.sh", "eca-db:5432", "--timeout=${DB_CONTAINER_WAIT_TIMEOUT}", "--", "catalina.sh", "run"]
    volumes:
      - experiment-data:/home/experiment
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - default
    depends_on:
      - eca-db
      - rabbitmq

  eca-oauth:
    image: eca-oauth
    container_name: eca-oauth
    command: ["/wait-for-it.sh", "eca-db:5432", "--timeout=${DB_CONTAINER_WAIT_TIMEOUT}", "--", "catalina.sh", "run"]
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - default
    depends_on:
      - eca-db

  eca-web:
    image: eca-web
    container_name: eca-web
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - default
    depends_on:
      - eca-server

  zuul-gate:
    image: zuul-gate
    container_name: zuul-gate
    environment:
      TZ: ${TIME_ZONE}
      SPRING_PROFILES_ACTIVE: "docker"
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    name: app-network
    driver: bridge

volumes:
  eca-pgdata:
    name: eca-pgdata
  rabbit-data:
    name: rabbit-data
  experiment-data:
    name: experiment-data