= Microservice for storaging training data sets
Автор: Roman Batygin <roman.batygin@mail.ru>
:toc:
:toc-title: Оглавление

== Table of contents

API provides operations with training data sets for ECA web application

== Renames data with specified id

__*PUT*__ */instances/rename* - Renames data with specified id


*Request parameters*
|===
|Name|Description|Type|Schema
|*id**
|Instances id
|query
a|integer (int64)







|*tableName**
|Table name
|query
a|string 

*Min. length*: 0

*Max. length*: 30

*Pattern*: `^[0-9a-z_]+$`

|===

*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|-
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : null,
  "code" : "UniqueTableName",
  "errorMessage" : "Table with name [iris] already exists!"
} ]
----
|===

== Saves instances into database

__*POST*__ */instances/save* - Saves instances into database

|===
|Content type|Required|Schema|Example
|*multipart/form-data*
|false
|-
a|
-
|===

*Request parameters*
|===
|Name|Description|Type|Schema
|*tableName**
|Table name
|query
a|string 

*Min. length*: 0

*Max. length*: 30

*Pattern*: `^[0-9a-z_]+$`

|===

*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|*application/json*
|<<CreateInstancesResultDto>>
a|
[source,json]
----
{
  "id" : 1,
  "sourceFileName" : "iris.xls",
  "tableName" : "iris"
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : null,
  "code" : "UniqueTableName",
  "errorMessage" : "Table with name [iris] already exists!"
} ]
----
|===

== Finds instances tables with specified options such as filter, sorting and paging

__*POST*__ */instances/list* - Finds instances tables with specified options such as filter, sorting and paging

|===
|Content type|Required|Schema|Example
|*application/json*
|true
|<<PageRequestDto>>
a|
[source,json]
----
{
  "page" : 0,
  "size" : 25
}
----
|===

*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|*application/json*
|<<PageDto>>
a|
[source,json]
----
{
  "content" : [ {
    "id" : 1,
    "tableName" : "iris",
    "numInstances" : 150,
    "numAttributes" : 5,
    "created" : "2021-07-01 14:00:00",
    "createdBy" : "admin"
  } ],
  "page" : 0,
  "totalCount" : 1
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Finds data page for specified instances

__*POST*__ */instances/data-page* - Finds data page for specified instances

|===
|Content type|Required|Schema|Example
|*application/json*
|true
|<<PageRequestDto>>
a|
[source,json]
----
{
  "page" : 0,
  "size" : 25
}
----
|===

*Request parameters*
|===
|Name|Description|Type|Schema
|*id**
|Instances id
|query
a|integer (int64)







|===

*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|*application/json*
|<<PageDto>>
a|
[source,json]
----
{
  "content" : [ [ "5.1", "3.5", "1.4", "0.2", "Iris-setosa" ], [ "4.9", "3.0", "1.4", "0.2", "Iris-setosa" ], [ "4.7", "3.2", "1.3", "0.2", "Iris-setosa" ] ],
  "page" : 0,
  "totalCount" : 3
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Gets instances reports info

__*GET*__ */instances/reports-info* - Gets instances reports info


*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|*application/json*
|-
a|
[source,json]
----
[ {
  "title" : "Microsoft Excel (.xlsx)",
  "reportType" : "XLS",
  "fileExtension" : "xlsx"
}, {
  "title" : "Формат CSV (.csv)",
  "reportType" : "CSV",
  "fileExtension" : "csv"
}, {
  "title" : "Формат Arff (.arff)",
  "reportType" : "ARFF",
  "fileExtension" : "arff"
}, {
  "title" : "Json формат (.json)",
  "reportType" : "JSON",
  "fileExtension" : "json"
}, {
  "title" : "Xml формат (.xml)",
  "reportType" : "XML",
  "fileExtension" : "xml"
}, {
  "title" : "Текстовый формат (.txt)",
  "reportType" : "TXT",
  "fileExtension" : "txt"
}, {
  "title" : "Формат данных (.data)",
  "reportType" : "DATA",
  "fileExtension" : "data"
}, {
  "title" : "Microsoft Word (.docx)",
  "reportType" : "DOCX",
  "fileExtension" : "docx"
} ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|===

== Download instances report with specified type

__*GET*__ */instances/download* - Download instances report with specified type


*Request parameters*
|===
|Name|Description|Type|Schema
|*id**
|Instances id
|query
a|integer (int64)







|*reportType**
|Report type
|query
a|string 







*Values*:
* XLS

* CSV

* ARFF

* JSON

* XML

* TXT

* DATA

* DOCX

|===

*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|*application/octet-stream*
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : null,
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Gets instances details

__*GET*__ */instances/details/{id}* - Gets instances details


*Request parameters*
|===
|Name|Description|Type|Schema
|*id**
|Instances id
|path
a|integer (int64)







|===

*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|*application/json*
|<<InstancesDto>>
a|
[source,json]
----
{
  "id" : 1,
  "tableName" : "iris",
  "numInstances" : 150,
  "numAttributes" : 5,
  "created" : "2021-07-01 14:00:00",
  "createdBy" : "admin"
}
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : null,
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Gets attributes list for specified instances

__*GET*__ */instances/attributes/{id}* - Gets attributes list for specified instances


*Request parameters*
|===
|Name|Description|Type|Schema
|*id**
|Instances id
|path
a|integer (int64)







|===

*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|*application/json*
|-
a|
[source,json]
----
[ "x1", "x2", "x3", "x4", "class" ]
----
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : null,
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===

== Deletes instances with specified id

__*DELETE*__ */instances/delete* - Deletes instances with specified id


*Request parameters*
|===
|Name|Description|Type|Schema
|*id**
|Instances id
|query
a|integer (int64)







|===

*Список кодов ответа*
|===
|Code|Description|Content type|Schema|Example
|200
|OK
|-
|-
a|
-
|401
|Not authorized
|*application/json*
|-
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|400
|Bad request
|*application/json*
|-
a|
[source,json]
----
[ {
  "fieldName" : null,
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===


== Components
=== ValidationErrorDto
:table-caption: Table
.Validation error model
|===
|Name|Description|Schema
|*fieldName*
|Field name
a|
string







|*code*
|Error code
a|
string







|*errorMessage*
|Error message
a|
string







|===
=== CreateInstancesResultDto
:table-caption: Table
.Create instances result model
|===
|Name|Description|Schema
|*id**
|Instances id
a|
integer
(int64)







|*sourceFileName**
|Source file name
a|
string







|*tableName**
|Database table name
a|
string







|===
=== PageDto
:table-caption: Table
.Page model
|===
|Name|Description|Schema
|*content*
|Page content
a|
array







|*page*
|Page number
a|
integer
(int32)







|*totalCount*
|Total elements count in all pages
a|
integer
(int64)







|===
=== FilterRequestDto
:table-caption: Table
.Filter request model
|===
|Name|Description|Schema
|*name**
|Filter column name
a|
string

*Min. length*: 0

*Max. length*: 255



|*values*
|-
a|
array







|*matchMode**
|Match mode type
a|
string







*Values*:
* EQUALS

* LIKE

* RANGE

|===
=== PageRequestDto
:table-caption: Table
.Page request model
|===
|Name|Description|Schema
|*page**
|Page number
a|
integer
(int32)







|*size**
|Page size
a|
integer
(int32)







|*sortField*
|Sort field
a|
string

*Min. length*: 0

*Max. length*: 255



|*ascending*
|Is ascending sort?
a|
boolean







|*searchQuery*
|Search query string
a|
string

*Min. length*: 0

*Max. length*: 255



|*filters*
|Filters list
a|
array







|===
=== InstancesReportInfoDto
:table-caption: Table
.Instances report info model
|===
|Name|Description|Schema
|*reportType*
|Report type
a|
string







|*title*
|Report title
a|
string







|*fileExtension*
|Report file extension
a|
string







|===
=== InstancesDto
:table-caption: Table
.Instances model
|===
|Name|Description|Schema
|*id*
|Instances id
a|
integer
(int64)







|*tableName*
|Table name
a|
string







|*numInstances*
|Instances number
a|
integer
(int32)







|*numAttributes*
|Attributes number
a|
integer
(int32)







|*created*
|Instances creation date
a|
string







|*createdBy*
|User name
a|
string







|===
