= Microservice for collecting and storing audit events
Автор: Roman Batygin <roman.batygin@mail.ru>
:toc:
:toc-title: Оглавление

== Описание

API provides operations with audit events

== Downloads audit logs base report in xlsx format

*POST*
*/audit-log/report/download* - Downloads audit logs base report in xlsx format

|===
|Формат запроса|Обязательность|Тело запроса|Пример запроса
|application/json
|true
|<<PageRequestDto>>
a|
[source,json]
----
{
  "page" : 0,
  "size" : 25,
  "sortField" : "eventDate",
  "ascending" : false,
  "searchQuery" : "",
  "filters" : [ {
    "name" : "groupCode",
    "values" : [ "USER_PROFILE_ACTIONS" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "initiator",
    "values" : [ "admin" ],
    "matchMode" : "LIKE"
  }, {
    "name" : "eventDate",
    "values" : [ "2021-07-16" ],
    "matchMode" : "RANGE"
  } ]
}
----
|===
Список кодов ответа
|===
|Код ответа|Описание|Формат ответа|Пример ответа
|200
|OK
|application/octet-stream
a|
-
|401
|Not authorized
|application/json
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|403
|Permission denied
|application/json
a|
[source,json]
----
{
  "error" : "access_denied",
  "error_description" : "Access is denied"
}
----
|400
|Bad request
|application/json
a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Finds audit logs with specified options such as filter, sorting and paging

*POST*
*/audit-log/list* - Finds audit logs with specified options such as filter, sorting and paging

|===
|Формат запроса|Обязательность|Тело запроса|Пример запроса
|application/json
|true
|<<PageRequestDto>>
a|
[source,json]
----
{
  "page" : 0,
  "size" : 25,
  "sortField" : "eventDate",
  "ascending" : false,
  "searchQuery" : "",
  "filters" : [ {
    "name" : "groupCode",
    "values" : [ "USER_PROFILE_ACTIONS" ],
    "matchMode" : "EQUALS"
  }, {
    "name" : "initiator",
    "values" : [ "admin" ],
    "matchMode" : "LIKE"
  }, {
    "name" : "eventDate",
    "values" : [ "2021-07-16" ],
    "matchMode" : "RANGE"
  } ]
}
----
|===
Список кодов ответа
|===
|Код ответа|Описание|Формат ответа|Пример ответа
|200
|OK
|application/json
a|
[source,json]
----
{
  "content" : [ {
    "eventId" : "1d2de514-3a87-4620-9b97-c260e24340de",
    "message" : "Some action",
    "initiator" : "user",
    "groupCode" : "USER_ACTIONS",
    "groupTitle" : "User actions",
    "code" : "LOGIN",
    "codeTitle" : "User logged in",
    "eventDate" : "2021-07-01 14:00:00"
  } ],
  "page" : 0,
  "totalCount" : 1
}
----
|401
|Not authorized
|application/json
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|403
|Permission denied
|application/json
a|
[source,json]
----
{
  "error" : "access_denied",
  "error_description" : "Access is denied"
}
----
|400
|Bad request
|application/json
a|
[source,json]
----
[ {
  "fieldName" : "page",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 0"
}, {
  "fieldName" : "size",
  "code" : "Min",
  "errorMessage" : "must be greater than or equal to 1"
} ]
----
|===

== Saves audit event into database

*POST*
*/api/audit/event/save* - Saves audit event into database

|===
|Формат запроса|Обязательность|Тело запроса|Пример запроса
|application/json
|true
|<<AuditEventRequest>>
a|
[source,json]
----
{
  "eventId" : "a01ebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
  "message" : "Audit message",
  "initiator" : "user",
  "eventType" : "START",
  "groupCode" : "GROUP_CODE",
  "groupTitle" : "",
  "code" : "AUDIT_CODE",
  "codeTitle" : "",
  "eventDate" : "2021-07-16 07:57:11"
}
----
|===
Список кодов ответа
|===
|Код ответа|Описание|Формат ответа|Пример ответа
|200
|OK
|-
a|
-
|===

== Gets audit log filter fields

*GET*
*/audit-log/filter-templates/fields* - Gets audit log filter fields

Список кодов ответа
|===
|Код ответа|Описание|Формат ответа|Пример ответа
|200
|OK
|application/json
a|
[source,json]
----
[ {
  "fieldName" : "eventId",
  "description" : "ID события",
  "fieldOrder" : 0,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false,
  "dictionary" : null
}, {
  "fieldName" : "groupCode",
  "description" : "Группа событий",
  "fieldOrder" : 1,
  "filterFieldType" : "REFERENCE",
  "matchMode" : "EQUALS",
  "multiple" : false,
  "dictionary" : {
    "name" : "auditGroup",
    "values" : [ {
      "label" : "Действия пользователя в личном кабинете",
      "value" : "USER_PROFILE_ACTIONS"
    }, {
      "label" : "Действия с конфигурациями классификаторов",
      "value" : "CLASSIFIERS_CONFIGURATIONS_ACTIONS"
    }, {
      "label" : "Действия с обучающими выборками",
      "value" : "DATA_STORAGE_ACTIONS"
    } ]
  }
}, {
  "fieldName" : "initiator",
  "description" : "Инициатор события",
  "fieldOrder" : 2,
  "filterFieldType" : "TEXT",
  "matchMode" : "LIKE",
  "multiple" : false,
  "dictionary" : null
}, {
  "fieldName" : "eventDate",
  "description" : "Дата события",
  "fieldOrder" : 3,
  "filterFieldType" : "DATE",
  "matchMode" : "RANGE",
  "multiple" : true,
  "dictionary" : null
} ]
----
|401
|Not authorized
|application/json
a|
[source,json]
----
{
  "error" : "unauthorized",
  "error_description" : "Full authentication is required to access this resource"
}
----
|403
|Permission denied
|application/json
a|
[source,json]
----
{
  "error" : "access_denied",
  "error_description" : "Access is denied"
}
----
|400
|Bad request
|application/json
a|
[source,json]
----
[ {
  "fieldName" : null,
  "code" : "DataNotFound",
  "errorMessage" : "Entity with search key [1] not found!"
} ]
----
|===


== Описание форматов для запросов
=== FilterRequestDto
:table-caption: Таблица
.Filter request model
|===
|Название параметра|Описание параметра|Тип данных|Мин. длина|Макс. длина|Паттерн
|*name**
|Filter column name
|string 
|0
|255
|-
|*values*
|-
|array 
|-
|-
|-
|*matchMode**
|Match mode type
|string 
|-
|-
|-
|===
=== PageRequestDto
:table-caption: Таблица
.Page request model
|===
|Название параметра|Описание параметра|Тип данных|Мин. длина|Макс. длина|Паттерн
|*page**
|Page number
|integer (int32)
|-
|-
|-
|*size**
|Page size
|integer (int32)
|-
|-
|-
|*sortField*
|Sort field
|string 
|0
|255
|-
|*ascending*
|Is ascending sort?
|boolean 
|-
|-
|-
|*searchQuery*
|Search query string
|string 
|0
|255
|-
|*filters*
|Filters list
|array 
|-
|-
|-
|===
=== AuditEventRequest
:table-caption: Таблица
.Audit event request mode
|===
|Название параметра|Описание параметра|Тип данных|Мин. длина|Макс. длина|Паттерн
|*eventId**
|Audit event id
|string 
|0
|255
|-
|*message**
|Audit message
|string 
|-
|-
|-
|*initiator**
|Event initiator
|string 
|0
|255
|-
|*eventType**
|Event type
|string 
|-
|-
|-
|*groupCode**
|Audit group
|string 
|0
|255
|-
|*groupTitle*
|Audit group title
|string 
|0
|255
|-
|*code**
|Audit code
|string 
|0
|255
|-
|*codeTitle*
|Audit code title
|string 
|0
|255
|-
|*eventDate**
|Event date
|string (date-time)
|-
|-
|`yyyy-MM-dd HH:mm:ss`
|===
