export enum FormFieldType {
  TEXT = 'TEXT',
  INTEGER = 'INTEGER',
  DECIMAL = 'DECIMAL',
  BOOLEAN = 'BOOLEAN',
  REFERENCE = 'REFERENCE',
  ONE_OF_OBJECT = 'ONE_OF_OBJECT',
  LIST_OBJECTS = 'LIST_OBJECTS'
}
