{
 "title": "Eca - service dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ers requests time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_seconds_sum{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"save\"}[1m]))/sum(rate(feign_Client_seconds_count{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"save\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/save\" - AVG"
    },
    {
     "expr": "(max(feign_Client_seconds_max{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"save\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/save\" - MAX"
    },
    {
     "expr": "(sum(rate(feign_Client_seconds_sum{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"getEvaluationResults\"}[1m]))/sum(rate(feign_Client_seconds_count{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"getEvaluationResults\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/results\" - AVG"
    },
    {
     "expr": "(max(feign_Client_seconds_max{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"getEvaluationResults\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/results\" - MAX"
    },
    {
     "expr": "(sum(rate(feign_Client_seconds_sum{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"getClassifierOptions\"}[1m]))/sum(rate(feign_Client_seconds_count{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"getClassifierOptions\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/optimal-classifier-options\" - AVG"
    },
    {
     "expr": "(max(feign_Client_seconds_max{application=\"ECA-SERVER\",host=\"eca-ers\",method=\"getClassifierOptions\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/optimal-classifier-options\" - MAX"
    }
   ]
  },
  {
   "title": "S3 requests time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(s3_storage_object_request_seconds_sum{application=\"ECA-SERVER\",method=\"uploadObject\"}[1m]))/sum(rate(s3_storage_object_request_seconds_count{application=\"ECA-SERVER\",method=\"uploadObject\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"uploadObject\" - AVG"
    },
    {
     "expr": "(max(s3_storage_object_request_seconds_max{application=\"ECA-SERVER\",method=\"uploadObject\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"uploadObject\" - MAX"
    },
    {
     "expr": "(sum(rate(s3_storage_object_request_seconds_sum{application=\"ECA-SERVER\",method=\"getObject\"}[1m]))/sum(rate(s3_storage_object_request_seconds_count{application=\"ECA-SERVER\",method=\"getObject\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"getObject\" - AVG"
    },
    {
     "expr": "(max(s3_storage_object_request_seconds_max{application=\"ECA-SERVER\",method=\"getObject\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"getObject\" - MAX"
    },
    {
     "expr": "(sum(rate(s3_storage_object_request_seconds_sum{application=\"ECA-SERVER\",method=\"getObjectPresignedProxyUrl\"}[1m]))/sum(rate(s3_storage_object_request_seconds_count{application=\"ECA-SERVER\",method=\"getObjectPresignedProxyUrl\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"getObjectPresignedProxyUrl\" - AVG"
    },
    {
     "expr": "(max(s3_storage_object_request_seconds_max{application=\"ECA-SERVER\",method=\"getObjectPresignedProxyUrl\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"getObjectPresignedProxyUrl\" - MAX"
    }
   ]
  },
  {
   "title": "Ers success requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"ECA-SERVER\",host=\"eca-ers\",http_status=\"200\",method=\"save\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "/api/save"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"ECA-SERVER\",host=\"eca-ers\",http_status=\"200\",method=\"getEvaluationResults\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "/api/results"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"ECA-SERVER\",host=\"eca-ers\",http_status=\"200\",method=\"getClassifierOptions\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "/api/optimal-classifier-options"
    }
   ]
  },
  {
   "title": "S3 request object memory total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum(rate(s3_storage_object_size_bytes_sum{application=\"ECA-SERVER\"}[1m]))/sum(rate(s3_storage_object_size_bytes_count{application=\"ECA-SERVER\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "AVG size"
    },
    {
     "expr": "(max(s3_storage_object_size_bytes_max{application=\"ECA-SERVER\"})) >= 0 OR on() vector(0)",
     "legendFormat": "MAX object size"
    }
   ]
  },
  {
   "title": "Ers 5xx errors / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-ers\",application=\"ECA-SERVER\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-server"
    }
   ]
  },
  {
   "title": "S3 success requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "(sum(rate(s3_storage_request_success_total{application=\"ECA-SERVER\",method=\"uploadObject\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "uploadObject"
    },
    {
     "expr": "(sum(rate(s3_storage_request_success_total{application=\"ECA-SERVER\",method=\"downloadObject\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "downloadObject"
    },
    {
     "expr": "(sum(rate(s3_storage_request_success_total{application=\"ECA-SERVER\",method=\"getObjectPresignedUrl\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "getObjectPresignedProxyUrl"
    }
   ]
  },
  {
   "title": "Mail error requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "(sum(rate(eca_mail_sending_message_error_total[1m]) * 60)) >= 0 OR on() vector(0)",
     "legendFormat": "mail_error_requests"
    }
   ]
  },
  {
   "title": "S3 error requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "(sum(rate(s3_storage_request_error_total{application=\"ECA-SERVER\",method=\"uploadObject\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "uploadObject"
    },
    {
     "expr": "(sum(rate(s3_storage_request_error_total{application=\"ECA-SERVER\",method=\"downloadObject\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "downloadObject"
    },
    {
     "expr": "(sum(rate(s3_storage_request_error_total{application=\"ECA-SERVER\",method=\"getObjectPresignedUrl\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "getObjectPresignedProxyUrl"
    }
   ]
  }
 ]
}