spring:
  application:
    name: eca-auto-tests
  jmx:
    default-domain: eca-auto-tests
  ## Auto tests datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca_auto_tests
    username: postgres
    password: postgres
    jpa:
      ddlAuto: update
      databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  ## Eca server datasource properties
  ecaserverdatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca
    username: postgres
    password: postgres
    jpa:
      ddlAuto: validate
      databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  cache:
    cache-names: instances
    caffeine:
      spec: maximumSize=10, expireAfterWrite=180s
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        maxConcurrency: 10

## Swagger properties
open-api:
  basePath: /
  title: Auto tests execution module
  description: API provides operations for auto tests execution
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

mail:
  userName: rbatsw@gmail.com
  password: czawqizcrdxfqlrv
  enabled: false

queue:
  experimentRequestQueue: experiment-request-queue
  experimentReplyToQueue: experiment-response-queue
  evaluationRequestQueue: evaluation-request-queue
  evaluationReplyToQueue: evaluation-response-queue

auto-tests:
  pageSize: 25
  schedulerPoolSize: 1
  delaySeconds: 2
  experimentsDataPath: classpath*:experiments/**/*.json
  requestTimeoutInSeconds: 1200
  ecaServerBaseUrl: http://localhost:8080/eca-server
  ecaErsBaseUrl: http://localhost:8080/eca-ers

server:
  port: 8093
