spring:
  application:
    name: eca-auto-tests
  ## Auto tests datasource properties
  jpa:
    properties:
      hibernate:
        id:
          ## Use one hibernate_sequence for all entities
          db_structure_naming_strategy: legacy
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5433/eca_auto_tests
    username: postgres
    password: postgres
    jpa:
      ddlAuto: update
  ## Eca server datasource properties
  ecaserverdatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5433/eca
    username: postgres
    password: postgres
    jpa:
      ddlAuto: validate
  cache:
    cache-names: instances
    caffeine:
      spec: maximumSize=10, expireAfterWrite=180s
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        maxConcurrency: 10
  security:
    oauth2:
      client:
        registration:
          api-client:
            client-id: external-api
            client-secret: external_api_secret
            scope: external-api
            authorization-grant-type: client_credentials
            provider: api-client
        provider:
          api-client:
            token-uri: http://localhost:8080/oauth2/token

## Swagger properties
open-api:
  basePath: /
  title: Auto tests execution module
  description: API provides operations for auto tests execution
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

mail:
  userName: rbatsw@gmail.com
  password: czawqizcrdxfqlrv
  enabled: false

queue:
  experimentRequestQueue: experiment-request-queue
  experimentReplyToQueue: experiment-response-queue
  evaluationRequestQueue: evaluation-request-queue
  evaluationReplyToQueue: evaluation-response-queue

auto-tests:
  pageSize: 25
  schedulerPoolSize: 1
  delaySeconds: 2
  experimentsDataPath: classpath*:experiments/**/*.json
  classifiersDataPath: classpath*:classifiers/**/*.json
  requestTimeoutInSeconds: 1200
  ecaErsBaseUrl: http://localhost:8080/eca-ers

data-loader:
  url: http://localhost:8080/eca-data-loader

server:
  port: 8093
