spring:
  application:
    name: eca-server
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 100
  camunda:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca_camunda
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          ## Use one hibernate_sequence for all entities
          db_structure_naming_strategy: legacy
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  cache:
    type: caffeine
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        maxConcurrency: 10
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      repositories:
        enabled: false
  cloud:
    openfeign:
      oauth2:
        clientRegistrationId: api-client
  security:
    oauth2:
      client:
        registration:
          api-client:
            client-id: eca_service_tech
            client-secret: 02#eca_service_tech6
            scope: internal-api
            authorization-grant-type: client_credentials
            provider: api-client
        provider:
          api-client:
            token-uri: http://localhost:8085/oauth2/token

eureka:
  instance:
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator
  client:
    registerWithEureka: false
    fetchRegistry: false

## Application properties
app:
  threadPoolSize: 10
  schedulerPoolSize: 3
  numberOfDaysForStorage: 180
  ## Remove expired models flag
  autoRemoveExpiredModels: false
  ## Each day at midnight
  removeModelCron: 0 0 0 * * *
  pageSize: 10
  maxPagesNum: 99
  modelDownloadUrlExpirationDays: 7
  shortLifeUrlExpirationMinutes: 5
  modelCacheTtlSeconds: 180
  modelCacheSize: 25

## Queues properties
queue:
  evaluationRequestQueue: evaluation-request-queue
  evaluationOptimizerRequestQueue: evaluation-optimizer-request-queue
  experimentRequestQueue: experiment-request-queue

## Cross - validation properties
cross-validation:
  numFolds: 10
  numTests: 1
  seed: 1

classifiers-options:
  maximumFractionDigits: 4

## Swagger properties
open-api:
  basePath: /
  title: Microservice for classifiers learning
  description: API provides operations for individual and ensemble classification models learning
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@
  tokenBaseUrl: http://localhost:8080
  apiAuth:
    PASSWORD:
      scopes: web

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      client-secret: swagger_secret
    disable-swagger-default-url: true

## Classifier properties
classifiers:
  evaluationTimeoutMinutes: 10
  ## Scheduler delay in seconds
  delaySeconds: 5
  ## Must be grater than evaluationTimeoutMinutes
  lockTtlSeconds: 660
  batchSize: 5
  threadPoolSize: 3
  retryIntervalSeconds: 60

## Experiment properties
experiment:
  resultSize: 5
  numIterations: 100
  individualClassifiersStoragePath: classpath*:classifiers/**/*.json
  maximumFractionDigits: ${classifiers-options.maximumFractionDigits}
  ## Experiment evaluation timeout in minutes
  evaluationTimeoutMinutes: 120
  ## Scheduler delay in seconds
  delaySeconds: 30
  experimentLocalStoragePath: /home/experiment
  lockTtlSeconds: 300
  retryIntervalSeconds: 60
  batchSize: 1
  ensemble:
    numIterations: 25
    numBestClassifiers: 4
    multiThreadModeEnabled: true
    numThreads: 10
    numFoldsForStacking: 10

minio:
  url: http://localhost:9000
  proxyUrl: http://localhost:9000
  accessKey: minio
  secretKey: minio-pa66word
  bucketName: eca-service
  autoCreateBucket: true

cache:
  specs:
    evaluation-results:
      expireAfterWriteSeconds: 1200
      maxSize: 50
    global-filters:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    sort-fields:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    filter-templates:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    filter-dictionaries:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    message-templates:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    evaluationLogsTotalCountQuery:
      expireAfterWriteSeconds: 1200
      maxSize: 512
    experimentsTotalCountQuery:
      expireAfterWriteSeconds: 1200
      maxSize: 512

auth-server:
  baseUrl: http://localhost:8085/eca-oauth
  clientId: eca_service_tech
  clientSecret: 02#eca_service_tech6

processes:
  processExperimentId: ExperimentProcess
  processEvaluationId: ProcessEvaluationRequest
  createExperimentRequestProcessId: CreateExperimentRequestProcess
  createEvaluationRequestProcessId: CreateEvaluationRequestProcess

management:
  observations:
    annotations:
      ## Enables span annotations processing
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        fields:
          - tx.id
      remote-fields:
        - tx.id
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    rabbit:
      enabled: false
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full

server:
  forward-headers-strategy: framework
