spring:
  application:
    name: eca-server
  jmx:
    default-domain: eca-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eca
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        order_by:
          default_null_ordering: last
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  cache:
    type: caffeine
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        maxConcurrency: 10
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      repositories:
        enabled: false
  sleuth:
    log:
      slf4j:
        whitelisted-mdc-keys: tx.id, ev.requestId
    propagation-keys: tx.id, ev.requestId
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

ribbon:
  ReadTimeout: 60000

## Application properties
app:
  maxPageSize: 50
  threadPoolSize: 10
  notifications:
    webPushesEnabled: false
    emailsEnabled: false

## Queues properties
queue:
  evaluationRequestQueue: evaluation-request-queue
  evaluationOptimizerRequestQueue: evaluation-optimizer-request-queue
  experimentRequestQueue: experiment-request-queue

## Cross - validation properties
cross-validation:
  numFolds: 10
  numTests: 1
  seed: 1
  ## Cross validation timeout in minutes
  timeout: 60

classifiers-options:
  maximumFractionDigits: 4

## Swagger properties
open-api:
  basePath: /
  title: Microservice for classifiers learning
  description: API provides operations for individual and ensemble classification models learning
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@
  tokenBaseUrl: http://localhost:8080
  apiAuth:
    PASSWORD:
      scopes: web

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      client-secret: swagger_secret
    disable-swagger-default-url: true

## Experiment properties
experiment:
  resultSize: 5
  numIterations: 100
  fileFormat: experiment_%s.model
  storagePath: D:/experiment/
  individualClassifiersStoragePath: classpath*:classifiers/**/*.json
  downloadBaseUrl: http://localhost:8085/eca-server
  maximumFractionDigits: ${classifiers-options.maximumFractionDigits}
  numberOfDaysForStorage: 14
  ## Each day at midnight
  removeExperimentCron: 0 0 0 * * *
  ## Every 2 hours
  ersSendingCron: 0 0 0/2 * * *
  ## Experiment timeout in hours
  timeout: 5
  ## Scheduler delay in seconds
  delaySeconds: 30

  data:
    storagePath: D:/experiment/data/
    fileFormat: data_%s.xlsx
    dateFormat: yyyy-MM-dd HH:mm:ss
  ensemble:
    numIterations: 25
    numBestClassifiers: 4
    multiThreadModeEnabled: true
    numThreads:
    numFoldsForStacking: 10
  lock:
    registryKey: experiments-registry
    expireAfter: 18060000

ers:
  useClassifierOptionsCache: false
  classifierOptionsCacheDurationInDays: 2

cache:
  specs:
    evaluation-results:
      expireAfterWriteSeconds: 1200
      maxSize: 50
    global-filters:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    filter-templates:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    filter-dictionaries:
      expireAfterWriteSeconds: 18000
      maxSize: 100

auth-server:
  baseUrl: http://localhost:8085/eca-oauth
  clientId: eca_web
  clientSecret: web_secret

redis-lock:
  expireAfter: 60000
  registryKey: eca-server-lock

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    rabbit:
      enabled: false
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always

server:
  forward-headers-strategy: framework
