spring:
  application:
    name: eca-server
  jmx:
    default-domain: eca-server
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca
    username: postgres
    password: postgres
  ## Token datasource properties
  tokendatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca-oauth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        order_by:
          default_null_ordering: last
  cache:
    cache-names: classifiers, evaluation-results, global-filters, filter-templates, filter-dictionaries
    caffeine:
      spec: maximumSize=100, expireAfterWrite=1800s
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  boot:
    admin:
      client:
        instance:
          service-url: http://localhost:8085/eca-server
        url: http://localhost:8085/monitoring
        username: admin
        password: secret
        read-timeout: 1m
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        maxConcurrency: 10

## Application common configs
common:
  maxPageSize: 50
  classifierOptionsCacheDurationInDays: 2
  threadPoolSize: 10

## Cross - validation properties
cross-validation:
  numFolds: 10
  numTests: 1
  seed: 1
  ## Cross validation timeout in minutes
  timeout: 60

## Swagger properties
swagger2:
  projectVersion: @project.version@
  groups:
    eca:
      title: REST API for ECA application
      description: API for individual and ensemble classification models learning
      author: Roman Batygin
      email: roman.batygin@mail.ru
    eca-web:
      title: REST API for web application
      description: Operations for ECA web application
      author: Roman Batygin
      email: roman.batygin@mail.ru
  tokenUrl: http://localhost:8085/eca-oauth/oauth/token
  clientId: swagger
  secret: swagger_secret

## Experiment properties
experiment:
  resultSize: 5
  numIterations: 100
  fileFormat: experiment_%s.model
  storagePath: D:/experiment/
  individualClassifiersStoragePath: classifiers
  downloadUrl: http://localhost:8085/eca-server/eca-api/experiment/download/%s
  maximumFractionDigits: 4
  numberOfDaysForStorage: 14
  ## Each day at midnight
  removeExperimentCron: 0 0 0 * * *
  ## Every 2 hours
  ersSendingCron: 0 0 0/2 * * *
  ## Experiment timeout in hours
  timeout: 5
  ## Scheduler delay in seconds
  delaySeconds: 30

  data:
    storagePath: D:/experiment/data/
    fileFormat: data_%s.xlsx
    dateFormat: yyyy-MM-dd HH:mm:ss
  ensemble:
    numIterations: 25
    numBestClassifiers: 4
    multiThreadModeEnabled: true
    numThreads:
    numFoldsForStacking: 10

  mail:
    from: rbatsw@gmail.com
    subject: Eca - service
    serviceUrl: http://localhost:8090/notification-service/ws/
    enabled: true
    messageTemplatesMap:
      NEW: email-new-template.html
      FINISHED: email-message-template.html
      ERROR: email-error-message-template.html
      TIMEOUT: email-timeout-message-template.html
    ssl:
      trustStore: classpath:notification/notification-truststore.jks
      trustStorePassword: notification

ers-config:
  url: http://localhost:8089/evaluation-results-service/ws/
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always