spring:
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://postgres-db:5432/eca
    username: postgres
    password: postgres
  ## Token datasource properties
  tokendatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://postgres-db:5432/eca_oauth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

## Swagger properties
swagger2:
  tokenUrl: http://localhost:8080/eca-oauth/oauth/token

## Experiment properties
experiment:
  storagePath: /home/experiment/
  downloadUrl: http://localhost:8080/eca-server/eca-api/experiment/download/%s
  data:
    storagePath: /home/experiment/data/
  mail:
    from: rbatsw@gmail.com
    subject: Eca - service
    serviceUrl: https://notification-service:8443/ws/
    enabled: true
    ssl:
      trustStore: classpath:notification/notification-truststore.jks
      trustStorePassword: notification

ers:
  url: https://evaluation-results-service:9443/ws/
  enabled: true
  ssl:
    trustStore: classpath:evaluation-results/evaluation-truststore.jks
    trustStorePassword: evaluation