spring:
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://eca-db:5432/eca
    username: postgres
    password: postgres
  ## Token datasource properties
  tokendatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://eca-db:5432/eca-oauth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  boot:
    admin:
      client:
        instance:
          service-url: http://eca-server:8080/eca-server
        url: http://monitoring:8080

## Swagger properties
swagger2:
  oauthUrl: http://localhost:8080/auth-server

## Experiment properties
experiment:
  storagePath: /home/experiment/
  downloadUrl: http://localhost:8080/eca-server/experiment/download/%s
  data:
    storagePath: /home/experiment/data/
  mail:
    from: rbatsw@gmail.com
    subject: Eca - service
    serviceUrl: http://notification-service:8080/notification-service/ws/
    enabled: true

ers-config:
  url: http://evaluation-results-service:8080/evaluation-results-service/ws/
  enabled: true