spring:
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://eca-db:5432/eca
    username: postgres
    password: postgres
  ## Token datasource properties
  tokendatasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://eca-db:5432/eca_oauth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

## Swagger properties
swagger2:
  tokenUrl: http://localhost:8080/auth-server/oauth/token

## Experiment properties
experiment:
  storagePath: /home/experiment/
  downloadUrl: http://localhost:8080/eca-server/eca-api/experiment/download/%s
  data:
    storagePath: /home/experiment/data/
  mail:
    from: rbatsw@gmail.com
    subject: Eca - service
    serviceUrl: http://notification-service:8080/ws/
    enabled: true

ers:
  url: http://evaluation-results-service:8080/ws/
  enabled: true