spring:
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://postgres-db:5432/eca
    username: postgres
    password: postgres
  camunda:
    driver-class-name: org.postgresql.Driver
    jdbc-url:  jdbc:postgresql://postgres-db:5432/eca_camunda
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  rabbitmq:
    host: rabbitmq
  redis:
    host: redis

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

app:
  push:
    enabled: true
    async: true

## Swagger properties
open-api:
  tokenBaseUrl: http://localhost:8080/eca-oauth

mail:
  client:
    enabled: true

redelivery:
  enabled: true

minio:
  url: http://s3-minio-storage:9000
  proxyUrl: http://localhost:8098/object-storage

auth-server:
  baseUrl: http://eca-oauth:8080

service:
  feign:
    oauth:
      tokenUrl: http://eca-oauth:8080

lock:
  enabled: true
  registry-type: REDIS
  redis:
    expireAfter: 60000
    registryKey: eca-server-lock

rabbit:
  enabled: true

management:
  health:
    rabbit:
      enabled: true
    redis:
      enabled: true
