spring:
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://eca-db:5432/eca
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

## Swagger properties
swagger2:
  tokenBaseUrl: http://localhost:8080/eca-oauth

## Experiment properties
experiment:
  storagePath: /home/experiment/
  downloadBaseUrl: http://localhost:8080/eca-server
  data:
    storagePath: /home/experiment/data/

ers:
  url: http://evaluation-results-service:8080/ws/
  enabled: true

auth-server:
  baseUrl: http://eca-oauth:8080
