spring:
  application:
    name: eca-server
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 100
  camunda:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/eca_camunda
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        order_by:
          default_null_ordering: last
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  cache:
    type: caffeine
  redis:
    client-type: jedis
  rabbitmq:
    listener:
      simple:
        concurrency: 10
        maxConcurrency: 10
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      repositories:
        enabled: false
  sleuth:
    baggage:
      correlation-fields: tx.id, ev.requestId
      remote-fields: tx.id, ev.requestId

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

## Application properties
app:
  threadPoolSize: 10
  numberOfDaysForStorage: 14
  ## Each day at midnight
  removeModelCron: 0 0 0 * * *
  pageSize: 10
  modelDownloadUrlExpirationDays: 7
  shortLifeUrlExpirationMinutes: 5
  push:
    enabled: false

## Queues properties
queue:
  evaluationRequestQueue: evaluation-request-queue
  evaluationOptimizerRequestQueue: evaluation-optimizer-request-queue
  experimentRequestQueue: experiment-request-queue

## Cross - validation properties
cross-validation:
  numFolds: 10
  numTests: 1
  seed: 1

classifiers-options:
  maximumFractionDigits: 4

## Swagger properties
open-api:
  basePath: /
  title: Microservice for classifiers learning
  description: API provides operations for individual and ensemble classification models learning
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@
  tokenBaseUrl: http://localhost:8080
  apiAuth:
    PASSWORD:
      scopes: web

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      client-secret: swagger_secret
    disable-swagger-default-url: true

## Classifier properties
classifiers:
  timeout: 60
  ## Scheduler delay in seconds
  delaySeconds: 3
  maxRequestsPerJob: 25
  notSupportedClassifierTemplates: ADA_BOOST, HETEROGENEOUS_CLASSIFIER, STACKING

## Experiment properties
experiment:
  resultSize: 5
  numIterations: 100
  individualClassifiersStoragePath: classpath*:classifiers/**/*.json
  maximumFractionDigits: ${classifiers-options.maximumFractionDigits}
  ## Experiment timeout in hours
  timeout: 5
  ## Scheduler delay in seconds
  delaySeconds: 30
  experimentLocalStoragePath: /home/experiment
  ensemble:
    numIterations: 25
    numBestClassifiers: 4
    multiThreadModeEnabled: true
    numThreads:
    numFoldsForStacking: 10

ers:
  useClassifierOptionsCache: false
  classifierOptionsCacheDurationInDays: 2

minio:
  url: http://localhost:9000
  proxyUrl: http://localhost:9000
  accessKey: minio
  secretKey: minio-pa66word
  bucketName: eca-service

cache:
  specs:
    evaluation-results:
      expireAfterWriteSeconds: 1200
      maxSize: 50
    global-filters:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    sort-fields:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    filter-templates:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    filter-dictionaries:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    message-templates:
      expireAfterWriteSeconds: 18000
      maxSize: 100
    instances-meta-data:
      expireAfterWriteSeconds: 18000
      maxSize: 100

auth-server:
  baseUrl: http://localhost:8085/eca-oauth
  clientId: eca_service_tech
  clientSecret: 02#eca_service_tech6

service:
  feign:
    oauth:
      tokenUrl: http://localhost:8085/eca-oauth
      clientId: eca_service_tech
      clientSecret: 02#eca_service_tech6

processes:
  processExperimentId: ExperimentProcess
  processEvaluationId: ProcessEvaluationWebRequest
  createExperimentRequestProcessId: CreateExperimentRequestProcess
  createEvaluationRequestProcessId: CreateEvaluationRequestProcess

lock:
  evaluations-registry:
    ## Evaluation lock expiration in millis
    expireAfter: 3660000
  experiments-registry:
    ## Experiment lock expiration in millis
    expireAfter: 18060000

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    rabbit:
      enabled: false
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full

server:
  forward-headers-strategy: framework
