spring:
  ## Eca datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://eca-db:5432/eca
    username: postgres
    password: postgres
  camunda:
    driver-class-name: org.postgresql.Driver
    jdbc-url:  jdbc:postgresql://eca-db:5432/eca_camunda
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: rabbitmq
  data:
    redis:
      host: redis
  security:
    oauth2:
      client:
        provider:
          api-client:
            token-uri: http://eca-oauth:8080/oauth2/token

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

## Swagger properties
open-api:
  tokenBaseUrl: http://localhost:8080/eca-oauth

user-profile:
  client:
    cache:
      enabled: true
      rabbit:
        dataEventExchangeName: user-profile-options-exchange
        dataEventQueue: eca-server-user-profile-options-data-event-queue

mail:
  client:
    enabled: true

web-push:
  client:
    enabled: true
    async: true

redelivery:
  enabled: true

minio:
  url: http://s3-minio-storage:9000
  proxyUrl: http://localhost:8098/object-storage

auth-server:
  baseUrl: http://eca-oauth:8080

lock:
  enabled: true
  registry-type: REDIS

rabbit:
  enabled: true

management:
  health:
    rabbit:
      enabled: true
    redis:
      enabled: true
