= Библиотека для отправки email сообщений
:toc:
:toc-title: Оглавление

== Введение

В данном документе приведена инструкция для подключения библиотеки eca-mail-client к spring boot приложению.

== 1. Базовые настройки библиотеки

Для начала, необходимо добавить зависимость в pom.xml

[source,xml]
----
<dependency>
    <groupId>eca.service</groupId>
    <artifactId>eca-mail-client</artifactId>
    <version>${project.version}</version>
</dependency>
----

В файле application.yml добавить настройки библиотеки

[source,yml]
----
mail:
  client:
    ## Вкл./выкл. отправки email сообщений
    enabled: true
    ## Флаг асинхронной отправки email сообщений
    async: true
    ## Размер пула потоков для асинхронной отправки email сообщений
    threadPoolSize: 3
    encrypt:
      ## Вкл./выкл. хранение email сообщений в зашифрованном виде
      enabled: true
      ## Пароль для алгоритма генерации ключа PBKDF2WithHmacSHA1
      password: passw0rd@!
      ## Соль для алгоритма генерации ключа PBKDF2WithHmacSHA1
      salt: s@lt#
----

Добавить класс конфигурации

[source,java]
----
// Если в вашем модуле есть JPA сущности, то указать путь для сканирования
@EntityScan(basePackageClasses = MyEntity.class)
// Если в вашем модуле есть JPA репозитории, то указать путь для сканирования
@EnableJpaRepositories(basePackageClasses = MyEntityRepository.class)
@Configuration
public class AppConfiguration {
}
----

В конфигурационный файл liquibase, добавить путь к файлу mail-client-changelog.xml со скриптами для создания служебных таблиц.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">
    <!-- your change sets -->
    <include file="../mail-client-changelog.xml" relativeToChangelogFile="true"/>
</databaseChangeLog>
----

== 2. Настройка использования механизма redelivery

Для поддержки redelivery (повторной отправки запросов в случае сбоев) в файле application.yml необходимо добавить следующие настройки

[source,yml]
----
redelivery:
  ## Вкл./выкл. механизма redelivery.
  enabled: true
  ## Интервал между запусками заданий на повторную отправку запросов
  redeliveryIntervalMillis: 60000
  ## Размер страницы для повторной отправки запросов
  pageSize: 25
----

== 3. Настройка использования блокировок для кластерной среды на примере redis

В pom.xml необходимо добавить зависимости для интеграции с redis

[source,xml]
----
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-redis</artifactId>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
----

В файле application.yml добавить следующие настройки

[source,yml]
----
lock:
  ## Вкл./выкл. распределенных блокировок.
  ## Используется для scheduler повторной отправки email сообщений.
  ## Необходимо использовать в случае, если запущено несколько инстансов приложения, во избежании data race
  enabled: true
----

Добавить конфигурацию бина redeliveryLockRegistry для управления блокировками

[source,java]
----
// Подключить библиотеку блокировок
@EnableLocks
@Configuration
public class EmailClientLockConfiguration {

    @Bean(name = "redeliveryLockRegistry")
    public LockRegistry redisLockRegistry(RedisConnectionFactory redisConnectionFactory) {
        return new RedisLockRegistry(redisConnectionFactory, "yourRegistryKey");
    }
}
----

Примечание: Также можно использовать любую другу реализацию LockRegistry от spring integration.
