spring:
  ## Email properties
  mail:
    host: @mail.host@
    port: @mail.port@
    username: @mail.username@
    password: @mail.password@
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
  ## Datasource properties
  datasource:
    driver-class-name: @jdbc.driver@
    url: @jdbc.url@
    username: @jdbc.user@
    password: @jdbc.password@
  jpa:
    hibernate:
      ddl-auto: @jdbc.ddlAuto@
    database-platform: @jdbc.dialect@

## Cross - validation properties
cross-validation:
  numFolds: 10
  numTests: 10
  seed: 3
  ## Cross validation timeout in minutes
  timeout: 60

## Server port
server:
  port: @server.port@

## Experiment properties
experiment:
  resultSize: 100
  numIterations: 50
  fileFormat: experiment%d.txt
  storagePath: @storagePath@
  downloadUrl: http://localhost:@server.port@/eca-service/experiment/download/%s
  maximumFractionDigits: 4
  ## Experiment timeout in hours
  timeout: 5
  delay: 60000

  data:
    storagePath: @data.storagePath@
    fileFormat: data%d.arff
    dateFormat: yyyy-MM-dd HH:mm:ss
  ensemble:
    numIterations: 25

  mail:
    from: r.batygin@intabia.ru
    subject: Experiment results from eca - service
    maxFailedAttemptsToSent: 10
    messageTemplatesMap:
      FINISHED: email-message-template.html
      ERROR: email-error-message-template.html
      TIMEOUT: email-error-message-template.html