spring:
  ## Email properties
  mail:
    host: @mail.host@
    port: @mail.port@
    username: @mail.username@
    password: @mail.password@
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: false
  ## Datasource properties
  datasource:
    driver-class-name: @jdbc.driver@
    url: @jdbc.url@
    username: @jdbc.user@
    password: @jdbc.password@
  jpa:
    hibernate:
      ddl-auto: @jdbc.ddlAuto@
    database-platform: @jdbc.dialect@

## Cross - validation properties
cross-validation:
  numFolds: 10
  numTests: 1
  seed: 3
  ## Cross validation timeout in minutes
  timeout: 60

## Server port
server:
  port: @server.port@

project:
  version: @project.version@


## Experiment properties
experiment:
  resultSize: 25
  numIterations: 100
  fileFormat: experiment%d.txt
  storagePath: @storagePath@
  downloadUrl: http://localhost:@server.port@/eca-service/experiment/download/%s
  maximumFractionDigits: 4
  numberOfDaysForStorage: 30
  ## Each day at midnight
  schedulerCron: 0 0 0 * * *
  ## Experiment timeout in hours
  timeout: 5
  ## Scheduler delay in seconds
  delaySeconds: 120
  processStatuses: [NEW]
  sentStatuses: [FINISHED, ERROR, TIMEOUT]

  data:
    storagePath: @data.storagePath@
    fileFormat: data%d.arff
    dateFormat: yyyy-MM-dd HH:mm:ss
  ensemble:
    numIterations: 25
    numBestClassifiers: 4

  mail:
    from: rbatsw@gmail.com
    subject: Experiment results from eca - service
    maxFailedAttemptsToSent: 10
    messageTemplatesMap:
      FINISHED: email-message-template.html
      ERROR: email-error-message-template.html
      TIMEOUT: email-timeout-message-template.html

liquibase:
  contexts: schema,data
  change-log: classpath:db/liquibase-changelog.xml