spring:
  ## Datasource properties
  datasource:
    driver-class-name: @jdbc.driver@
    url: @jdbc.url@
    username: @jdbc.user@
    password: @jdbc.password@
  jpa:
    hibernate:
      ddl-auto: @jdbc.ddlAuto@
    database-platform: @jdbc.dialect@
  cache:
    cache-names: classifiers
    caffeine:
      spec: maximumSize=25, expireAfterWrite=7200s

## Cross - validation properties
crossValidation:
  numFolds: 10
  numTests: 1
  seed: 1
  ## Cross validation timeout in minutes
  timeout: 60
  classifierOptionsCacheDurationInDays: 2

## Swagger properties
swagger2:
  projectVersion: @project.version@
  title: Eca service REST API
  description: API for individual and ensemble classification models learning
  author: Roman Batygin
  email: roman.batygin@mail.ru

## Experiment properties
experiment:
  resultSize: 25
  numIterations: 100
  fileFormat: experiment%d.model
  storagePath: @storagePath@
  individualClassifiersStoragePath: classifiers
  downloadUrl: http://localhost:8085/eca-service/experiment/download/%s
  maximumFractionDigits: 4
  numberOfDaysForStorage: 14
  ## Each day at midnight
  removeExperimentCron: 0 0 0 * * *
  ## Experiment timeout in hours
  timeout: 5
  ## Scheduler delay in seconds
  delaySeconds: 30
  pageSize: 1
  resultSizeToSend: 5

  data:
    storagePath: @data.storagePath@
    fileFormat: data%d.arff
    dateFormat: yyyy-MM-dd HH:mm:ss
  ensemble:
    numIterations: 25
    numBestClassifiers: 4
    multiThreadModeEnabled: true
    numThreads:
    numFoldsForStacking: 10

  mail:
    from: rbatsw@gmail.com
    subject: Eca - service
    serviceUrl: http://localhost:8085/notification-service/ws/
    enabled: true
    messageTemplatesMap:
      NEW: email-new-template.html
      FINISHED: email-message-template.html
      ERROR: email-error-message-template.html
      TIMEOUT: email-timeout-message-template.html

ersConfig:
  url: http://localhost:8085/evaluation-results-service/ws/
  enabled: true
  threadPoolSize: 10


## Liquibase properties
liquibase:
  contexts: schema,data
  change-log: classpath:db/liquibase-changelog.xml
