spring:
  ## Email properties
  mail:
    host: @mail.host@
    port: @mail.port@
    username: @mail.username@
    password: @mail.password@
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: false
  ## Datasource properties
  datasource:
    driver-class-name: @jdbc.driver@
    url: @jdbc.url@
    username: @jdbc.user@
    password: @jdbc.password@
  jpa:
    hibernate:
      ddl-auto: @jdbc.ddlAuto@
    database-platform: @jdbc.dialect@
  cache:
    cache-names: classifiers
    caffeine:
      spec: maximumSize=25, expireAfterWrite=7200s

## Cross - validation properties
cross-validation:
  numFolds: 10
  numTests: 1
  seed: 3
  ## Cross validation timeout in minutes
  timeout: 60

## Swagger properties
swagger2:
  projectVersion: @project.version@
  title: Eca service REST API
  description: API for individual and ensemble classification models learning
  author: Roman Batygin
  email: roman.batygin@mail.ru

## Experiment properties
experiment:
  resultSize: 25
  numIterations: 100
  fileFormat: experiment%d.txt
  storagePath: @storagePath@
  individualClassifiersStoragePath: classifiers
  downloadUrl: http://localhost:8085/eca-service/experiment/download/%s
  maximumFractionDigits: 4
  numberOfDaysForStorage: 30
  ## Each day at midnight
  schedulerCron: 0 0 0 * * *
  ## Experiment timeout in hours
  timeout: 5
  ## Scheduler delay in seconds
  delaySeconds: 30
  pageSize: 1

  data:
    storagePath: @data.storagePath@
    fileFormat: data%d.arff
    dateFormat: yyyy-MM-dd HH:mm:ss
  ensemble:
    numIterations: 25
    numBestClassifiers: 4
    multiThreadModeEnabled: true
    numThreads:

  mail:
    from: rbatsw@gmail.com
    subject: Experiment results from eca - service
    maxFailedAttemptsToSent: 10
    messageTemplatesMap:
      FINISHED: email-message-template.html
      ERROR: email-error-message-template.html
      TIMEOUT: email-timeout-message-template.html

## Liquibase properties
liquibase:
  contexts: schema,data
  change-log: classpath:db/liquibase-changelog.xml
