spring:
  application:
    name: monitoring
  jmx:
    default-domain: monitoring
  ## Email properties
  mail:
    host: smtp.gmail.com
    port: 25
    username: rbatsw@gmail.com
    password: czawqizcrdxfqlrv
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: false
  security:
    user:
      name: admin
      password: secret
  boot:
    admin:
      notify:
        mail:
          to: roman.batygin@mail.ru