spring:
  application:
    name: eca-web-push
  jmx:
    default-domain: eca-web-push
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  ## Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eca_web_push
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        order_by:
          default_null_ordering: last
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  sleuth:
    log:
      slf4j:
        whitelisted-mdc-keys: tx.id, ev.requestId
    propagation-keys: tx.id, ev.requestId

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

auth-server:
  baseUrl: http://localhost:8085/eca-oauth
  clientId: eca_service_tech
  clientSecret: 02#eca_service_tech6

queues:
  pushQueue: /push

## Swagger properties
open-api:
  basePath: /
  title: Web pushes microservice
  description: API provides operations for sending web pushes
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full

server:
  forward-headers-strategy: framework
