spring:
  application:
    name: eca-web-push
  jmx:
    default-domain: eca-web-push
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  sleuth:
    log:
      slf4j:
        whitelisted-mdc-keys: tx.id, ev.requestId
    propagation-keys: tx.id, ev.requestId
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

auth-server:
  baseUrl: http://localhost:8085/eca-oauth
  clientId: eca_service_tech
  clientSecret: 02#eca_service_tech6

queues:
  bindings:
    EXPERIMENT_STATUS: /queue/experiment

## Swagger properties
open-api:
  basePath: /
  title: Web pushes microservice
  description: API provides operations for sending web pushes
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full

server:
  forward-headers-strategy: framework
