spring:
  application:
    name: eca-web
  jmx:
    default-domain: eca-web
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

ribbon:
  ReadTimeout: 60000

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full
