spring:
  application:
    name: eca-web

eureka:
  instance:
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator
  client:
    registerWithEureka: false
    fetchRegistry: false

## Swagger properties
open-api:
  basePath: /
  title: Microservice for web application
  description: API provides operations for web application
  author: Roman Batygin
  email: roman.batygin@mail.ru
  tokenBaseUrl: http://localhost:8080
  apiAuth:
    PASSWORD:
      scopes: web

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      client-secret: swagger_secret
    disable-swagger-default-url: true

auth-server:
  baseUrl: http://localhost:8085/eca-oauth
  clientId: eca_service_tech
  clientSecret: 02#eca_service_tech6

management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full
