spring:
  application:
    name: eca-web
  jmx:
    default-domain: eca-web

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: 60000

web-config:
  apiUrl: http://localhost:8085/eca-server
  oauthUrl: http://localhost:8085/eca-oauth/oauth/token
  clientId: eca_web
  secret: web_secret

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
