spring:
  application:
    name: eca-web
  jmx:
    default-domain: eca-web

web-config:
  apiUrl: http://localhost:8085/eca-server
  oauthUrl: http://localhost:8085/eca-oauth/oauth/token
  clientId: eca_web
  secret: web_secret
