eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

## Swagger properties
open-api:
  tokenBaseUrl: http://localhost:8080/eca-oauth

auth-server:
  baseUrl: http://eca-oauth:8080
