spring:
  application:
    name: eca-ers
  ## Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/evaluation_results_storage
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    cache-names: evaluation-results-sort-fields
    caffeine:
      spec: maximumSize=10, expireAfterWrite=36000s
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  sleuth:
    log:
      slf4j:
        whitelisted-mdc-keys: tx.id
    propagation-keys: tx.id

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

ribbon:
  ReadTimeout: 60000

## Swagger properties
open-api:
  basePath: /
  title: Microservice for storaging and analysis evaluation results
  description: API provides operations with evaluation results
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@

ers:
  resultSize: 5

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  forward-headers-strategy: framework
