= Описание API для авторизации
:toc:
:toc-title: Оглавление

== 1. Пример запроса на получение access token

Для получения access токена необходимо выполнить следующий запрос:

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/token -d grant_type=password -d username=admin -d password=secret
----

где eca_web:web_secret - пара clientId и clientSecret

Запрос возвращает пару access_token/refresh_token:

[source,json]
----
{
  "access_token": "5LG5eDZgyPq4_X9KwVqkHLnYfjrDrEK0pdGF3sqe_V8Y1vq0T1N3c_Q_KYsNsdcFsJ1rwNA35Er1IB_h9qEo-N47j0OUTxihhAzNLIZBwc3BHtn2u7sZmr7cyRv__mLX",
  "refresh_token": "ZJgZvaMv99aheGf-fUQPbBuDRCo9bX2YmPyH6Wn3VRNFJIHwIOn5tTGbZ2uEPPs4GkzIW55ZqtVlzzhtzgNIGaz3KXMAZdhKND0COb6OrW4XVTnLh2QgcQkQiUSDA-jW",
  "scope": "web",
  "token_type": "Bearer",
  "expires_in": 899
}
----

В случае, если у пользователя установлен временный пароль, то запрос возвращает 403 ошибку с телом ответа:

[source,json]
----
{
  "error": "change_password_required",
  "error_description": "Password must be changed"
}
----

В случае, если настроена двухфакторная аутентификация, то запрос возвращает 403 ошибку с телом ответа:

[source,json]
----
{
  "error": "tfa_required",
  "error_description": "Two-factor authentication required",
  "token": "ff47d750-0b50-40f0-9dc8-454819685eea",
  "expires_in": "120"
}
----

где token - временный токен, expires_in - время действия одноразового пароля, который должен прийти по почте, привязанной к учетной записи пользователя

== 2. Пример запроса на обновление access token на основе refresh token

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/token -d grant_type=refresh_token -d refresh_token=ZJgZvaMv99aheGf-fUQPbBuDRCo9bX2YmPyH6Wn3VRNFJIHwIOn5tTGbZ2uEPPs4GkzIW55ZqtVlzzhtzgNIGaz3KXMAZdhKND0COb6OrW4XVTnLh2QgcQkQiUSDA-jW
----

== 3. Пример запроса на получение токена с использованием двухфакторной аутентификации

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/token -d grant_type=tfa_code -d token=ff47d750-0b50-40f0-9dc8-454819685eea -d tfa_code=849674
----

где *tfa_code* - одноразовый пароль для двухфакторной аутентификации, который должен прийти по почте.

== 4. Пример запроса на проверку валидности access token

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/introspect -d token=5LG5eDZgyPq4_X9KwVqkHLnYfjrDrEK0pdGF3sqe_V8Y1vq0T1N3c_Q_KYsNsdcFsJ1rwNA35Er1IB_h9qEo-N47j0OUTxihhAzNLIZBwc3BHtn2u7sZmr7cyRv__mLX
----

Пример ответа на запрос:

[source,json]
----
{
  ## Признак активности токена
  "active": true,
  "sub": "admin",
  "aud": [
    "eca_web"
  ],
  "nbf": 1718556179,
  ## Доступные scope
  "scope": "web",
  ## Список ролей пользователя
  "roles": [
    "ROLE_USER"
  ],
  "iss": "http://localhost:8080",
  "exp": 1718557079,
  "iat": 1718556179,
  "jti": "255d10d7-f058-4cc6-bc78-36da9343eba8",
  "client_id": "eca_web",
  "token_type": "Bearer"
}
----

== 5. Пример запроса на отзыв access токена

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/revoke -d token=5LG5eDZgyPq4_X9KwVqkHLnYfjrDrEK0pdGF3sqe_V8Y1vq0T1N3c_Q_KYsNsdcFsJ1rwNA35Er1IB_h9qEo-N47j0OUTxihhAzNLIZBwc3BHtn2u7sZmr7cyRv__mLX
----
