= Описание API для авторизации
:toc:
:toc-title: Оглавление

== 1. Пример запроса на получение access token

Для получения access токена необходимо выполнить следующий запрос:

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/token -d grant_type=password -d username=admin -d password=secret
----

где eca_web:web_secret - пара clientId и clientSecret

Запрос возвращает ответ в формате json и пару access_token/refresh_token в заголовках Set-Cookie:

[source,json]
----
{
  "scope": "web",
  "token_type": "Bearer"
}
----

Заголовки ответа:

*Set-Cookie:*
*AccessToken*=56UjSjQvXLH08BxW1wLxxCMeVRQFJkzvDsYJgsunXkYL0iqppY2jOaJ7hBjCdLKaQl3lDTFrnmumjUmYQtVbn6jQnwrV1g3PmPh3jLDq1Jhkt7IqyU0YiThiF-Epmjsz; Max-Age=1800; Expires=Tue, 10 Dec 2024 16:59:24 GMT; Path=/; HttpOnly; SameSite=Strict

*Set-Cookie:*
*RefreshToken*=UtBs7IiqkKqBq8cjlSFoj29_2gwQkcifCQZ6VCHP3Y6XTMy0PPG-EF-Tw1zQ93sNpXmv8q2Li32dwaVd64sUa7sLLxu9Drd205uVulO9BiNfb8lP0cPX8qSTcHneJOJO; Max-Age=2592000; Expires=Thu, 09 Jan 2025 16:29:24 GMT; Path=/eca-oauth/oauth2/token; HttpOnly; SameSite=Strict

В случае, если у пользователя установлен временный пароль, то запрос возвращает 403 ошибку с телом ответа:

[source,json]
----
{
  "error": "change_password_required",
  "error_description": "Password must be changed"
}
----

В случае, если настроена двухфакторная аутентификация, то запрос возвращает 403 ошибку с телом ответа:

[source,json]
----
{
  "error": "tfa_required",
  "error_description": "Two-factor authentication required",
  "token": "ff47d750-0b50-40f0-9dc8-454819685eea",
  "expires_in": "120"
}
----

где token - временный токен, expires_in - время действия одноразового пароля, который должен прийти по почте, привязанной к учетной записи пользователя

== 2. Пример запроса на обновление access token на основе refresh token

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/token -d grant_type=refresh_token -b "RefreshToken=UtBs7IiqkKqBq8cjlSFoj29_2gwQkcifCQZ6VCHP3Y6XTMy0PPG-EF-Tw1zQ93sNpXmv8q2Li32dwaVd64sUa7sLLxu9Drd205uVulO9BiNfb8lP0cPX8qSTcHneJOJO"
----

где *RefreshToken* - cookie с refresh токеном

== 3. Пример запроса на получение токена с использованием двухфакторной аутентификации

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/token -d grant_type=tfa_code -d token=ff47d750-0b50-40f0-9dc8-454819685eea -d tfa_code=849674
----

где *tfa_code* - одноразовый пароль для двухфакторной аутентификации, который должен прийти по почте, *token* - временный токен

== 4. Пример запроса на проверку валидности access token

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/introspect -d token=5LG5eDZgyPq4_X9KwVqkHLnYfjrDrEK0pdGF3sqe_V8Y1vq0T1N3c_Q_KYsNsdcFsJ1rwNA35Er1IB_h9qEo-N47j0OUTxihhAzNLIZBwc3BHtn2u7sZmr7cyRv__mLX
----

Пример ответа на запрос:

[source,json]
----
{
  "active": true,
  "sub": "admin",
  "aud": [
    "eca_web"
  ],
  "nbf": 1718556179,
  "scope": "web",
  "roles": [
    "ROLE_USER"
  ],
  "iss": "http://localhost:8080",
  "exp": 1718557079,
  "iat": 1718556179,
  "jti": "255d10d7-f058-4cc6-bc78-36da9343eba8",
  "client_id": "eca_web",
  "token_type": "Bearer"
}
----

где

* active - признак активности токена
* sub - логин пользователя
* scope - доступные scopes
* roles - роли пользователя
* client_id - идентификатор клиента
* token_type - тип токена
* exp - дата истечения срока действия токена в мс.
* jti - id токена

== 5. Пример запроса на отзыв access токена

[source,bash]
----
curl eca_web:web_secret@localhost:8080/eca-oauth/oauth2/revoke -b "AccessToken=56UjSjQvXLH08BxW1wLxxCMeVRQFJkzvDsYJgsunXkYL0iqppY2jOaJ7hBjCdLKaQl3lDTFrnmumjUmYQtVbn6jQnwrV1g3PmPh3jLDq1Jhkt7IqyU0YiThiF-Epmjsz"
----

где *AccessToken* - cookie с access токеном
