= DISCOVERY SERVER API
:toc:
:toc-title: Оглавление

== Введение

В данном документе приведено описание API сервиса discovery server.

== 1. Список доступных методов

|===
|*Endpoint*|*Тип запроса*|*Описание*|*Формат запроса*|*Формат ответа*
|http://eca-service:8761/api/prometheus/sd-configs
|GET
|Возвращает ответ для prometheus со списком сервисов для мониторинга
|-
|application/json
|===

== 2. Получение списка сервисов для мониторинга с помощью prometheus

=== 2.1. Пример запроса

Для получения списка сервисов необходимо выполнить следующий запрос:

[source,bash]
----
curl -X GET "http://eca-service:8761/api/prometheus/sd-configs"
----

Пример ответа:

[source,json]
----
[
    {
        "targets": [
            "859eb9bc8f89:8080"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-web",
            "__meta_discovery_app_instance_name": "eca-web-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:16:44"
        }
    },
    {
        "targets": [
            "375a17fa4e70:8080"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-ers",
            "__meta_discovery_app_instance_name": "eca-ers-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:16:53"
        }
    },
    {
        "targets": [
            "329a34741260:8099"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-web-push",
            "__meta_discovery_app_instance_name": "eca-web-push-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:16:54"
        }
    },
    {
        "targets": [
            "5760a5ab801b:8030"
        ],
        "labels": {
            "__meta_discovery_app_name": "zuul-gate",
            "__meta_discovery_app_instance_name": "zuul-gate-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:17:02"
        }
    },
    {
        "targets": [
            "7f343a34022f:8080"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-mail",
            "__meta_discovery_app_instance_name": "eca-mail-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:17:02"
        }
    },
    {
        "targets": [
            "5fc8351f29c4:8080"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-audit-log",
            "__meta_discovery_app_instance_name": "eca-audit-log-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:17:04"
        }
    },
    {
        "targets": [
            "1e91c94aa786:8080"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-data-storage",
            "__meta_discovery_app_instance_name": "eca-data-storage-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:17:07"
        }
    },
    {
        "targets": [
            "132eb1c5dd15:8080"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-oauth",
            "__meta_discovery_app_instance_name": "eca-oauth-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:17:09"
        }
    },
    {
        "targets": [
            "26213c37a099:8080"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-server",
            "__meta_discovery_app_instance_name": "eca-server-1",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:17:12"
        }
    },
    {
        "targets": [
            "2708d3ca6b79:8080"
        ],
        "labels": {
            "__meta_discovery_app_name": "eca-server",
            "__meta_discovery_app_instance_name": "eca-server-2",
            "__meta_discovery_app_instance_metrics_path": "/actuator/prometheus",
            "__meta_discovery_app_instance_status": "UP",
            "__meta_discovery_app_instance_last_updated_date": "2022-12-16 13:16:46"
        }
    }
]
----

Подробное описание формата ответа для prometheus приведено в https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config.

=== 2.2. Описание меток для <relabel_config>

|===
|*Название метки*|*Описание*|*Пример значения*
|__meta_discovery_app_name
|Название сервиса
|eca-server
|__meta_discovery_app_instance_name
|Название инстанса для конкретного сервиса
|eca-server-1
|__meta_discovery_app_instance_metrics_path
|Endpoint сервиса для получения метрик в формате prometheus
|/actuator/prometheus
|__meta_discovery_app_instance_status
|Статус инстанса (UP или DOWN)
|UP
|__meta_discovery_app_instance_last_updated_date
|Дата последнего обновления данных инстанса в формате yyyy-MM-dd HH:mm:ss
|2022-12-16 15:00:00
|===

=== 2.3. Пример настройки <http_sd_configs>

Ниже приведен пример *prometheus.yml* с настройками *http_sd_configs* для получения списка сервисов для мониторинга

[source,yml]
----
global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'service-discovery'
    http_sd_configs:
      - url: 'http://discovery-server:8761/api/prometheus/sd-configs'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_discovery_app_name]
        target_label: application
      - source_labels: [__meta_discovery_app_instance_name]
        target_label: instance
      - source_labels: [__meta_discovery_app_instance_metrics_path]
        target_label: __metrics_path__
----

