= ECA DATA STORAGE API
:toc: macro

== Введение

   Основным предназначением модуля является сохранение файлов с обучающей выборкой в базу данных.
При этом, система поддерживает файлы следующих форматов: arff, xls, xlsx, csv, json, txt, data, docx, xml.
Система также поддерживает сохранение имен атрибутов, представленных кириллицей. При сохранении в базу,
данные подвергаются следующим преобразованиям:

1. Каждый специальный символ в имени атрибута преобразуется в символ '_'. Отметим, что
к специальным символам не относятся цифры, буквы латинского алфавита и кириллица.

2. Каждый специальный символ в имени таблицы преобразуется в символ '_'.

3. Если длина значения номинального атрибута превышает 255 символов, то оно обрезается
до соответствующей длины.

== 1. Список доступных методов

|===
|Endpoint|Тип запроса|Описание|Формат запроса|Формат ответа
|http://eca-service:8080/eca-data-storage/instances/list
|GET
|Получение списка таблиц с данными
|-
|application/json
|http://eca-service:8080/eca-data-storage/instances/save
|POST
|Запрос на сохранение обучающей выборки на сервер
|multipart/form-data
|application/json
|http://eca-service:8080/eca-data-storage/instances/rename
|PUT
|Изменение названия обучающей выборки
|-
|-
|http://eca-service:8080/eca-data-storage/instances/delete
|DELETE
|Удаление обучающей выборки
|-
|-
|===

== 2. Получение токена доступа к API

Авторизация клиентского приложения осуществляется по протоколу oauth2. Все запросы к API должны сопровождаться авторизационным токеном в заголовке запроса:

Authorization: Bearer YOUR_TOKEN

Для получения авторизационного токена необходимо выполнить следующий запрос:

[source,bash]
----
curl eca_web:web_secret@eca-service:8080/eca-oauth/oauth/token -d grant_type=password -d username=admin -d password=secret
----

где eca_web:web_secret - пара clientId и clientSecret, username и password - логин и пароль пользователя в системе

Запрос возвращает пару access_token/refresh_token: для доступа к API:

[source,json]
----
{
  "access_token": "cf4cd583-b9f1-4dce-8dcc-afefd1510974",
  "token_type": "bearer",
  "refresh_token": "7321ab3a-ee63-4e2e-bdfd-58aaca9fb263",
  "expires_in": 1799,
  "scope": "web"
}
----

где expires_in - время жизни access_token в секундах.

== 3. Описание формата запросов

==== 3.1. Пример загрузки обучающей выборки на сервер

[source,bash]
----
curl -i -X POST -H "Content-Type: multipart/form-data" -H "authorization: Bearer cf4cd583-b9f1-4dce-8dcc-afefd1510974" -F "trainingData=@/home/roman/soybean.arff" -F "tableName=soybean" http://eca-service:8080/eca-data-storage/instances/save
----

где trainingData - файл с обучающей выборкой, tableName - название таблицы БД, в которую необходимо созранить данные

* Примечание: размер файла не должен превышать 10мб.
* Примечание: допускаются только файлы форматов csv, xls, xlsx, arff, json, docx, data, txt

==== 3.2. Пример ответа на запрос о загрузке обучающей выборки на сервер

[source,json]
----
{
  "id": 10,
  "sourceFileName": "soybean.arff",
  "tableName": "soybean",
  "created": true,
  "errorMessage": null
}
----

==== 3.3. Описание параметров ответа на запрос о загрузке обучающей выборки на сервер

|===
|Название поля/атрибута|Тип|Обязательное|Описание|Комментарий
|id
|long
|+
|ID выборки
|-
|sourceFileName
|string
|+
|Название файла источника
|-
|tableName
|string
|-
|Название таблицы, в которую были сохранены данные
|-
|created
|boolean
|+
|Признак успешного сохранения данных
|-
|errorMessage
|string
|-
|Сообщение об ошибке
|-
|===

==== 3.4. Пример запроса на изменение названия данных

[source,bash]
----
curl -i -X PUT -H "authorization: Bearer cf4cd583-b9f1-4dce-8dcc-afefd1510974" -F "id=1" -F "tableName=soybean1" http://eca-service:8080/eca-data-storage/instances/rename
----

где id - ID обучающей выборки, tableName - новое название таблицы БД

==== 3.5. Пример запроса на удаление данных

[source,bash]
----
curl -i -X DELETE -H "authorization: Bearer cf4cd583-b9f1-4dce-8dcc-afefd1510974" -F "id=1" http://eca-service:8080/eca-data-storage/instances/delete
----

где id - ID обучающей выборки

