= Модуль ECA ERS (Evaluation results service)
:toc:
:toc-title: Оглавление

== 1. Описание модуля

Evaluation results service представляет собой сервис, который предназначен для хранения и анализа результатов классификации разнотипных данных с использованием различных алгоритмов классификации, как одиночных так и ансамблевых. Сервис поддерживает хранение таких основных показателей как:

* Точность классификатора
* Дисперсия ошибки классификатора
* Доверительный интервал ошибки классификатора
* Результаты ROC - анализа
* Матрица классификации и др.

Вместе с результами классификации сохраняется полная информация о входных параметрах классификатора, а также обучающая выборка на основе которой была построена модель классификатора.

Сервис также предоставляет API для нахождения оптимальных параметров классификаторов для конкретной обучающей выборки на основе накопленной истории результатов классификации.

== 2. Описание формата отправки результатов классификации

=== 2.1. Структура запроса отправки результатов классификации

[source,json]
----
{
  "requestId": "94c0d852-6beb-424d-a887-a059c033932d",
  "instances": {
    "uuid": "f8cecbf7-405b-403b-9a94-f51e8fb73ed8",
    "relationName": "glass",
    "numInstances": 214,
    "numAttributes": 10,
    "numClasses": 6,
    "className": "type",
    "objectPath": "instances-f8cecbf7-405b-403b-9a94-f51e8fb73ed8.json"
  },
  "classifierReport": {
    "classifierName": "Logistic",
    "options": "{\"type\":\"logistic\",\"maxIts\":200,\"useConjugateGradientDescent\":false}"
  },
  "evaluationMethodReport": {
    "evaluationMethod": "CROSS_VALIDATION",
    "numFolds": 10,
    "numTests": 1,
    "seed": 1
  },
  "statistics": {
    "numTestInstances": 214,
    "numCorrect": 137,
    "numIncorrect": 77,
    "pctCorrect": 64.01869158878505,
    "pctIncorrect": 35.981308411214954,
    "meanAbsoluteError": 0.14376091581568973,
    "rootMeanSquaredError": 0.30208658843903385,
    "maxAucValue": 0.9783783783783784,
    "varianceError": 0.005618757831752862,
    "confidenceIntervalLowerBound": 0.3061910946114487,
    "confidenceIntervalUpperBound": 0.4134350736128503
  },
  "classificationCosts": [
    {
      "classIndex": 0,
      "classValue": "build wind float",
      "truePositiveRate": 0.6428571428571429,
      "falsePositiveRate": 0.19444444444444445,
      "trueNegativeRate": 0.8055555555555556,
      "falseNegativeRate": 0.35714285714285715,
      "rocCurve": {
        "aucValue": 0.8237103174603174,
        "specificity": 0.5694444444444444,
        "sensitivity": 0.9428571428571428,
        "thresholdValue": 0.19192572443021555
      }
    },
    {
      "classIndex": 1,
      "classValue": "vehic wind float",
      "truePositiveRate": 0.11764705882352941,
      "falsePositiveRate": 0.025380710659898477,
      "trueNegativeRate": 0.9746192893401016,
      "falseNegativeRate": 0.8823529411764706,
      "rocCurve": {
        "aucValue": 0.7954613317408181,
        "specificity": 0.8121827411167513,
        "sensitivity": 0.7647058823529411,
        "thresholdValue": 0.08531212420240561
      }
    },
    {
      "classIndex": 2,
      "classValue": "tableware",
      "truePositiveRate": 0.6666666666666666,
      "falsePositiveRate": 0.01951219512195122,
      "trueNegativeRate": 0.9804878048780488,
      "falseNegativeRate": 0.3333333333333333,
      "rocCurve": {
        "aucValue": 0.9550135501355014,
        "specificity": 0.9804878048780488,
        "sensitivity": 0.8888888888888888,
        "thresholdValue": 5.508938596555931E-9
      }
    },
    {
      "classIndex": 3,
      "classValue": "build wind non-float",
      "truePositiveRate": 0.6578947368421053,
      "falsePositiveRate": 0.21014492753623187,
      "trueNegativeRate": 0.7898550724637681,
      "falseNegativeRate": 0.34210526315789475,
      "rocCurve": {
        "aucValue": 0.7545766590389016,
        "specificity": 0.7318840579710144,
        "sensitivity": 0.7236842105263158,
        "thresholdValue": 0.3752861685842112
      }
    },
    {
      "classIndex": 4,
      "classValue": "headlamps",
      "truePositiveRate": 0.8275862068965517,
      "falsePositiveRate": 0.02702702702702703,
      "trueNegativeRate": 0.972972972972973,
      "falseNegativeRate": 0.1724137931034483,
      "rocCurve": {
        "aucValue": 0.9783783783783784,
        "specificity": 0.9297297297297298,
        "sensitivity": 0.9310344827586207,
        "thresholdValue": 2.71767875053676E-29
      }
    },
    {
      "classIndex": 5,
      "classValue": "containers",
      "truePositiveRate": 0.7692307692307693,
      "falsePositiveRate": 0.029850746268656716,
      "trueNegativeRate": 0.9701492537313433,
      "falseNegativeRate": 0.23076923076923078,
      "rocCurve": {
        "aucValue": 0.7975507079984692,
        "specificity": 0.9701492537313433,
        "sensitivity": 0.7692307692307693,
        "thresholdValue": 0.4447975576277138
      }
    }
  ],
  "confusionMatrix": [
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 0,
      "numInstances": 45
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 1,
      "numInstances": 5
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 2,
      "numInstances": 0
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 3,
      "numInstances": 19
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 4,
      "numInstances": 0
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 5,
      "numInstances": 1
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 0,
      "numInstances": 9
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 1,
      "numInstances": 2
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 2,
      "numInstances": 0
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 3,
      "numInstances": 6
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 4,
      "numInstances": 0
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 5,
      "numInstances": 0
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 0,
      "numInstances": 0
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 1,
      "numInstances": 0
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 2,
      "numInstances": 6
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 3,
      "numInstances": 1
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 4,
      "numInstances": 2
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 5,
      "numInstances": 0
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 0,
      "numInstances": 18
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 1,
      "numInstances": 0
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 2,
      "numInstances": 3
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 3,
      "numInstances": 50
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 4,
      "numInstances": 2
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 5,
      "numInstances": 3
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 0,
      "numInstances": 1
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 1,
      "numInstances": 0
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 2,
      "numInstances": 1
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 3,
      "numInstances": 1
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 4,
      "numInstances": 24
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 5,
      "numInstances": 2
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 0,
      "numInstances": 0
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 1,
      "numInstances": 0
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 2,
      "numInstances": 0
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 3,
      "numInstances": 2
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 4,
      "numInstances": 1
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 5,
      "numInstances": 10
    }
  ]
}
----

=== 2.2. Описание полей запроса отправки результатов классификации

==== 2.2.1. Описание полей блока EvaluationResultsRequest

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса в формате UUID
|Данное поле заполняется клиентским приложением
|2
|instances
|InstancesReport
|+
|Блок содержит информацию об обучающей выборке, на основе которой были получены результаты классификации
|
|3
|classifierReport
|ClassifierReport
|+
|Информация о классификаторе
|
|4
|evaluationMethodReport
|EvaluationMethodReport
|+
|Блок содержит информацию о методе оценки точности классификатора
|
|5
|statistics
|StatisticsReport
|+
|Блок с основными показателями точности классификатора
|
|6
|classificationCosts
|array<ClassificationCostsReport>
|-
|Результаты классификации с учетом издержек
|
|7
|confusionMatrix
|array<ConfusionMatrixReport>
|-
|Структура матрицы классификации
|
|===

==== 2.2.2. Описание полей блока InstancesReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Мин. значение|Описание|Комментарий
|1
|uuid
|string
|+
|255
|-
|UUID обучающей выборки
|
|2
|relationName
|string
|+
|255
|-
|Наименовавние данных
|
|3
|numInstances
|integer
|+
|-
|2
|Число объектов обучающей выборки
|
|4
|numAttributes
|integer
|+
|-
|2
|Число атрибутов
|
|5
|numClasses
|integer
|+
|-
|2
|Число классов
|
|6
|className
|string
|+
|255
|-
|Имя атрибута класса
|
|7
|objectPath
|string
|+
|255
|-
|Путь к объекту обучающей выборки в S3
|
|===

==== 2.2.3. Описание полей блока ClassifierReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Описание|Комментарий
|1
|classifierName
|string
|+
|255
|Наименование классификатора
|В качестве имени можно использовать название алгоритма классификации
|2
|options
|string
|+
|-
|Строка с настройками классификатора
|
|===

==== 2.2.4. Описание полей блока EvaluationMethodReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Мин. значение|Описание|Комментарий
|1
|evaluationMethod
|EvaluationMethod
|+
|-
|Метод оценки точности классификатора
|Заполняется по по справочнику <<Справочник значений EvaluationMethod>>
|2
|numFolds
|integer
|-
|2
|Число блоков для k * V - блочной кросс проверки на тестовой выборке
|
|3
|numTests
|integer
|-
|1
|Число тестов для k * V - блочной кросс проверки на тестовой выборке
|
|4
|seed
|integer
|-
|-
|Начальное значение (seed) для генератор псевдослучайных чисел
|
|===

==== 2.2.5. Описание полей блока StatisticsReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Мин. значение|Макс. значение|Описание|Комментарий
|1
|numTestInstances
|integer
|+
|2
|-
|Число объектов тестовых данных
|
|2
|numCorrect
|integer
|+
|0
|-
|Число верно классифицированных объектов
|
|3
|numIncorrect
|integer
|+
|0
|-
|Число неверно классифицированных объектов
|
|4
|pctCorrect
|decimal
|+
|0
|100
|Точность классификатора
|Доля верно классифицированных объектов
|5
|pctIncorrect
|decimal
|+
|0
|100
|Ошибка классификатора
|Доля неверно классифицированных объектов
|6
|meanAbsoluteError
|decimal
|-
|0
|1
|Средняя абсолютная ошибка классификации
|
|7
|rootMeanSquaredError
|decimal
|-
|0
|1
|Среднеквадратическая ошибка классификации
|
|8
|maxAucValue
|decimal
|-
|0
|1
|Максимальное значение показателя AUC среди всех классов
|
|9
|varianceError
|decimal
|-
|0
|1
|Дисперсия ошибки классификатора
|
|10
|confidenceIntervalLowerBound
|decimal
|-
|-
|-
|Нижняя граница 95% доверительного интервала ошибки классификатора
|
|11
|confidenceIntervalUpperBound
|decimal
|-
|-
|-
|Верхняя граница 95% доверительного интервала ошибки классификатора
|
|===

==== 2.2.6. Описание полей блока ClassificationCostsReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Мин. значение|Макс. значение|Описание|Комментарий
|1
|classIndex
|integer
|+
|-
|0
|-
|Индекс класса
|
|2
|className
|string
|+
|255
|-
|-
|Наименование класса
|
|3
|truePositiveRate
|decimal
|+
|-
|0
|1
|Доля верно классифицированных положительных примеров для данного класса
|
|4
|falsePositiveRate
|decimal
|+
|-
|0
|1
|Доля отрицательных примеров, классифицированных как положительные
|
|5
|trueNegativeRate
|decimal
|+
|-
|0
|1
|Доля верно классифицированных отрицательных примеров
|
|6
|falseNegativeRate
|decimal
|+
|-
|0
|1
|Доля положительных примеров, классифицированных как отрицательные
|
|7
|rocCurve
|RocCurveReport
|+
|Данные ROC - анализа
|
|===

==== 2.2.7. Описание полей блока RocCurveReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Мин. значение|Макс. значение|Описание|Комментарий
|1
|aucValue
|decimal
|+
|0
|1
|Значение площади под ROC - кривой для соответствующего класса
|
|2
|specificity
|decimal
|+
|0
|1
|Значение специфичности оптимальной точки ROC - кривой для соответствующего класса
|
|3
|sensitivity
|decimal
|+
|0
|1
|Значение чувствительности оптимальной точки ROC - кривой для соответствующего класса
|
|4
|thresholdValue
|decimal
|+
|0
|1
|Значения оптимальный порога для определения класса
|
|===

==== 2.2.8. Описание полей блока ConfusionMatrixReport

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Мин. значение|Описание|Комментарий
|1
|actualClassIndex
|integer
|+
|-
|0
|Реальное значение класса
|
|2
|predictedClassIndex
|integer
|+
|-
|0
|Прогнозное значение класса
|
|3
|numInstances
|decimal
|+
|-
|0
|Число объектов
|
|===

== 3. Описание формата ответа на запрос о сохранении результатов классификации

=== 3.1. Структура ответа на запрос о сохранении результатов классификации

[source,json]
----
{
  "requestId": "04b1373f-7838-4535-b65a-88c088830879"
}
----

=== 3.2. Описание полей ответа на запрос о сохранении результатов классификации

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса
|Совпадает со значением requestId из запроса
|===

== 4. Описание формата запроса на нахождение оптимальных конфигураций классификаторов

=== 4.1. Структура запроса на нахождение оптимальных конфигураций классификаторов

[source,json]
----
{
  "requestId": "f8cecbf7-405b-403b-9a94-f51e8fb73ed8",
  "dataUuid": "f8cecbf7-405b-403b-9a94-f51e8fb73ed8",
  "evaluationMethodReport": {
    "evaluationMethod": "CROSS_VALIDATION",
    "numFolds": 10,
    "numTests": 1,
    "seed": 1
  },
  "evaluationResultsStatisticsSortFields": null
}
----

=== 4.2. Описание полей запроса на нахождение оптимальных конфигураций классификаторов

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Описание|Комментарий
|1
|requestId
|string
|+
|255
|Уникальный идентификатор запроса
|
|2
|dataUuid
|string
|+
|255
|UUID обучающей выборки для которой будет осуществлен поиск оптимальных параметров классификаторов
|
|3
|evaluationMethodReport
|EvaluationMethodReport
|+
|-
|Блок содержит информацию о методе оценки точности классификатора
|
|4
|evaluationResultsStatisticsSortFields
|array<EvaluationResultsStatisticsSortField>
|-
|3
|Настраиваемый список полей для упорядочивания результатов классификации
|Если поля для сортировки не заданы, то используется сортировка по умолчанию ([PCT_CORRECT->DESC, MAX_AUC_VALUE->DESC, VARIANCE_ERROR->ASC])
|===

==== 4.2.1. Описание полей блока EvaluationResultsStatisticsSortField

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Макс. длина|Описание|Комментарий
|1
|field
|EvaluationResultsStatisticsField
|+
|255
|Название поля для сортировки результатов классификации
|Заполняется по справочнику <<Справочник значений EvaluationResultsStatisticsField>>.
|2
|direction
|SortDirection
|+
|255
|Направление сортировки
|Заполняется по справочнику <<Справочник значений SortDirection>>.
|===

== 5. Описание формата ответа на запрос о нахождении оптимальных конфигураций классификаторов

=== 5.1. Структура ответа на запрос о нахождении оптимальных конфигураций классификаторов

[source,json]
----
{
  "requestId": "f8cecbf7-405b-403b-9a94-f51e8fb73ed8",
  "classifierReports": [
    {
      "classifierName": "ExtraTreesClassifier",
      "options": "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
    {
      "classifierName": "ExtraTreesClassifier",
      "options": "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
    },
    {
      "classifierName": "ExtraTreesClassifier",
      "options": "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
    },
    {
      "classifierName": "ExtraTreesClassifier",
      "options": "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
    },
    {
      "classifierName": "ExtraTreesClassifier",
      "options": "{\"type\":\"extra_trees\",\"numIterations\":20,\"numThreads\":6,\"seed\":1,\"numRandomAttr\":5,\"minObj\":2,\"maxDepth\":0,\"decisionTreeType\":\"ID3\",\"numRandomSplits\":6,\"useBootstrapSamples\":false}"
    }
  ]
}
----

=== 5.2. Описание полей ответа на запрос о нахождении оптимальных конфигураций классификаторов

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса
|
|2
|classifierReports
|array<ClassifierReport>
|+
|Список оптимальных конфигураций классификаторов
|
|===

== 6. Описание формата запроса на получение результатов классификации

=== 6.1. Структура запроса на получение результатов классификации

[source,json]
----
{
  "requestId": "04b1373f-7838-4535-b65a-88c088830879"
}

----

=== 6.2. Описание полей запроса на получение результатов классификации

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса в формате UUID
|
|===

== 7. Описание формата ответа на запрос о получении результатов классификации

=== 7.1. Структура ответа на запрос о получении результатов классификации

[source,json]
----
{
  "requestId": "94c0d852-6beb-424d-a887-a059c033932d",
  "instances": {
    "uuid": "f8cecbf7-405b-403b-9a94-f51e8fb73ed8",
    "relationName": "glass",
    "numInstances": 214,
    "numAttributes": 10,
    "numClasses": 6,
    "className": "type",
    "objectPath": "instances-f8cecbf7-405b-403b-9a94-f51e8fb73ed8.json"
  },
  "classifierReport": {
    "classifierName": "Logistic",
    "options": "{\"type\":\"logistic\",\"maxIts\":200,\"useConjugateGradientDescent\":false}"
  },
  "evaluationMethodReport": {
    "evaluationMethod": "CROSS_VALIDATION",
    "numFolds": 10,
    "numTests": 1,
    "seed": 1
  },
  "statistics": {
    "numTestInstances": 214,
    "numCorrect": 137,
    "numIncorrect": 77,
    "pctCorrect": 64.01869158878505,
    "pctIncorrect": 35.981308411214954,
    "meanAbsoluteError": 0.14376091581568973,
    "rootMeanSquaredError": 0.30208658843903385,
    "maxAucValue": 0.9783783783783784,
    "varianceError": 0.005618757831752862,
    "confidenceIntervalLowerBound": 0.3061910946114487,
    "confidenceIntervalUpperBound": 0.4134350736128503
  },
  "classificationCosts": [
    {
      "classIndex": 0,
      "classValue": "build wind float",
      "truePositiveRate": 0.6428571428571429,
      "falsePositiveRate": 0.19444444444444445,
      "trueNegativeRate": 0.8055555555555556,
      "falseNegativeRate": 0.35714285714285715,
      "rocCurve": {
        "aucValue": 0.8237103174603174,
        "specificity": 0.5694444444444444,
        "sensitivity": 0.9428571428571428,
        "thresholdValue": 0.19192572443021555
      }
    },
    {
      "classIndex": 1,
      "classValue": "vehic wind float",
      "truePositiveRate": 0.11764705882352941,
      "falsePositiveRate": 0.025380710659898477,
      "trueNegativeRate": 0.9746192893401016,
      "falseNegativeRate": 0.8823529411764706,
      "rocCurve": {
        "aucValue": 0.7954613317408181,
        "specificity": 0.8121827411167513,
        "sensitivity": 0.7647058823529411,
        "thresholdValue": 0.08531212420240561
      }
    },
    {
      "classIndex": 2,
      "classValue": "tableware",
      "truePositiveRate": 0.6666666666666666,
      "falsePositiveRate": 0.01951219512195122,
      "trueNegativeRate": 0.9804878048780488,
      "falseNegativeRate": 0.3333333333333333,
      "rocCurve": {
        "aucValue": 0.9550135501355014,
        "specificity": 0.9804878048780488,
        "sensitivity": 0.8888888888888888,
        "thresholdValue": 5.508938596555931E-9
      }
    },
    {
      "classIndex": 3,
      "classValue": "build wind non-float",
      "truePositiveRate": 0.6578947368421053,
      "falsePositiveRate": 0.21014492753623187,
      "trueNegativeRate": 0.7898550724637681,
      "falseNegativeRate": 0.34210526315789475,
      "rocCurve": {
        "aucValue": 0.7545766590389016,
        "specificity": 0.7318840579710144,
        "sensitivity": 0.7236842105263158,
        "thresholdValue": 0.3752861685842112
      }
    },
    {
      "classIndex": 4,
      "classValue": "headlamps",
      "truePositiveRate": 0.8275862068965517,
      "falsePositiveRate": 0.02702702702702703,
      "trueNegativeRate": 0.972972972972973,
      "falseNegativeRate": 0.1724137931034483,
      "rocCurve": {
        "aucValue": 0.9783783783783784,
        "specificity": 0.9297297297297298,
        "sensitivity": 0.9310344827586207,
        "thresholdValue": 2.71767875053676E-29
      }
    },
    {
      "classIndex": 5,
      "classValue": "containers",
      "truePositiveRate": 0.7692307692307693,
      "falsePositiveRate": 0.029850746268656716,
      "trueNegativeRate": 0.9701492537313433,
      "falseNegativeRate": 0.23076923076923078,
      "rocCurve": {
        "aucValue": 0.7975507079984692,
        "specificity": 0.9701492537313433,
        "sensitivity": 0.7692307692307693,
        "thresholdValue": 0.4447975576277138
      }
    }
  ],
  "confusionMatrix": [
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 0,
      "numInstances": 45
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 1,
      "numInstances": 5
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 2,
      "numInstances": 0
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 3,
      "numInstances": 19
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 4,
      "numInstances": 0
    },
    {
      "actualClassIndex": 0,
      "predictedClassIndex": 5,
      "numInstances": 1
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 0,
      "numInstances": 9
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 1,
      "numInstances": 2
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 2,
      "numInstances": 0
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 3,
      "numInstances": 6
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 4,
      "numInstances": 0
    },
    {
      "actualClassIndex": 1,
      "predictedClassIndex": 5,
      "numInstances": 0
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 0,
      "numInstances": 0
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 1,
      "numInstances": 0
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 2,
      "numInstances": 6
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 3,
      "numInstances": 1
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 4,
      "numInstances": 2
    },
    {
      "actualClassIndex": 2,
      "predictedClassIndex": 5,
      "numInstances": 0
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 0,
      "numInstances": 18
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 1,
      "numInstances": 0
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 2,
      "numInstances": 3
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 3,
      "numInstances": 50
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 4,
      "numInstances": 2
    },
    {
      "actualClassIndex": 3,
      "predictedClassIndex": 5,
      "numInstances": 3
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 0,
      "numInstances": 1
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 1,
      "numInstances": 0
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 2,
      "numInstances": 1
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 3,
      "numInstances": 1
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 4,
      "numInstances": 24
    },
    {
      "actualClassIndex": 4,
      "predictedClassIndex": 5,
      "numInstances": 2
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 0,
      "numInstances": 0
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 1,
      "numInstances": 0
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 2,
      "numInstances": 0
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 3,
      "numInstances": 2
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 4,
      "numInstances": 1
    },
    {
      "actualClassIndex": 5,
      "predictedClassIndex": 5,
      "numInstances": 10
    }
  ]
}
----

=== 7.2. Описание полей ответа на запрос о получении результатов классификации

[options="header"]
|===
|№|Название поля|Тип|Обязательное|Описание|Комментарий
|1
|requestId
|string
|+
|Уникальный идентификатор запроса
|
|3
|instances
|InstancesReport
|+
|Блок содержит информацию об обучающей выборке, на основе которой были получены результаты классификации
|
|4
|classifierReport
|ClassifierReport
|+
|Информация о классификаторе
|
|5
|evaluationMethodReport
|EvaluationMethodReport
|+
|Блок содержит информацию о методе оценки точности классификатора
|
|6
|statistics
|StatisticsReport
|+
|Блок с основными показателями точности классификатора
|
|7
|classificationCosts
|array<ClassificationCostsReport>
|-
|Результаты классификации с учетом издержек
|
|8
|confusionMatrix
|array<ConfusionMatrixReport>
|-
|Структура матрицы классификации
|
|===

== 8. Пример ответа с ошибкой

[source,json]
----
[
  {
    "fieldName": null,
    "code": "DataNotFound",
    "errorMessage": "Instances [ionosphere] doesn't exists!"
  }
]
----

== Справочник значений EvaluationMethod

[options="header"]
|===
|№|Значение|Описание
|1
|TRAINING_DATA
|Использование всей обучающей выборки для оценки точности классификатора
|2
|CROSS_VALIDATION
|Метод k * V - блочной кросс проверки на тестовой выборке
|===

== Справочник значений SortDirection

[options="header"]
|===
|№|Код ответа|Описание
|1
|ASC
|Сортировка по возрастанию
|2
|DESC
|Сортировка по убыванию
|===

== Справочник значений EvaluationResultsStatisticsField

[options="header"]
|===
|№|Код ответа|Описание
|1
|PCT_CORRECT
|Точность классификатора
|2
|MAX_AUC_VALUE
|Максимальное значение показателя AUC среди всех классов
|3
|VARIANCE_ERROR
|Дисперсия ошибки классификатора
|===

== Справочник кодов ошибок

[options="header"]
|===
|№|Код ошибки|Описание
|1
|DuplicateRequestId
|Данные с таким requestId уже существуют в базе
|2
|DataNotFound
|В БД не найдена обучающая выборка, заданная в запросе
|3
|ResultsNotFound
|Не удалось найти данные для заданных параметров запроса
|===
