= Метрики системы
:toc:
:toc-title: Оглавление

== Введение

В данном документе приведено описание метрик для всех микросервисов.

== 1. Actuator endpoints

|===
|*Endpoint*|*Описание*|*Пример ответа*
|*http://[host]:[port]/actuator/prometheus*
|Получение всех метрик приложения в формате prometheus
a|
`tomcat_sessions_active_current_sessions{application="eca-mail",} 0.0`

`jvm_buffer_memory_used_bytes{application="eca-mail",id="direct",} 8192.0`

`jvm_buffer_memory_used_bytes{application="eca-mail",id="mapped",} 0.0`

`jvm_memory_max_bytes{application="eca-mail",area="heap",id="G1 Survivor Space",} -1.0`

`jvm_memory_max_bytes{application="eca-mail",area="heap",id="G1 Old Gen",} 4.158652416E9`

...
|*http://[host]:[port]/actuator/info*
|Получение информации о приложении (версия, текущий коммит и т.д.)
a|
[source,json]
----
{
  "git": {
    "local": {
      "branch": {
        "ahead": "NO_REMOTE",
        "behind": "NO_REMOTE"
      }
    },
    "commit": {
      "id": {
        "describe-short": "a38cdbf",
        "abbrev": "a38cdbf",
        "full": "a38cdbf073d964f721ee08a0b183911df744fee5",
        "describe": "a38cdbf"
      },
      "message": {
        "short": "#ES-156 - replaced dependencies",
        "full": "#ES-156 - replaced dependencies"
      },
      "user": {
        "name": "Commit author",
        "email": "Author email"
      },
      "time": "2021-10-21T07:48:53Z"
    },
    "branch": "feature/ES-156",
    "build": {
      "time": "2021-10-21T07:51:45Z",
      "version": "6.1",
      "host": "Roman1993",
      "user": {
        "name": "Commit author",
        "email": "Author email"
      }
    },
    "tags": "",
    "total": {
      "commit": {
        "count": "3317"
      }
    },
    "closest": {
      "tag": {
        "commit": {
          "count": ""
        },
        "name": ""
      }
    },
    "remote": {
      "origin": {
        "url": "https://github.com/Stonnos/eca-service.git"
      }
    },
    "dirty": "false"
  }
}
----
|===

== 2. Бизнес метрики

|===
|*Название метрики*|*Описание*|*Примеры*
|*eca_mail_sending_message_success_total*
|Счетчик числа успешно отправленых email сообщений
a|`eca_mail_sending_message_success_total{application="eca-mail",} 0.0`
|*eca_mail_sending_message_error_total*
|Счетчик числа ошибок при отправке email сообщений
a|`eca_mail_sending_message_error_total{application="eca-mail",} 0.0`
|*core_lock_success_total{application="appName",lockName="processNotSentRetryRequests",}*
|Счетчик числа успешных блокировок processNotSentRetryRequests (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_lock_success_total{application="appName",lockName="processNotSentRetryRequests",} 2.0`
|*core_unlock_success_total{application="appName",lockName="processNotSentRetryRequests",}*
|Счетчик числа успешных операций снятия блокировок processNotSentRetryRequests (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_unlock_success_total{application="appName",lockName="processNotSentRetryRequests",} 2.0`
|*core_lock_failed_total{application="appName",lockName="processNotSentRetryRequests",}*
|Счетчик числа операций, которые не смогли получить блокировку processNotSentRetryRequests по причине data condition (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_lock_failed_total{application="appName",lockName="processNotSentRetryRequests",} 2.0`
|*core_lock_acquire_error_total{application="appName",lockName="processNotSentRetryRequests",}*
|Счетчик числа ошибок при получении блокировки processNotSentRetryRequests (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_lock_acquire_error_total{application="appName",lockName="processNotSentRetryRequests",} 2.0`
|*core_unlock_error_total{application="appName",lockName="processNotSentRetryRequests",}*
|Счетчик числа ошибок при попытке снять блокировку processNotSentRetryRequests (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_unlock_error_total{application="appName",lockName="processNotSentRetryRequests",} 2.0`
|*core_lock_success_total{application="eca-server",lockName="experimentsCronJob",}*
|Счетчик числа успешных блокировок experimentsCronJob (очистка данных эксперимента)
a|`core_lock_success_total{application="eca-server",lockName="experimentsCronJob",} 2.0`
|*core_unlock_success_total{application="eca-server",lockName="experimentsCronJob",}*
|Счетчик числа успешных операций снятия блокировок experimentsCronJob
a|`core_unlock_success_total{application="eca-server",lockName="experimentsCronJob",} 2.0`
|*core_lock_failed_total{application="eca-server",lockName="experimentsCronJob",}*
|Счетчик числа операций, которые не смогли получить блокировку experimentsCronJob по причине data condition
a|`core_lock_failed_total{application="eca-server",lockName="experimentsCronJob",} 2.0`
|*core_lock_acquire_error_total{application="eca-server",lockName="experimentsCronJob",}*
|Счетчик числа ошибок при получении блокировки experimentsCronJob
a|`core_lock_acquire_error_total{application="eca-server",lockName="experimentsCronJob",} 2.0`
|*core_unlock_error_total{application="eca-server",lockName="experimentsCronJob",}*
|Счетчик числа ошибок при попытке снять блокировку experimentsCronJob
a|`core_unlock_error_total{application="eca-server",lockName="experimentsCronJob",} 2.0`
|*core_lock_success_total{application="eca-server",lockName="setActiveClassifiersConfiguration",}*
|Счетчик числа успешных блокировок setActiveClassifiersConfiguration (установка активной конфигурации классификаторов для эксперимента)
a|`core_lock_success_total{application="eca-server",lockName="setActiveClassifiersConfiguration",} 2.0`
|*core_unlock_success_total{application="eca-server",lockName="setActiveClassifiersConfiguration",}*
|Счетчик числа успешных операций снятия блокировок setActiveClassifiersConfiguration
a|`core_unlock_success_total{application="eca-server",lockName="setActiveClassifiersConfiguration",} 2.0`
|*core_lock_acquire_error_total{application="eca-server",lockName="setActiveClassifiersConfiguration",}*
|Счетчик числа ошибок при получении блокировки setActiveClassifiersConfiguration
a|`core_lock_acquire_error_total{application="eca-server",lockName="setActiveClassifiersConfiguration",} 2.0`
|*core_unlock_error_total{application="eca-server",lockName="setActiveClassifiersConfiguration",}*
|Счетчик числа ошибок при попытке снять блокировку setActiveClassifiersConfiguration
a|`core_unlock_error_total{application="eca-server",lockName="setActiveClassifiersConfiguration",} 2.0`
|*core_lock_success_total{application="eca-server",lockName="experiment",}*
|Счетчик числа успешных блокировок experiment (обработка заявки на эксперимент)
a|`core_lock_success_total{application="eca-server",lockName="experiment",} 2.0`
|*core_unlock_success_total{application="eca-server",lockName="experiment",}*
|Счетчик числа успешных операций снятия блокировок experiment
a|`core_unlock_success_total{application="eca-server",lockName="experiment",} 2.0`
|*core_lock_failed_total{application="eca-server",lockName="experiment",}*
|Счетчик числа операций, которые не смогли получить блокировку experiment по причине data condition
a|`core_lock_failed_total{application="eca-server",lockName="experiment",} 2.0`
|*core_lock_acquire_error_total{application="eca-server",lockName="experiment",}*
|Счетчик числа ошибок при получении блокировки experiment
a|`core_lock_acquire_error_total{application="eca-server",lockName="experiment",} 2.0`
|*core_unlock_error_total{application="eca-server",lockName="experiment",}*
|Счетчик числа ошибок при попытке снять блокировку experiment
a|`core_unlock_error_total{application="eca-server",lockName="experiment",} 2.0`
|*core_retry_request_cache_size_total{application="appName",request_type="auditRequest",}*
|Счетчик числа запросов, которые были сохранены в кэш для повторной отправки в сервис аудита (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_retry_request_cache_size_total{application="appName",request_type="auditRequest",} 1.0`
|*core_retry_request_error_total{application="appName",request_type="auditRequest",}*
|Счетчик числа ошибок для запросов, которые не были сохранены в кэш для повторной отправки в сервис аудита (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_retry_request_error_total{application="appName",request_type="auditRequest",} 0.0`
|*core_retries_failed_total{application="appName",request_type="auditRequest",}*
|Счетчик числа неуспешных попыток повторной отправки запросов в сервис аудита (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_retries_failed_total{application="appName",request_type="auditRequest",} 3.0`
|*core_retries_success_total{application="appName",request_type="auditRequest",}*
|Счетчик числа успешных попыток повторной отправки запросов в сервис аудита (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_retries_success_total{application="appName",request_type="auditRequest",} 1.0`
|*core_retries_exhausted_total{application="appName",request_type="auditRequest",}*
|Счетчик числа превышений лимита попыток для повторной отправки запросов в сервис аудита (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_retries_exhausted_total{application="appName",request_type="auditRequest",} 0.0`
|*core_retries_error_total{application="appName",request_type="auditRequest",}*
|Счетчик числа критических ошибок при повторной отправки запросов в сервис аудита (для application: eca-server, eca-oauth, eca-data-storage)
a|`core_retries_error_total{application="appName",request_type="auditRequest",} 0.0`
|*core_retry_request_cache_size_total{application="appName",request_type="emailRequest",}*
|Счетчик числа запросов, которые были сохранены в кэш для повторной отправки в email сервис (для application: eca-server, eca-oauth)
a|`core_retry_request_cache_size_total{application="appName",request_type="emailRequest",} 1.0`
|*core_retry_request_error_total{application="appName",request_type="emailRequest",}*
|Счетчик числа ошибок для запросов, которые не были сохранены в кэш для повторной отправки в email сервис (для application: eca-server, eca-oauth)
a|`core_retry_request_error_total{application="appName",request_type="emailRequest",} 0.0`
|*core_retries_failed_total{application="appName",request_type="emailRequest",}*
|Счетчик числа неуспешных попыток повторной отправки запросов в email сервис (для application: eca-server, eca-oauth)
a|`core_retries_failed_total{application="appName",request_type="emailRequest",} 3.0`
|*core_retries_success_total{application="appName",request_type="emailRequest",}*
|Счетчик числа успешных попыток повторной отправки запросов в email сервис (для application: eca-server, eca-oauth)
a|`core_retries_success_total{application="appName",request_type="emailRequest",} 1.0`
|*core_retries_exhausted_total{application="appName",request_type="emailRequest",}*
|Счетчик числа превышений лимита попыток для повторной отправки запросов в email сервис (для application: eca-server, eca-oauth)
a|`core_retries_exhausted_total{application="appName",request_type="emailRequest",} 0.0`
|*core_retries_error_total{application="appName",request_type="emailRequest",}*
|Счетчик числа критических ошибок при повторной отправки запросов в email сервис (для application: eca-server, eca-oauth)
a|`core_retries_error_total{application="appName",request_type="emailRequest",} 0.0`
|*core_retry_request_cache_size_total{application="eca-server",request_type="ersEvaluationResultsRequest",}*
|Счетчик числа запросов, которые были сохранены в кэш для повторной отправки в ERS сервис
a|`core_retry_request_cache_size_total{application="eca-server",request_type="ersEvaluationResultsRequest",} 1.0`
|*core_retry_request_error_total{application="eca-server",request_type="ersEvaluationResultsRequest",}*
|Счетчик числа ошибок для запросов, которые не были сохранены в кэш для повторной отправки в ERS сервис
a|`core_retry_request_error_total{application="eca-server",request_type="ersEvaluationResultsRequest",} 0.0`
|*core_retries_failed_total{application="eca-server",request_type="ersEvaluationResultsRequest",}*
|Счетчик числа неуспешных попыток повторной отправки запросов в ERS сервис
a|`core_retries_failed_total{application="eca-server",request_type="ersEvaluationResultsRequest",} 3.0`
|*ore_retries_success_total{application="eca-server",request_type="ersEvaluationResultsRequest",}*
|Счетчик числа успешных попыток повторной отправки запросов в ERS сервис
a|`core_retries_success_total{application="eca-server",request_type="ersEvaluationResultsRequest",} 1.0`
|*core_retries_exhausted_total{application="eca-server",request_type="ersEvaluationResultsRequest",}*
|Счетчик числа превышений лимита попыток для повторной отправки запросов в ERS сервис
a|`core_retries_exhausted_total{application="eca-server",request_type="ersEvaluationResultsRequest",} 0.0`
|*core_retries_error_total{application="eca-server",request_type="ersEvaluationResultsRequest",}*
|Счетчик числа критических ошибок при повторной отправки запросов в ERS сервис
a|`core_retries_error_total{application="eca-server",request_type="ersEvaluationResultsRequest",} 0.0`
|**
|===

== 3. Метрики Feign http клиента

|===
|*Название метрики*|*Описание*|*Примеры*
|*feign_Client_http_response_code_total*
|Счетчик числа ответов, параметризированный по http коду ответа (http_status), названию метода (method), имя вызываемого сервиса (host).
a|
`feign_Client_http_response_code_total{application="eca-server",client="com.ecaservice.server.service.auth.UsersClient",host="eca-oauth",http_status="200",method="getUserInfo",status_group="2xx",} 1.0`

`feign_Client_http_response_code_total{application="eca-server",client="com.ecaservice.core.audit.service.AuditEventClient",host="eca-audit-log",http_status="200",method="sendEvent",status_group="2xx",} 1.0`

`feign_Client_http_response_code_total{application="eca-server",client="com.ecaservice.server.service.push.WebPushClient",host="eca-web-push",http_status="200",method="push",status_group="2xx",} 2.0`

`feign_Client_http_response_code_total{application="eca-server",client="com.ecaservice.server.service.experiment.mail.EmailClient",host="eca-mail",http_status="200",method="sendEmail",status_group="2xx",} 3.0`

`feign_Client_http_response_code_total{application="eca-server",client="com.ecaservice.server.service.ers.ErsClient",host="eca-ers",http_status="200",method="getEvaluationResults",status_group="2xx",} 1.0`

`feign_Client_http_response_code_total{application="eca-server",client="com.ecaservice.server.service.ers.ErsClient",host="eca-ers",http_status="200",method="save",status_group="2xx",} 5.0`
|*feign_Client_seconds_count*
|Счетчик числа http запросов, параметризированный по названию метода (method), имя вызываемого сервиса (host).
a|
`feign_Client_seconds_count{application="eca-server",client="com.ecaservice.server.service.experiment.mail.EmailClient",host="eca-mail",method="sendEmail",} 3.0`

`feign_Client_seconds_count{application="eca-server",client="com.ecaservice.core.audit.service.AuditEventClient",host="eca-audit-log",method="sendEvent",} 1.0`

`feign_Client_seconds_count{application="eca-server",client="com.ecaservice.server.service.ers.ErsClient",host="eca-ers",method="save",} 5.0`

`feign_Client_seconds_count{application="eca-server",client="com.ecaservice.server.service.ers.ErsClient",host="eca-ers",method="getEvaluationResults",} 1.0`

`feign_Client_seconds_count{application="eca-server",client="com.ecaservice.server.service.auth.UsersClient",host="eca-oauth",method="getUserInfo",} 1.0`

`feign_Client_seconds_count{application="eca-server",client="com.ecaservice.server.service.push.WebPushClient",host="eca-web-push",method="push",} 2.0`
|*feign_Client_seconds_sum*
|Счетчик суммарного времени выполнения http запроса, параметризированный по названию метода (method), имя вызываемого сервиса (host).
a|
`feign_Client_seconds_sum{application="eca-server",client="com.ecaservice.server.service.experiment.mail.EmailClient",host="eca-mail",method="sendEmail",} 2.171083791`

`feign_Client_seconds_sum{application="eca-server",client="com.ecaservice.core.audit.service.AuditEventClient",host="eca-audit-log",method="sendEvent",} 0.12708842`

`feign_Client_seconds_sum{application="eca-server",client="com.ecaservice.server.service.ers.ErsClient",host="eca-ers",method="save",} 2.123148685`

`feign_Client_seconds_sum{application="eca-server",client="com.ecaservice.server.service.ers.ErsClient",host="eca-ers",method="getEvaluationResults",} 0.080737109`

`feign_Client_seconds_sum{application="eca-server",client="com.ecaservice.server.service.auth.UsersClient",host="eca-oauth",method="getUserInfo",} 0.034848082`

`feign_Client_seconds_sum{application="eca-server",client="com.ecaservice.server.service.push.WebPushClient",host="eca-web-push",method="push",} 0.0777714`
|*feign_Client_seconds_max*
|Макс. время выполнения http запроса.
a|
`feign_Client_seconds_max{application="eca-server",client="com.ecaservice.server.service.experiment.mail.EmailClient",host="eca-mail",method="sendEmail",} 0.0`

`feign_Client_seconds_max{application="eca-server",client="com.ecaservice.core.audit.service.AuditEventClient",host="eca-audit-log",method="sendEvent",} 0.0`

`feign_Client_seconds_max{application="eca-server",client="com.ecaservice.server.service.ers.ErsClient",host="eca-ers",method="save",} 1.991423887`

`feign_Client_seconds_max{application="eca-server",client="com.ecaservice.server.service.ers.ErsClient",host="eca-ers",method="getEvaluationResults",} 0.080737109`

`feign_Client_seconds_max{application="eca-server",client="com.ecaservice.server.service.auth.UsersClient",host="eca-oauth",method="getUserInfo",} 0.0`

`feign_Client_seconds_max{application="eca-server",client="com.ecaservice.server.service.push.WebPushClient",host="eca-web-push",method="push",} 0.070433362`
|===

== 4. Метрики http запросов

|===
|*Название метрики*|*Описание*|*Примеры*
|*http_server_requests_seconds_count*
|Счетчик числа http запросов, параметризированный имени сервиса (application), по названию метода (uri), коду ответа (status).
a|
`http_server_requests_seconds_count{application="eca-ers",exception="None",method="POST",outcome="SUCCESS",status="200",uri="/api/save",} 1.0`
|*http_server_requests_seconds_sum*
|Счетчик суммарного времени выполнения http запроса, параметризированный имени сервиса (application), по названию метода (uri), коду ответа (status).
a|
`http_server_requests_seconds_sum{application="eca-ers",exception="None",method="POST",outcome="SUCCESS",status="200",uri="/api/save",} 0.221839122`
|*http_server_requests_seconds_max*
|Макс. время выполнения http запроса
a|
`http_server_requests_seconds_max{application="eca-ers",exception="None",method="POST",outcome="SUCCESS",status="200",uri="/api/save",} 0.221839122`
