spring:
  application:
    name: eca-audit-log
  ## Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/audit_log
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        order_by:
          default_null_ordering: last
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  cache:
    cache-names: global-filters, filter-templates, filter-dictionaries
    caffeine:
      spec: maximumSize=100, expireAfterWrite=18000s

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

## Swagger properties
open-api:
  basePath: /
  title: Microservice for collecting and storing audit events
  description: API provides operations with audit events
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@
  tokenBaseUrl: http://localhost:8080
  apiAuth:
    PASSWORD:
      scopes: web

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      client-secret: swagger_secret
    disable-swagger-default-url: true

auth-server:
  baseUrl: http://localhost:8085/eca-oauth
  clientId: eca_service_tech
  clientSecret: 02#eca_service_tech6

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full

server:
  forward-headers-strategy: framework
