= Библиотека аудита
:toc:
:toc-title: Оглавление

== Введение

В данном документе приведена инструкция для подключения библиотеки аудита к spring boot приложению.

== 1. Подключение библиотеки

Для начала, необходимо добавить зависимость в pom.xml

[source,xml]
----
<dependency>
    <groupId>eca.service</groupId>
    <artifactId>core-audit</artifactId>
    <version>${project.version}</version>
</dependency>
----

В файле application.yml добавить настройки библиотеки

[source,yml]
----
audit:
  ## Вкл. отправку событий аудита
  enabled: true
  ## Флаг асинхронной отправки событий аудита
  asyncEvents: true
  ## Размер пула потоков для асинхронной отправки событий аудита
  threadPoolSize: 3
  ## Вкл./выкл. режима повторной отправки событий аудита в случае недоступности сервиса аудита
  redelivery: true
  ## Интервал между запусками заданий на повторную отправку событий аудита
  redeliveryIntervalMillis: 60000
  ## Размер страницы для повторной отправки событий аудита
  pageSize: 25
----

С помощью аннотации @EnableAudit импортировать бины библиотеки

[source,java]
----
@EnableAudit
// Если в вашем модуле есть JPA сущности, то указать путь для сканирования
@EntityScan(basePackageClasses = MyEntity.class)
// Если в вашем модуле есть JPA репозитории, то указать путь для сканирования
@EnableJpaRepositories(basePackageClasses = MyEntityRepository.class)
@Configuration
public class AppConfiguration {

    /**
     * Creates custom audit event initiator bean.
     *
     * @return audit event initiator bean
     */
    @Primary
    @Bean
    public AuditEventInitiator auditEventInitiator() {
        return () -> SecurityContextHolder.getContext().getAuthentication().getName();
    }
}
----

Обратите внимание, что в конфигурации можно переопределить основной бин AuditEventInitiator, который
предоставляет единственный метод getInitiator для получения инициатора события аудита, например текущего
авторизированного пользователя.

В конфигурационный файл liquibase, добавить путь к файлу audit-changelog.xml со скриптами для создания служебных таблиц аудита

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd">
    <!-- your change sets -->
    <include file="../audit-changelog.xml" relativeToChangelogFile="true"/>
</databaseChangeLog>
----

== 2. Описание таблиц для хранения шаблонов аудита

Таблица 2.1 - 'audit_group' - содержит данные о группах событий аудита
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                      |varchar(255)     |+|+|+                              |Код группы (первичный ключ)
|title                   |varchar(255)     |-|-|-                              |Описание группы
|===

Таблица 2.2 - 'audit_code' - содержит данные о кодах событий аудита
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                      |varchar(255)     |+|+|+                              |Код события (первичный ключ)
|title                   |varchar(255)     |-|-|-                              |Описание кода
|enabled                 |boolean          |-|+|-                              |Вкл./выкл. кода события
|audit_group_id          |varchar(255)     |-|+|fk_audit_code_group_id         |Внешний ключ группы событий
|===

Таблица 2.3 - 'audit_event_template' - содержит данные о шаблонах событий аудита
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                               |bigint           |+|+|+                                  |Идентификатор записи (первичный ключ)
|event_type                       |varchar(255)     |-|+|+                                  |Тип события
|message_template                 |varchar(1024)    |-|+|-                                  |Шаблон сообщения
|audit_code_id                    |varchar(255)     |-|+|fk_audit_event_template_code_id    |Внешний ключ кода события
|===

Таблица содержит уникальный индекс audit_event_template_code_id_event_type_unique_index на поля audit_code_id, event_type

Таблица 2.4 - 'audit_event_request' - содержит данные о запросах с событиями аудита
[cols="^20%,^14%,^8%,^8%,^8%,^30%",options="header"]
|===
|Название колонки|Тип|Unique|Not NULL|Индекс|Описание
|id                      |bigint           |+|+|+                              |Идентификатор записи (первичный ключ)
|event_id                |varchar(255)     |-|+|-                              |Внешний ID события
|message                 |text             |-|+|-                              |Текст сообщения
|initiator               |varchar(255)     |-|+|-                              |Источник события, например имя пользователя
|event_type              |varchar(255)     |-|+|-                              |Тип события
|group_code              |varchar(255)     |-|+|-                              |Код группы событий
|group_title             |varchar(255)     |-|-|-                              |Описание группы событий
|audit_code              |varchar(255)     |-|+|-                              |Код события
|audit_code_title        |varchar(255)     |-|-|-                              |Описание кода события
|event_date              |timestamp        |-|+|-                              |Дата наступления события
|event_status            |varchar(255)     |-|+|-                              |Статус отправки события аудита в сервис аудита (SENT, NOT_SENT, ERROR)
|details                 |text             |-|-|-                              |Дополнительная информация, например текст ошибки
|sent_date               |timestamp        |-|-|-                              |Дата отправки события аудита в сервис аудита
|===

== 3. Настройка шаблонов с событиями аудита

События аудита создаются по следующей схеме:

* Каждый шаблон события привязывается к уникальному коду события.
* Каждый код события привязывается к определенной группе событий. Это дает возможность привязывать
набор событий аудита к определенной группе, например действия пользователя в личном кабинете.

=== 3.1. Настройка групп событий

Пример csv файла с группами событий для импорта в базу данных:

[source,csv]
----
id;title
USER_PROFILE_ACTIONS;Действия пользователя в личном кабинете
----

=== 3.2. Настройка кодов событий

Пример csv файла с кодами событий для импорта в базу данных:

[source,csv]
----
id;title;enabled;audit_group_id
ENABLE_2FA;Включение двухфакторной аутентификации;true;USER_PROFILE_ACTIONS
DISABLE_2FA;Выключение двухфакторной аутентификации;true;USER_PROFILE_ACTIONS
UPDATE_PERSONAL_DATA;Изменение персональных данных;true;USER_PROFILE_ACTIONS
LOCK_USER;Блокировка пользователя;true;USER_PROFILE_ACTIONS
UNLOCK_USER;Снятие блокировки пользователя;true;USER_PROFILE_ACTIONS
----

=== 3.3. Настройка шаблонов событий

Пример csv файла с шаблонами событий для импорта в базу данных:

[source,csv]
----
id;event_type;message_template;audit_code_id
1;SUCCESS;Включена двухфакторной аутентификации;ENABLE_2FA
2;SUCCESS;Выключена двухфакторная аутентификация;DISABLE_2FA
3;SUCCESS;Персональные данные были изменены;UPDATE_PERSONAL_DATA
4;SUCCESS;Пользователь [${returnValue.login}] был заблокирован;LOCK_USER
5;SUCCESS;Блокировка пользователя [${returnValue.login}] была снята;UNLOCK_USER
----

В шаблоне события (поле message_template) можно задавать селекторы со следующими переменными:

* Входные переменные метода java класса. Переменными могут быть примитивные типы и сложные объекты.
Для доступа к полю объекта используется следующий синтаксис myInputParam.field1Value
* Возвращаемое значение метода java класса. Доступ к объекту возвращаемого значения осуществляется с использованием переменной
returnValue
