FROM tomcat:8-jre8
RUN mkdir -p /home/experiment/data
ADD wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
COPY target/eca-server.war /usr/local/tomcat/webapps/
ENTRYPOINT exec /wait-for-it.sh eca-db:5432 --timeout=$DB_CONTAINER_WAIT_TIMEOUT -- catalina.sh run