FROM openjdk:8
RUN mkdir -p /home/experiment/data
ADD wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
COPY target/eca-server.war eca-server.war
ENTRYPOINT exec /wait-for-it.sh eca-db:5432 --timeout=$DB_CONTAINER_WAIT_TIMEOUT -- java $JAVA_OPTS -jar eca-server.war