spring:
  application:
    name: eca-external-api-tests
  jmx:
    default-domain: eca-external-api-tests
  ## Datasource properties
  datasource:
    jdbc-url: jdbc:h2:mem:autotestdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  camunda:
    jdbc-url: jdbc:h2:mem:camundadb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

security:
  oauth2:
    client:
      clientId: external-api
      clientSecret: external_api_secret
      accessTokenUri: http://localhost:8080/eca-oauth/oauth/token
      grant-type: client_credentials

external-api-tests:
  url: http://localhost:8080
  testDataPath: classpath*:requests/**/*.json
  numThreads: 1
  workerThreadTimeoutInSeconds: 180
  pageSize: 25
  delaySeconds: 2

process:
  processId: ExternalApiAutoTestProcess

## Swagger properties
open-api:
  basePath: /
  title: External API auto tests execution
  description: API provides operations for external API auto tests
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@

server:
  port: 8090
