spring:
  application:
    name: eca-external-api-tests
  ## Datasource properties
  datasource:
    jdbc-url: jdbc:h2:mem:autotestdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  camunda:
    jdbc-url: jdbc:h2:mem:camundadb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

external-api-tests:
  url: http://localhost:8080
  evaluationTestDataPath: classpath*:evaluation-requests/**/*.json
  experimentTestDataPath: classpath*:experiment-requests/**/*.json
  numThreads: 10
  workerThreadTimeoutInSeconds: 180
  pageSize: 25
  delaySeconds: 2
  expectedExperimentNumModels: 5
  auth:
    clientId: external-api
    clientSecret: external_api_secret
    tokenUrl: http://localhost:8080/eca-oauth/oauth/token

process:
  ids:
    EVALUATION_REQUEST_PROCESS: EvaluationApiAutoTestProcess
    EXPERIMENT_REQUEST_PROCESS: ExperimentApiAutoTestProcess

## Swagger properties
open-api:
  basePath: /
  title: External API auto tests execution
  description: API provides operations for external API auto tests
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

server:
  port: 8090
