spring:
  application:
    name: eca-external-api-tests
  jmx:
    default-domain: eca-external-api-tests
  ## Datasource properties
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  cache:
    cache-names: instances
    caffeine:
      spec: maximumSize=10, expireAfterWrite=180s

security:
  oauth2:
    client:
      clientId: external-api
      clientSecret: external_api_secret
      accessTokenUri: http://localhost:8080/eca-oauth/oauth/token
      grant-type: client_credentials

external-api-tests:
  numThreads: 3
  workerThreadTimeoutInSeconds: 180
  pageSize: 25
  delaySeconds: 2

## Swagger properties
swagger2:
  projectVersion: @project.version@
  groups:
    eca-external-api-tests:
      title: External API tests execution
      description: Operations for external API tests managment
      author: Roman Batygin
      email: roman.batygin@mail.ru

server:
  port: 8090