FROM tomcat:8-jre8
ADD scripts/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
ENTRYPOINT [ "/wait-for-it.sh", "eca-server:8080", "-t 60", "--" ]
COPY target/eca-web.war /usr/local/tomcat/webapps/
CMD ["catalina.sh", "run"]