spring:
  application:
    name: eca-data-storage
  ## Datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/data_storage
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    contexts: schema,data
    change-log: classpath:db/liquibase-changelog.xml
  cache:
    cache-names: attributes, attributes-statistics, global-filters, filter-templates, filter-dictionaries, sort-fields
    caffeine:
      spec: maximumSize=100, expireAfterWrite=1800s
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          api-client:
            client-id: eca_service_tech
            client-secret: 02#eca_service_tech6
            scope: web
            authorization-grant-type: client_credentials
            provider: api-client
        provider:
          api-client:
            token-uri: http://localhost:8085/oauth2/token

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

lock:
  enabled: true

eca-ds:
  dateFormat: yyyy-MM-dd HH:mm:ss
  batchSize: 100
  reportsPath: reports-config.json
  supportedDataFileExtensions: csv, arff, xls, xlsx, json, txt, data

## Swagger properties
open-api:
  basePath: /
  title: Microservice for storaging training data sets
  description: API provides operations with training data sets for ECA web application
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@
  tokenBaseUrl: http://localhost:8080
  apiAuth:
    PASSWORD:
      scopes: web

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger
      client-secret: swagger_secret
    disable-swagger-default-url: true

resource:
  server:
    security:
      whitelistUrls:
        - /api/internal/**

auth-server:
  baseUrl: http://localhost:8085/eca-oauth
  clientId: eca_service_tech
  clientSecret: 02#eca_service_tech6

management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        fields:
          - tx.id
      remote-fields:
        - tx.id
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      enabled: true
      mode: full

server:
  forward-headers-strategy: framework
